version: 2
sources:
  - name: sri_open_schema
    description: ''
    tables:
      - name: sci_all_lmpcrg
        description: ''
      - name: sci_all_subprof
        description: ''   
      - name: prty_rltd
        description: '' 
      - name: m_entity_setoff_xlate
        description: ''   
               

                      
    tags: ['sit']
