version: 2
sources:
  - name: sri_open_schema
    description: 'SIT Schema'
    tables:
      - name: ebbs_in_mast
        description: 'EBBS Master table for country India'
        columns:
          - name: ebbs_mast_id
            description: 'Unique identifier for the EBBS Master record'
            data_type: 'STRING'
          - name: ebbs_mast_name
            description: 'Name of the EBBS Master record'
            data_type: 'STRING'
          - name: ebbs_mast_description
            description: 'Description of the EBBS Master record'
            data_type: 'STRING'
          - name: ebbs_mast_created_at
            description: 'Timestamp when the EBBS Master record was created'
            data_type: 'TIMESTAMP'
          - name: ebbs_mast_updated_at
            description: 'Timestamp when the EBBS Master record was last updated'
            data_type: 'TIMESTAMP'
    
      - name: ebbs_in_mastrell
        description: 'EBBS Master Relationship table'
      - name: ebbs_mast
        description: 'EBBS Master table'
      - name: sci_all_bkgloc
        description:  'All Book Locations table'
      - name: ebbs_account
        description:   'EBBS Account table'
      - name: ebbs_in_account
        description:   'EBBS India Account table'
      - name: ebbs_in_acctprv
        description:     'EBBS Master table' 
      - name: ebbs_in_acinthis
        description:     'EBBS Master table' 
      - name: ebbs_in_arm
        description: 'EBBS Master table'
      - name: ebbs_in_bebal
        description: 'EBBS Master table'
      - name: ebbs_cbalstat
        description: 'EBBS Master table'
      - name: ebbs_const
        description: 'EBBS Master table' 
      - name: ebbs_dealprv
        description: 'EBBS Master table'
      - name: ebbs_in_excrtl
        description: 'EBBS India Master table'
      - name: ebbs_in_instcls
        description: 'EBBS Master table'
      - name: ebbs_in_lmtlndt
        description: 'EBBS Master table'      
      - name: ebbs_in_mdeltyp
        description: 'EBBS Master table'
      - name: ebbs_in_mstinfo
        description: 'EBBS Master table'
      - name: ebbs_in_odclass
        description: 'EBBS Master table'
      - name: ebbs_in_dlinthis
        description: 'EBBS Master table'
      - name: ebbs_in_dlintsh
        description: 'EBBS Master table'
      - name: ebbs_in_rel
        description: 'EBBS Master table'
      - name: ebbs_in_relinfo
        description: 'EBBS Master table'
      - name: ebbs_in_rskind
        description: 'EBBS Master table'
      - name: ebbs_in_const
        description: 'EBBS Master table'
      - name: ebbs_in_pmmkdeal
        description: 'EBBS Master table' 
      - name: ebbs_in_cbalstat
        description: 'EBBS Master table'   
      - name: ebbs_in_prd
        description: 'EBBS Master table'  
      - name: ebbs_in_prvinfo
        description: 'EBBS Master table'    
      - name: ebbs_in_dealprv
        description: 'EBBS Master table' 
      - name: ebbs_in_dlinfo
        description: 'EBBS Master table'
      - name: ebbs_in_trnchsb
        description: 'EBBS Master table'
      - name: ebbs_in_intpl
        description: 'EBBS Master table' 
      - name: ebbs_in_intpldt
        description: 'EBBS Master table'   
      - name: ebbs_in_intcurr
        description: 'EBBS Master table'  
      - name: ebbs_in_intdtl
        description: 'EBBS Master table'         
      - name: ebbs_in_accinfo
        description: '' 
      - name: ebbs_in_mltmast
        description: '' 
      - name: m_product_xlate
        description: ''  
      - name: ebbs_in_brn
        description: ''                                         
      - name: ebbs_in_seg
        description: ''    
      - name: ebbs_in_reason
        description: ''     
      - name: ebbs_acinthis
        description: ''   
      - name: m_scb_entity_xlate
        description: ''    
      - name: m_cdl_glbu_to_entcd_bkcd_xlate
        description: ''    
      - name: alt_prty
        description: '' 
      - name: prty
        description: ''        
      - name: ebbs_dlinfo
        description: ''       
      - name: ebbs_trnchsb
        description: ''       
      - name: ebbs_dlinthis
        description: ''  
      - name: ebbs_dlintsh
        description: ''   
      - name: sub_ldgr
        description: ''    
      - name: acct
        description: '' 
      - name: chrt_of_acct
        description: '' 
      - name: m_ifrs9_acct_class_xlate
        description: ''   
      - name: m_psgl_src_lsdr_src_sys_xlate
        description: '' 
      - name: m_gl_acct_amt_grp
        description: ''  
      - name: acct_bal
        description: ''       
      - name: prvsn
        description: ''                     
      - name: prty_rtng
        description: '' 
      - name: ebbs_relinfo
        description: ''       
      - name: ebbs_rskind
        description: ''     
      - name: ebbs_rel
        description: ''                
      - name: with_prty_ebbs_rskind
        description: '' 
      - name: with_prty_ebbs_relinfo
        description: '' 
      - name: with_prty_ebbs_mastrel1
        description: ''  
      - name: with_prty_ebbs_mastrel2
        description: '' 
      - name: with_prty_ebbs_mast
        description: ''  
      - name: with_prty_ebbs_mstinfo
        description: ''     
      - name: ebbs_dsa_slpd_bs
        description: ''   
      - name: m_gl_product_xlate
        description: ''                                             
        


                                                                           
    tags: ['sit']
