apiVersion: v1
kind: Pod
metadata:
  name: xxx-k8s-pod-template
  annotations:
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/agent-pre-populate-only : "true"
    vault.hashicorp.com/agent-set-security-context: 'true'
    vault.hashicorp.com/agent-run-as-user: '1002'
    vault.hashicorp.com/agent-run-as-group: '1002'
    vault.hashicorp.com/agent-inject-token: 'true'
    vault.hashicorp.com/agent-init-json-patch: '[{"op": "replace", "path": "/securityContext/seccompProfile",
      "value": {"type": "RuntimeDefault"}}]'
    vault.hashicorp.com/agent-json-patch: '[{"op": "replace", "path": "/securityContext/seccompProfile",
      "value": {"type": "RuntimeDefault"}}]'
    vault.hashicorp.com/agent-service-account-token-volume-name: vault-auth
    vault.hashicorp.com/role: my-role
    vault.hashicorp.com/agent-inject-secret-s3-authorizer-secret: 'xxx/my-role'
    vault.hashicorp.com/agent-inject-template-s3-authorizer-secret: |
      {{- with secret "xxx/my-role" -}}
      {{ .Data.username }}
      {{ .Data.password }}
      {{- end }}
    vault.hashicorp.com/secret-volume-path: /var/run/secret/auth/
spec:
  automountServiceAccountToken: false
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
    supplementalGroups: [1000]
  containers:
    - name: xxx-k8s-pod-template
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - "ALL"
      imagePullPolicy: Always
      env:
        - name: S3_AUTHORIZER_SERVER_BASE_URL
          value: "https://xxx.com"
        - name: S3_ENDPOINT_URL
          value: "https://xxx:1234"
        - name: AWS_ACCESS_KEY
          value: "NO_NEED"
        - name: AWS_SECRET_KEY
          value: "NO_NEED"
        - name: S3_AUTHORIZER_AUTH_FILE
          value: "/var/run/secret/auth/s3-authorizer-secret"
        - name: HIVE_ENDPOINT_URL
          value: "thrift://xxx:9083"
        - name: HIVE_TRUSTSTORE_CRD
          valueFrom:
            secretKeyRef:
              name: hive-credential
              key: HIVE_TRUSTSTORE_CRD
        - name: DATAHUB_REST_TOKEN
          valueFrom:
            secretKeyRef:
              name: datahub-credential
              key: DATAHUB_REST_TOKEN
        - name: DATAHUB_REST_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: datahub-credential
              key: DATAHUB_REST_ENDPOINT
      volumeMounts:
        - name: xxx-truststore-volume
          mountPath: /etc/xxx/ssl
          readOnly: true
        - name: xxx-tenant-profile-volume
          mountPath: /etc/xxx/profiles/default
          readOnly: true
        - name: k8s-sa-token
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          readOnly: true
      resources:
        requests:
          memory: "2Gi"
          cpu: "1"
        limits:
          memory: "20Gi"
          cpu: "2"
  volumes:
    - name: vault-auth
      projected:
        sources:
          - serviceAccountToken:
              path: vault-auth
              expirationSeconds: 7200
              audience: vault
    - name: xxx-truststore-volume
      secret:
        secretName: xxx-truststore-bundle
    - name: xxx-tenant-profile-volume
      configMap:
        name: xxx-tenant-profile
    - name: k8s-sa-token
      projected:
        defaultMode: 420
        sources:
          - serviceAccountToken:
              audience: "https://xxx.com"
              expirationSeconds: 13600
              path: token
          - configMap:
              items:
                - key: ca.crt
                  path: ca.crt
              name: kube-root-ca.crt
          - downwardAPI:
              items:
                - fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
                  path: namespace
