    
{{ config(
    alias='prvsn',
    materialized='table'
) }}

 -- 

 SELECT
  CONCAT(EBBS_PRVINFO.CURRENCYCODE, '-', TRIM(EBBS_PRVINFO.REFERENCENO)) AS PRVSN_ID,
  'Chargeoff' AS PRVSN_TYPE,
  EBBS_PRVINFO.country AS CTRY_CD,
  '9999-12-31' AS END_DT,
  EBBS_PRVINFO.ods AS STRT_DT,
  'EBBS' AS SRC_SYS,
  NULL AS LAST_EXCES_DT,
  NULL AS PRVSN_PRD_CD,
  NULL AS OD_CLAS,
  EBBS_ODCLASS.ODTYPE AS OD_TYPE,
  NULL AS DPD,
  EBBS_PRVINFO.FEEPRVCHRGOFFAMT AS FEE_AMT,
  EBBS_PRVINFO.INTCHARGEDOFFAMT AS INT_AMT,
  EBBS_PRVINFO.LASTDRINTPAYDATE AS LAST_DEBIT_INT_SRVC_DT,
  NULL AS ORIG_PRVSN_AMT,
  NULL AS PRVSN_LVL,
  EBBS_PRVINFO.PROVISIONSTATUS AS PRVSN_STS,
  NULL AS PRVSN_PCT,
  EBBS_PRVINFO.TOTALCHARGEOFFAMT AS TOT_PRVSN_AMT,
  EBBS_PRVINFO.CHARGEOFFDATE AS TXN_DT,
  EBBS_PRVINFO.PROVISIONAMOUNT AS PRVSN_AMT,
  EBBS_PRVINFO.IMPAIRMENTFLAG AS PRVSN_FLG,
  EBBS_PRVINFO.CURRENCYCODE AS ACCT_CCY,
  NULL AS RCVR_INT_PRVSN_NON_REVN_AMT,
  EBBS_PRVINFO.PROVCHRGOFFAMT AS RCVR_PRVSN_CHOFF_AMT,
  EBBS_PRVINFO.FEEPRVCHRGOFFAMT AS RCVR_FEE_PRVSN_CHOFF_AMT,
  NULL AS RCVR_INT_PRVSN_CHOFF_AMT,
  EBBS_PRVINFO.FEENONREVAMOUNT AS RCVR_FEE_PRVSN_NON_REVN_AMT,
  EBBS_PRVINFO.ACCUMCHRGOFFREC AS ACUM_CHOFF_RECV_AMT,
  NULL AS UN_IMPAR_DT,
  NULL AS UN_IMPAR_AMT,
  NULL AS PRVSN_ADJ_AMT,
  EBBS_PRVINFO.DISCPROVAMOUNT AS DISC_PRVSN_AMT,
  NULL AS INSRNC_PRVSN_AMT,
  EBBS_PRVINFO.excessfee AS LATE_CHRG_PRVSN_AMT,
  NULL AS IMPAR_FLG,
  NULL AS EY_ADJ_AMT,
  NULL AS IMPAR_AUTO_PRVSN_CD,
  NULL AS REAGEING_DT,
  NULL AS PRVSN_PRD_DESC,
  EBBS_PRVINFO.CHARGEOFF AS CHOFF_FLG,
  EBBS_PRVINFO.CHARGEOFFREASON AS CHOFF_RSN,
  EBBS_PRVINFO.ods AS ODS
FROM {{ source('sri_open_schema', 'ebbs_in_prvinfo') }} AS ebbs_prvinfo
LEFT OUTER JOIN {{ source('sri_open_schema', 'ebbs_in_odclass') }} AS EBBS_ODCLASS
  ON EBBS_ODCLASS.PRVPRDCURRENCY = EBBS_PRVINFO.CURRENCYCODE
  AND EBBS_ODCLASS.PROVPRDCODE = EBBS_PRVINFO.PRVPRDCD
  AND EBBS_ODCLASS.ODS = EBBS_PRVINFO.ODS
  AND EBBS_ODCLASS.ods = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN {{ source('sri_open_schema', 'ebbs_in_excrtl') }} AS EBBS_EXCRTL
  ON EBBS_EXCRTL.CURRENCYCODE = EBBS_PRVINFO.CURRENCYCODE
  AND EBBS_EXCRTL.ACCOUNTNO = EBBS_PRVINFO.REFERENCENO
  AND EBBS_EXCRTL.ODS = EBBS_PRVINFO.ODS
  AND EBBS_EXCRTL.ods = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN {{ source('sri_open_schema', 'ebbs_in_account') }} AS EBBS_ACCOUNT
  ON EBBS_PRVINFO.CURRENCYCODE = EBBS_ACCOUNT.CURRENCYCODE
  AND TRIM(EBBS_PRVINFO.REFERENCENO) = TRIM(EBBS_ACCOUNT.ACCOUNTNO)
  AND EBBS_PRVINFO.ODS = EBBS_ACCOUNT.ODS
  AND EBBS_ACCOUNT.STATUSFLAG <> 14
  AND EBBS_ACCOUNT.ods = '{{ var('__ods_val__') }}'
WHERE
  EBBS_PRVINFO.ODS = '{{ var('__ods_val__') }}'
 