    
{{ config(
    alias='prty_rtng1',
    materialized='incremental'
) }}

 -- 

 SELECT
  TRIM(CAST(EBBS_MAST.MASTERNO AS VARCHAR)) AS PRTY_ID,
  'EBBS' AS SRC_SYS,
  'IN' AS CTRY_CD,
  EBBS_MAST.ods AS STRT_DT,
  '9999-12-31' AS END_DT,
  CAST(NULL AS VARCHAR) AS PRTY_CR_RISK_RTNG_AGNCY_TYPE,
  CAST(NULL AS VARCHAR) AS PRTY_CR_RISK_RTNG_CCY,
  'flag' AS PRTY_CR_RISK_RTNG_CD,
  'INTERNAL' AS PRTY_CR_RISK_RTNG_TYPE,
  'TPCustomerCreditGrade' AS RTNG_CAT_CD,
  CAST(NULL AS VARCHAR) AS PRTY_CR_RISK_RTNG_CD_DESC,
  CAST(NULL AS VARCHAR) AS PRTY_CR_RISK_RTNG_STRT_DT,
  EBBS_MAST.ods AS ODS
FROM sri_open_schema.ebbs_in_mastrell AS ebbs_mast
WHERE
  EBBS_MAST.ODS = '{{ var('__ods_val__') }}'

