    
{{ config(
    alias='acct_bal',
    materialized='incremental',
    incremental_strategy='merge',
  
) }}


 SELECT
  CONCAT(EBBS_ACCOUNT.CURRENCYCODE, '-', TRIM(EBBS_ACCOUNT.ACCOUNTNO)) AS ACCT_ID,
  'EBBS' AS SRC_SYS,
  'IN' AS CTRY_CD,
  CAST(EBBS_ACCOUNT.ods AS DATE) AS STRT_DT,
  CAST('9999-12-31'  AS DATE) AS END_DT,
  EBBS_ACCOUNT.CURRENCYCODE AS ACCT_CCY,
  CASE WHEN EBBS_BEBAL.LEDGERBALANCE < '0' THEN EBBS_BEBAL.LEDGERBALANCE ELSE '0' END AS ASSET_BAL_OS_AMT,
  CASE WHEN EBBS_PRD.CONTINGENTFLAG = 'Y' THEN EBBS_BEBAL.LEDGERBALANCE ELSE '0' END AS CONT_OS_BAL_AMT,
  CAST(NULL AS VARCHAR) AS FEE_RECD_ADV_AMT,
  CAST(NULL AS VARCHAR) AS FEE_RECD_AMT,
  CASE WHEN EBBS_ACCTPRV.ISCRDRFLAG = 'C' THEN EBBS_ACCTPRV.PROVISIONAMOUNT ELSE '0' END AS INT_PYBL_AMT_TD,
  CASE WHEN EBBS_ACCTPRV.ISCRDRFLAG = 'D' THEN EBBS_ACCTPRV.PROVISIONAMOUNT ELSE '0' END AS INT_RCVBL_AMT_TD,
  CAST(NULL AS VARCHAR) AS INT_RECD_ADV_AMT,
  CASE WHEN EBBS_BEBAL.LEDGERBALANCE >= '0' THEN EBBS_BEBAL.LEDGERBALANCE ELSE '0' END AS LIAB_BAL_OS_AMT,
  CASE
    WHEN EBBS_CBALSTAT.MAVGLEDGERBAL < '0'
    THEN EBBS_CBALSTAT.MAVGLEDGERBAL
    ELSE '0'
  END AS MTH_AVG_ASSET_BAL_AMT,
  CASE WHEN EBBS_PRD.CONTINGENTFLAG = 'Y' THEN EBBS_CBALSTAT.MAVGLEDGERBAL ELSE '0' END AS MTH_AVG_CONT_BAL_AMT,
  CASE
    WHEN EBBS_CBALSTAT.MAVGLEDGERBAL >= '0'
    THEN EBBS_CBALSTAT.MAVGLEDGERBAL
    ELSE '0'
  END AS MTH_AVG_LIAB_BAL_AMT,
  CAST(NULL AS VARCHAR) AS PAST_DUE_OS_BAL_AMT,
  EBBS_PRVINFO.IISAMOUNT AS PAST_DUE_OS_INT_AMT,
  CASE
    WHEN EBBS_CBALSTAT.YAVGLEDGERBAL < '0'
    THEN EBBS_CBALSTAT.YAVGLEDGERBAL
    ELSE '0'
  END AS YR_AVG_ASSET_BAL_AMT,
  CASE WHEN EBBS_PRD.CONTINGENTFLAG = 'Y' THEN EBBS_CBALSTAT.YAVGLEDGERBAL ELSE '0' END AS YR_AVG_CONT_OS_BAL_AMT,
  CASE
    WHEN EBBS_CBALSTAT.YAVGLEDGERBAL >= '0'
    THEN EBBS_CBALSTAT.YAVGLEDGERBAL
    ELSE '0'
  END AS YR_AVG_LIAB_BAL_AMT,
  CAST(NULL AS VARCHAR) AS FEE_ACR_AMT,
  CAST(NULL AS VARCHAR) AS MTD_FEE_REPMT_AMT,
  CAST(NULL AS VARCHAR) AS MTD_INT_REPMT_AMT,
  CAST(NULL AS VARCHAR) AS OTH_PYBL_AMT_TD,
  CAST(NULL AS VARCHAR) AS OTH_RCVBL_AMT_TD,
  EBBS_BEBAL.FORWARDCREDIT AS FRWD_CR_BAL_AMT,
  EBBS_BEBAL.FORWARDDEBIT AS FRWD_DR_BAL_AMT,
  EBBS_BEBAL.EARMARKCRBALANCE AS EARMARK_CR_BAL_AMT,
  EBBS_BEBAL.EARMARKDRBALANCE AS EARMARK_DR_BAL_AMT,
  '' As card_mtd_bal_amt,
  '' AS stm_due_amt,
  '' AS rtl_bal_beg_of_cur_cyc,
  '' AS cash_bal_beg_of_cur_cyc,
  '' AS cash_bal_amt,
  '' AS rtl_bal_amt,
  '' AS risk_partp_pct,
  '' AS acct_corp_flg,
  '' AS acct_sme_flg,
  '' AS recrse_flg,
  '' AS expsr_type ,
  '' AS insur_le_id,
  '' AS maturity_dt,
  '' AS fst_ln_drwdown_dt,
  '' AS ln_eff_dt,
  '' AS obligor_pd,
  '' AS rec_prcs_dt,
  '' AS rec_rlovr_flg,
  EBBS_ACCOUNT.ods AS ODS,
 
    {{ add_partition_columns_with_defaults() }}
FROM {{ source('sri_open_schema', 'ebbs_in_account') }} AS ebbs_account
LEFT OUTER JOIN {{ source('sri_open_schema', 'ebbs_in_bebal') }} AS EBBS_BEBAL
  ON EBBS_BEBAL.CURRENCYCODE = EBBS_ACCOUNT.CURRENCYCODE
  AND TRIM(EBBS_BEBAL.ACCOUNTNO) = TRIM(EBBS_ACCOUNT.ACCOUNTNO)
  AND EBBS_BEBAL.ODS = EBBS_ACCOUNT.ODS
  AND EBBS_BEBAL.ODS = EBBS_BEBAL.DATE1
  AND EBBS_BEBAL.ods = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN {{ source('sri_open_schema', 'ebbs_in_prd') }} AS EBBS_PRD
  ON EBBS_ACCOUNT.PRODUCTCODE = EBBS_PRD.PRODUCTCODE
  AND EBBS_ACCOUNT.ODS = EBBS_PRD.ODS
  AND EBBS_PRD.ods = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN {{ source('sri_open_schema', 'ebbs_in_acctprv') }} AS EBBS_ACCTPRV
  ON EBBS_ACCTPRV.CURRENCYCODE = EBBS_ACCOUNT.CURRENCYCODE
  AND TRIM(EBBS_ACCTPRV.ACCOUNTNO) = TRIM(EBBS_ACCOUNT.ACCOUNTNO)
  AND EBBS_ACCTPRV.PROVISIONDATE = EBBS_ACCOUNT.ODS
  AND EBBS_ACCTPRV.ods = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN {{ source('sri_open_schema', 'ebbs_in_cbalstat') }} AS EBBS_CBALSTAT
  ON EBBS_CBALSTAT.CURRENCYCODE = EBBS_ACCOUNT.CURRENCYCODE
  AND TRIM(EBBS_CBALSTAT.ACCOUNTNO) = TRIM(EBBS_ACCOUNT.ACCOUNTNO)
  AND EBBS_ACCOUNT.ODS = EBBS_CBALSTAT.ODS
  AND EBBS_CBALSTAT.ods = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN {{ source('sri_open_schema', 'ebbs_in_mast') }} AS EBBS_MAST
  ON EBBS_ACCOUNT.MASTERNO = EBBS_MAST.MASTERNO
  AND EBBS_ACCOUNT.ODS = EBBS_MAST.ODS
  AND EBBS_MAST.ods = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN {{ source('sri_open_schema', 'ebbs_in_prvinfo') }} AS EBBS_PRVINFO
  ON EBBS_PRVINFO.CURRENCYCODE = EBBS_ACCOUNT.CURRENCYCODE
  AND TRIM(EBBS_PRVINFO.REFERENCENO) = TRIM(EBBS_ACCOUNT.ACCOUNTNO)
  AND EBBS_PRVINFO.ODS = EBBS_ACCOUNT.ODS
  AND EBBS_PRVINFO.ods = '{{ var('__ods_val__') }}'
WHERE
  EBBS_ACCOUNT.ODS = '{{ var('__ods_val__') }}'
  AND (
    EBBS_ACCOUNT.STATUSFLAG <> '14'
    --OR EBBS_ACCOUNT.ACCLOSEDT > LAST_DAY(CAST(EBBS_ACCOUNT.ODS AS DATE) - INTERVAL '14' MONTH)
    OR CAST(EBBS_ACCOUNT.ACCLOSEDT AS DATE) > date_add('day', -1, date_add('month', 1, date_trunc('month', CAST(EBBS_ACCOUNT.ODS AS DATE))))
  )

/* 
 {% if is_incremental() %}
  AND EBBS_ACCOUNT.ODS > (SELECT MAX(ODS) FROM {{ this }})
{% endif %}
*/