    
{{ config(
    alias='acct_ebbs',
    materialized='incremental'
) }}

 -- s

 SELECT
  CONCAT(EBBS_PMMKDEAL.DEALCURRCD, '-', TRIM(EBBS_PMMKDEAL.DEALNO)) AS ACCT_ID,
  EBBS_PMMKDEAL.DEALCURRCD AS ACCT_CCY,
  CONCAT(EBBS_PMMKDEAL.DEALCURRCD, TRIM(EBBS_PMMKDEAL.DEALNO)) AS ACCT_REF_ID,
  EBBS_PMMKDEAL.COUNTRY AS CTRY_CD,
  '9999-12-31' AS END_DT,
  EBBS_PMMKDEAL.ODS AS STRT_DT,
  'EBBS' AS SRC_SYS,
  'Deal' AS ACCT_CAT_CD,
  CASE WHEN EBBS_PMMKDEAL.STATUSFLAG = 14 THEN EBBS_PMMKDEAL.CHECKERDATE ELSE NULL END AS ACCT_CLSE_DT,
  NULL AS ACCT_CLSR_RSN,
  CASE WHEN EBBS_DEALPRV.INTERESTTYPEFLAG = 'C' THEN 'Y' ELSE '' END AS ACCT_CR_INT_ACR_FLG,
  CASE WHEN EBBS_DEALPRV.INTERESTTYPEFLAG = 'D' THEN 'Y' ELSE '' END AS ACCT_DR_INT_ACRL_FLG,
  NULL AS ACCT_DRMT_DT,
  EBBS_PMMKDEAL.FROZENCODE AS ACCT_FRZN_CD,
  NULL AS ACCT_IN_COL_FLG,
  EBBS_MDELTYP.RATETYPE AS ACCT_INT_TYPE_CD,
  EBBS_PMMKDEAL.INTCURRCD AS ACCT_INT_ACC_CCY,
  NULL AS ACCT_LAST_CR_TRAN_AMT,
  NULL AS ACCT_LAST_DR_TRAN_AMT,
  NULL AS ACCT_LAST_EXCES_TRAN_AMT,
  EBBS_PMMKDEAL.DEALDT AS ACCT_OPEN_DT,
  EBBS_PMMKDEAL.DEALBRANCHCODE AS ACCT_OPEN_BR_CD,
  NULL AS ACCT_POOL_FLG,
  NULL AS ACCT_POOL_ID,
  NULL AS ACCT_PREV_CR_TRAN_DT,
  NULL AS ACCT_PREV_DR_TRAN_DT,
  NULL AS ACCT_REACTIVATED_DT,
  EBBS_PMMKDEAL.DEALSHORTNAME AS ACCT_SHORT_NM,
  NULL AS ACCT_STMT_ADD_TITL,
  EBBS_PMMKDEAL.DEALCURRENTSTATUS AS ACCT_STS_CD,
  CASE
    WHEN EBBS_PMMKDEAL.DEALCURRENTSTATUS = 'U'
    THEN EBBS_PMMKDEAL.CHECKERDATE
    ELSE NULL
  END AS ACCT_UNCLAIM_DT,
  EBBS_PMMKDEAL.ADJINTAMT AS ACR_INT_ADJ_AMT,
  NULL AS AMORT_FLG,
  NULL AS AMORT_TYPE,
  NULL AS ANCHOR_ID,
  NULL AS ANCHOR_NM,
  EBBS_PMMKDEAL.CHECKERDATE AS AUTH_DT,
  EBBS_INTCURR.TENOR AS BASE_TENR,
  EBBS_PMMKDEAL.BENEFCUSTNAME AS BNF_CUST_NM,
  G.COMP_CD AS BK_CD,
  EBBS_PMMKDEAL.COUNTRY AS BKG_CTRY_CD,
  scbentityxlate.sci_entity_code AS BKG_LOC_CD,
  NULL AS CAP_RELIEF,
  TRIM(CAST(EBBS_PMMKDEAL.CUSTTCID AS STRING)) AS CP_ID,
  EBBS_INTCURR.CRINTCHARGEBASIS AS CR_INT_ACR_BSIS_CD,
  NULL AS CR_INT_ADJ_ACR_AMT,
  CASE
    WHEN EBBS_MDELTYP.DEPOSITORLOAN = 'D'
    THEN EBBS_PMMKDEAL.ACCRUEDINTERESTAMT
    ELSE NULL
  END AS CR_INT_LAST_ACR_AMT,
  CASE
    WHEN EBBS_MDELTYP.DEPOSITORLOAN = 'L'
    THEN EBBS_PMMKDEAL.LASTINTPAIDDATE
    ELSE NULL
  END AS CR_INT_LAST_PYMT_DT,
  NULL AS CR_INT_NXT_PYMT_DT,
  NULL AS CR_INT_PYMT_FREQ,
  CASE
    WHEN EBBS_MDELTYP.DEPOSITORLOAN = 'D'
    THEN EBBS_PMMKDEAL.INTERESTCODE
    ELSE ''
  END AS CR_INT_PRD_CD,
  NULL AS CR_PROT_OS_FIN_AMT,
  EBBS_PMMKDEAL.CROSSCURRDEALFLAG AS CROSS_CCY_DEAL_FLG,
  NULL AS CURR_INT_COL_OPT,
  NULL AS CURR_INT_PYMT_FRQ,
  NULL AS CURV_FLG,
  EBBS_PMMKDEAL.INTINSUSPENSE AS CUST_ACCT_INT_IN_SUSP_FLG,
  NULL AS CUST_DEP_TYPE_CD,
  EBBS_PMMKDEAL.VALUEDT AS CUST_DEP_VAL_DT,
  EBBS_PMMKDEAL.BASERATE AS CUST_INT_BASE_RT,
  EBBS_PMMKDEAL.CUSTOMERMARGIN AS CUST_MRGN_RT,
  EBBS_PMMKDEAL.MARGINFLAG AS CUST_MRGN_RT_FLG,
  EBBS_PMMKDEAL.NEXTMATURITYDATE AS NXT_MATURITY_DT,
  CONCAT('EBBS', '-', EBBS_PMMKDEAL.COUNTRY) AS DATA_SRC,
  NULL AS DAY_CNT_CONV_CD,
  NULL AS DAYS_PAST_DUE,
  EBBS_PMMKDEAL.DSRCLOSINGID AS DEAL_CLSE_DSR_ID,
  EBBS_PMMKDEAL.LIENAMOUNT AS DEAL_LIEN_AMT,
  NULL AS DEAL_MATCH_FLG,
  NULL AS DEAL_REPR_STRT_DT,
  EBBS_PMMKDEAL.ROLLOVERCOUNT AS DEAL_ROLL_OVER_CNT,
  EBBS_PMMKDEAL.DSRREFERRALID AS DEAL_SRC_DSR_ID,
  EBBS_PMMKDEAL.TERMVAL AS DEAL_TERM_AMT,
  EBBS_PMMKDEAL.TERMTYPE AS DEAL_TERM_TYPE,
  EBBS_PMMKDEAL.TRSYRATE AS DEAL_TRSRY_RT,
  EBBS_INTCURR.DRINTCHARGEBASIS AS DR_INT_ACR_BSIS_CD,
  EBBS_INTCURR.DRBANDPROGREG AS DR_INT_BAND_METH,
  CASE
    WHEN EBBS_MDELTYP.DEPOSITORLOAN = 'L'
    THEN EBBS_PMMKDEAL.ACCRUEDINTERESTAMT
    ELSE NULL
  END AS DR_INT_LAST_ACR_AMT,
  CASE
    WHEN EBBS_MDELTYP.DEPOSITORLOAN = 'D'
    THEN EBBS_PMMKDEAL.LASTINTPAIDDATE
    ELSE NULL
  END AS DR_INT_LAST_PYMT_DT,
  NULL AS DR_INT_NXT_PYMT_DT,
  NULL AS DR_INT_PYMT_FREQ,
  NULL AS DR_INT_ADJ_ACR_AMT,
  CASE
    WHEN EBBS_MDELTYP.DEPOSITORLOAN = 'L'
    THEN EBBS_PMMKDEAL.INTERESTCODE
    ELSE ''
  END AS DR_INT_PRD_CD,
  NULL AS DISAPPROVED_PERIOD,
  CASE
    WHEN EBBS_DLINFO.INFORMATIONCODE = 'FOL'
    THEN EBBS_DLINFO.INFODETCODE
    ELSE ''
  END AS FAC_ORIG_LOC,
  'Deal' AS FILE_TYPE,
  EBBS_PMMKDEAL.DEALDT AS FST_LN_DRWDOWN_DT,
  NULL AS FIX_PERIOD,
  NULL AS FRT_ON_LAND_CD,
  EBBS_PMMKDEAL.BASERATE AS FTP_BASE_RT,
  NULL AS FTP_BE_LIQ_PRIM_RT,
  NULL AS FTP_CONTR_LIQ_PRIM_RT,
  NULL AS FTP_COST_OF_LIQ_RT,
  NULL AS FTP_CTRY_COST_OF_LIQ_RT,
  NULL AS FTP_INCT_PRIM_RT,
  NULL AS FTP_LIQ_PRIM_RT_DT,
  NULL AS FTP_LIQ_PRIM_TENR,
  NULL AS FTP_RT_DT,
  NULL AS FUND_PL_MATURITY_DT,
  NULL AS FTP_RT,
  EBBS_PMMKDEAL.ACCRUEDUPTODT AS INT_ACR_UP_TO_DT,
  EBBS_PMMKDEAL.ACCRUEDINTERESTAMT AS INT_ACR_AMT,
  NULL AS INT_BAND_BRKP,
  NULL AS INT_BASE_RT_MULT,
  EBBS_MDELTYP.RATETYPE AS INT_BASE_RT_TYPE,
  NULL AS INT_CALC_DAY_CONV,
  NULL AS INT_ONLY_FLG,
  NULL AS INT_PYMT_DAY_CONV,
  EBBS_PMMKDEAL.INTPAYDUEDT AS INT_PYMT_DUE_DT,
  EBBS_PMMKDEAL.DEALRATE AS INT_RT,
  EBBS_INTCURR.EFFECTIVEDATE AS INT_RT_EFF_DT,
  EBBS_MDELTYP.RATETYPE AS INT_RT_TYPE,
  NULL AS INT_REPYMT_FREQ,
  EBBS_PMMKDEAL.INTERESTSTARTDT AS INT_PYMT_STRT_DT,
  EBBS_MDELTYP.ISISLAMIC AS ISLM_ACCT_FLG,
  NULL AS ISLM_SUB_PRD,
  NULL AS LAST_CR_INT_RT,
  NULL AS LAST_CUST_INIT_CR_TRAN_DT,
  NULL AS LAST_CUST_INIT_DR_TRAN_DT,
  NULL AS LAST_DR_INT_RT,
  NULL AS LAST_EXCES_AMT,
  NULL AS LAST_EXCES_DT,
  NULL AS LAST_INT_PYMT_DT,
  NULL AS LAST_INT_REPR_DT,
  scbentityxlate.sci_entity_code AS LGL_ENT_CD,
  scbentityxlate.sci_bkg_loctn_id AS LGL_ENT_ID,
  NULL AS LIBR_DIBR_FLG,
  EBBS_PMMKDEAL.DEALCURRENTSTATUS AS LIFCYCL_STS_CD,
  EBBS_MDELTYP.ACCLASSCODE AS LN_CLAS,
  EBBS_PMMKDEAL.VALUEDT AS LN_EFF_DT,
  NULL AS LN_TENR_IN_DAYS,
  EBBS_MDELTYP.PRODUCTCODE AS LOCAL_PRD_CD,
  NULL AS LOCAL_PRD_CD_CHG_DT,
  EBBS_PMMKDEAL.MATURITYDT AS MATURITY_DT,
  EBBS_PMMKDEAL.MATURITYINT AS MATURITY_INT_AMT,
  NULL AS MAX_TENR,
  EBBS_PMMKDEAL.INTPAYDUEDT AS NXT_INT_PYMT_DT,
  EBBS_PMMKDEAL.NEXTREPRICINGDT AS NXT_INT_REPR_DT,
  EBBS_PMMKDEAL.PRNPAYDUEDT AS NXT_PYMT_DT,
  NULL AS NOST_SUSP_FLG,
  NULL AS OBL_FLG,
  EBBS_PMMKDEAL.MATURITYDT AS ORIG_MATURTY_DT,
  EBBS_PMMKDEAL.ORGTERMTYPE AS ORIG_TERM_TYPE,
  EBBS_PMMKDEAL.ORIGINALDEALAMT AS ORIG_PRIN_AMT,
  NULL AS OVR_DFT_TYPE,
  NULL AS PAST_DUE_FLG,
  NULL AS PAST_DUE_INT_COL_OPT,
  NULL AS PAST_DUE_INT_PYMT_FREQ,
  EBBS_PMMKDEAL.PENALTYAMT AS PNLTY_AMT,
  NULL AS PNLTY_CHRG_FLG,
  NULL AS PRE_PYMT_RT,
  NULL AS PREV_LOCAL_PRD_CD,
  EBBS_PMMKDEAL.PRNPAYFREQ AS PRIN_PYMT_FREQ,
  NULL AS PRG_CD,
  NULL AS PRVSN_PRD_CD,
  NULL AS PRPS_CD,
  EBBS_PMMKDEAL.CHGINTRATEDT AS REPR_DT,
  NULL AS RECRSE_FLG,
  NULL AS REG_INT_COL_OPT,
  NULL AS RISK_PRTY_ID,
  EBBS_PMMKDEAL.ROLLOVERFLAG AS ROLL_OVER_FLG,
  EBBS_PMMKDEAL.CAPITALISEFLAG AS ROLL_OVER_INT_CAP_FLG,
  EBBS_PMMKDEAL.ORGRATEOPTION AS RLOVR_ORIG_INT_RT_FLG,
  NULL AS SCTY_TYPE_CD,
  NULL AS SEL_DOWN_FLG,
  EBBS_PMMKDEAL.CHECKERDATE AS SETLM_DT,
  TRIM(CAST(EBBS_MASTREL.RELATIONSHIPNO AS STRING)) AS SRC_CUST_ID,
  m_product_xlate.basel_prod_code AS STD_PRD_CD,
  NULL AS STRUC_NM,
  NULL AS STRUC_TRD_FLG,
  NULL AS STRUC_TRD_SUB_TYPE,
  NULL AS STRUC_TRD_TYPE,
  NULL AS SUST_TRD_FIN_FLG,
  NULL AS TOT_CHRG_OFF_AMT,
  NULL AS TP_ENT_NM,
  NULL AS ULT_RISK_CTRY,
  EBBS_PMMKDEAL.UNCLMDT AS UNCLAIM_DT,
  NULL AS UWRT_TYPE,
  NULL AS VOST_FLG,
  NULL AS WAIVE_EXCES_INT_FLG,
  NULL AS INT_RT_BSIS_CD,
  NULL AS NON_CR_PROT_OS_FIN_AMT,
  EBBS_PMMKDEAL.INTPAYFREQ AS INT_PYMT_FREQ,
  NULL AS TRD_FIN_TYPE,
  NULL AS TRUE_SALES_FLG,
  EBBS_BRN.NAME AS ACCT_BR_NM,
  NULL AS ACTG_METH_CD,
  NULL AS FST_INT_PYMT_DT,
  NULL AS FST_PRIN_PYMT_DT,
  NULL AS INT_PAST_DUE_DT,
  EBBS_PMMKDEAL.DEALCURRCD AS LOCAL_CCY,
  NULL AS LOCAL_CCY_FX_RT,
  NULL AS PRIN_PAST_DUE_DT,
  NULL AS PTFOL_ID,
  NULL AS PTFOL_NM,
  NULL AS RESV_RT,
  NULL AS RMNG_TENR,
  NULL AS LPC_GRP_CD,
  NULL AS LPC_TYPE,
  NULL AS OS_INVC_DT,
  NULL AS TP_BIZ_GRP_CD,
  NULL AS TP_BIZ_SGMT_CD,
  NULL AS TP_BIZ_SUB_SGMT_CD,
  NULL AS TP_BIZ_UNIT_CD,
  NULL AS ACCT_STS_DESC,
  NULL AS FAC_ORIG_LOC_DESC,
  NULL AS INT_PYMT_FREQ_DESC,
  NULL AS INT_RT_TYPE_DESC,
  NULL AS LN_CLAS_DESC,
  EBBS_PRD.DESCRIPTION AS LOCAL_PRD_DESC,
  NULL AS PRIN_PYMT_FREQ_DESC,
  NULL AS PRPS_DESC,
  NULL AS LPC_GRP_DESC,
  NULL AS LPC_TYPE_DESC,
  NULL AS REPRC_FREQ,
  NULL AS REPRC_FREQ_DESC,
  NULL AS STRUC_TYPE,
  NULL AS STRUC_TYPE_DESC,
  EBBS_MDELTYP.ROLLOVERWAITPR AS RLOVR_WAIT_PERIOD,
  EBBS_TRNCHSB.trnchid AS TRNCH_ID,
  NULL AS CARD_BLK_CD,
  NULL AS CASH_ADVN_INT_RT,
  NULL AS CR_CARD_TYPE_CD,
  NULL AS AVAIL_CR_AMT,
  NULL AS CR_CARD_USR_CD,
  NULL AS ACCT_STM_CYC_DAY,
  EBBS_PMMKDEAL.MMKDEALTYPE AS LCL_DEAL_TYPE,
  EBBS_PMMKDEAL.LIENNO AS DEAL_LIEN_NO,
  EBBS_PMMKDEAL.SYSADJINTAMT AS SYS_ADJ_INT_AMT,
  EBBS_PRD.splprdflag AS SPL_PRD_FLG,
  CASE
    WHEN EBBS_DLINTHIS_D.DEPOSITORLOAN = 'L'
    THEN EBBS_DLINTHIS_D.TOTAL_INT_PD
    ELSE ''
  END AS DR_INT_LAST_PYMT_AMT,
  CASE
    WHEN EBBS_DLINTHIS_C.DEPOSITORLOAN = 'D'
    THEN EBBS_DLINTHIS_C.TOTAL_INT_PD
    ELSE ''
  END AS CR_INT_LAST_PYMT_AMT,
  EBBS_PMMKDEAL.REFERENCE AS DEAL_REF_DTL_1,
  EBBS_PMMKDEAL.REFERENCE2 AS DEAL_REF_DTL_2,
  EBBS_PMMKDEAL.REFERENCE3 AS DEAL_REF_DTL_3,
  CASE WHEN EBBS_DLINTSH.INTERESTAMT < 0 THEN EBBS_DLINTSH.INTERESTAMT ELSE '' END AS DR_INT_NXT_PYMT_AMT,
  CASE WHEN EBBS_DLINTSH.INTERESTAMT > 0 THEN EBBS_DLINTSH.INTERESTAMT ELSE '' END AS CR_INT_NXT_PYMT_AMT,
  PRTY_SP_SCI.PRTY_ID AS PRTY_ID,
  CASE
    WHEN EBBS_PMMKDEAL.DEALCURRENTSTATUS = 'O'
    THEN EBBS_PMMKDEAL.DEALDT
    WHEN EBBS_PMMKDEAL.DEALCURRENTSTATUS IN ('U', 'C') AND EBBS_PMMKDEAL.STATUSFLAG = 14
    THEN EBBS_PMMKDEAL.CHECKERDATE
    ELSE NULL
  END AS LIFCYCL_STS_DT,
  EBBS_PMMKDEAL.ODS AS ODS
FROM {{ source('sri_open_schema', 'ebbs_in_pmmkdeal') }} AS ebbs_pmmkdeal
LEFT OUTER JOIN {{ source('sri_open_schema', 'ebbs_in_dealprv') }} AS EBBS_DEALPRV
  ON EBBS_DEALPRV.CURRENCYCODE = EBBS_PMMKDEAL.DEALCURRCD
  AND EBBS_DEALPRV.DEALNO = EBBS_PMMKDEAL.DEALNO
  AND EBBS_DEALPRV.provisiondate = EBBS_PMMKDEAL.ODS
  AND EBBS_DEALPRV.ods = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN {{ source('sri_open_schema', 'ebbs_in_mdeltyp') }} AS EBBS_MDELTYP
  ON EBBS_MDELTYP.MMKDEALTYPE = EBBS_PMMKDEAL.MMKDEALTYPE
  AND EBBS_MDELTYP.ODS = EBBS_PMMKDEAL.ODS
  AND EBBS_MDELTYP.ods = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN (
  SELECT
    a.CRINTCHARGEBASIS,
    a.CRINTPAYFREQ,
    a.DRINTCHARGEBASIS,
    a.DRBANDPROGREG,
    a.interestcode,
    a.CURRENCYCODE,
    a.EFFECTIVEDATE,
    a.TENOR,
    a.ODS
  FROM (
    SELECT
      CRINTCHARGEBASIS,
      CRINTPAYFREQ,
      DRINTCHARGEBASIS,
      DRBANDPROGREG,
      interestcode,
      CURRENCYCODE,
      EFFECTIVEDATE,
      TENOR,
      ODS
    FROM {{ source('sri_open_schema', 'ebbs_in_intcurr') }} AS ebbs_intcurr
  ) AS a
  JOIN (
    SELECT
      MAX(EFFECTIVEDATE) AS EFFECTIVEDATE,
      interestcode,
      CURRENCYCODE
    FROM {{ source('sri_open_schema', 'ebbs_in_intcurr') }} AS ebbs_intcurr
    WHERE
      ODS = '{{ var('__ods_val__') }}'
    GROUP BY
      interestcode,
      CURRENCYCODE
  ) AS b
    ON a.EFFECTIVEDATE = b.EFFECTIVEDATE
    AND a.interestcode = b.interestcode
    AND a.CURRENCYCODE = b.CURRENCYCODE
) AS EBBS_INTCURR
  ON EBBS_INTCURR.CURRENCYCODE = EBBS_PMMKDEAL.DEALCURRCD
  AND EBBS_INTCURR.INTERESTCODE = EBBS_PMMKDEAL.INTERESTCODE
  AND EBBS_INTCURR.ODS = EBBS_PMMKDEAL.ODS
  AND EBBS_INTCURR.ods = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN (
  SELECT
    a.DEALNO,
    a.SEQNO,
    a.INFODETCODE,
    a.informationcode,
    a.ODS
  FROM (
    SELECT
      DEALNO,
      SEQNO,
      INFODETCODE,
      informationcode,
      ODS
    FROM {{ source('sri_open_schema', 'ebbs_in_dlinfo') }} AS ebbs_dlinfo
    WHERE
      ODS = '{{ var('__ods_val__') }}'
  ) AS a
  JOIN (
    SELECT
      MAX(SEQNO) AS SEQNO,
      INFORMATIONCODE,
      DEALNO
    FROM {{ source('sri_open_schema', 'ebbs_in_dlinfo') }} AS ebbs_dlinfo
    WHERE
      INFORMATIONCODE IN ('FOL') AND ODS = '{{ var('__ods_val__') }}'
    GROUP BY
      INFORMATIONCODE,
      DEALNO
  ) AS b
    ON a.SEQNO = b.SEQNO
    AND a.INFORMATIONCODE = b.INFORMATIONCODE
    AND a.DEALNO = b.DEALNO
) AS EBBS_DLINFO
  ON EBBS_DLINFO.DEALNO = EBBS_PMMKDEAL.DEALNO
  AND EBBS_DLINFO.ODS = EBBS_PMMKDEAL.ODS
  AND EBBS_DLINFO.ods = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN {{ source('sri_open_schema', 'ebbs_in_brn') }} AS EBBS_BRN
  ON EBBS_BRN.BRANCHCODE = EBBS_PMMKDEAL.DEALBRANCHCODE
  AND EBBS_BRN.ODS = EBBS_PMMKDEAL.ODS
  AND EBBS_BRN.ods = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN (
  SELECT
    ODS,
    COUNTRY_CODE,
    SRC_PROD_CODE,
    BASEL_PROD_CODE,
    lcl_prod_desc,
    src_sys_short_name,
    ROW_NUMBER() OVER (PARTITION BY COUNTRY_CODE, SRC_PROD_CODE ORDER BY SRC_PROD_CODE) AS ROW_NUM
  FROM {{ source('sri_open_schema', 'm_product_xlate') }} AS m_product_xlate
  WHERE
    ods = '{{ var('__ods_val__') }}'
) AS m_product_xlate
  ON EBBS_MDELTYP.PRODUCTCODE = m_product_xlate.src_prod_code
  AND m_product_xlate.src_sys_short_name = 'EBBS'
  AND m_product_xlate.country_code = EBBS_MDELTYP.COUNTRY
  AND m_product_xlate.ODS = EBBS_MDELTYP.ODS
  AND m_product_xlate.ROW_NUM = 1
LEFT OUTER JOIN (
  SELECT
    COUNTRY,
    ODS,
    masterno,
    Relationshipno,
    primaryflag,
    ROW_NUMBER() OVER (PARTITION BY masterno ORDER BY Relationshipno ASC, s_startdt DESC) AS ROW_NUM
  FROM {{ source('sri_open_schema', 'ebbs_in_mastrell') }} AS ebbs_mastrel
  WHERE
    ods = '{{ var('__ods_val__') }}' AND PRIMARYFLAG = 'Y'
) AS EBBS_MASTREL
  ON TRIM(EBBS_MASTREL.MASTERNO) = TRIM(EBBS_PMMKDEAL.CUSTTCID)
  AND EBBS_MASTREL.ODS = EBBS_PMMKDEAL.ODS
  AND EBBS_MASTREL.PRIMARYFLAG = 'Y'
  AND EBBS_MASTREL.ods = '{{ var('__ods_val__') }}'
  AND EBBS_MASTREL.ROW_NUM = 1
LEFT OUTER JOIN (
  SELECT
    ODS,
    country,
    dealno,
    trnchid,
    ROW_NUMBER() OVER (PARTITION BY ODS, country, dealno ORDER BY dealno) AS ROW_NUM
  FROM {{ source('sri_open_schema', 'ebbs_in_trnchsb') }} AS ebbs_trnchsb
  WHERE
    ods = '{{ var('__ods_val__') }}'
) AS EBBS_TRNCHSB
  ON TRIM(EBBS_PMMKDEAL.DEALNO) = TRIM(EBBS_TRNCHSB.DEALNO)
  AND EBBS_PMMKDEAL.country = EBBS_TRNCHSB.COUNTRY
  AND EBBS_TRNCHSB.ODS = EBBS_PMMKDEAL.ODS
  AND EBBS_TRNCHSB.ROW_NUM = 1
LEFT OUTER JOIN {{ source('sri_open_schema', 'ebbs_in_prd') }} AS EBBS_PRD
  ON EBBS_MDELTYP.PRODUCTCODE = EBBS_PRD.PRODUCTCODE
  AND EBBS_MDELTYP.ods = EBBS_PRD.ods
  AND EBBS_PRD.ods = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN (
  SELECT
    a.DEALCURRCD,
    a.DEALNO,
    SUM(a.INTAMTPAID) AS TOTAL_INT_PD,
    a.DEPOSITORLOAN,
    a.INTPAIDDATE,
    a.ODS
  FROM (
    SELECT
      DEALCURRCD,
      DEALNO,
      INTAMTPAID,
      DEPOSITORLOAN,
      INTPAIDDATE,
      ODS
    FROM {{ source('sri_open_schema', 'ebbs_in_dlinthis') }} AS ebbs_dlinthis
    WHERE
      ODS = '{{ var('__ods_val__') }}'
  ) AS a
  JOIN (
    SELECT
      MAX(INTPAIDDATE) AS INTPAIDDATE,
      DEALCURRCD,
      DEALNO,
      DEPOSITORLOAN
    FROM {{ source('sri_open_schema', 'ebbs_in_dlinthis') }} AS ebbs_dlinthis
    WHERE
      ODS = '{{ var('__ods_val__') }}'
    GROUP BY
      DEALCURRCD,
      DEALNO,
      DEPOSITORLOAN
  ) AS b
    ON a.INTPAIDDATE = b.INTPAIDDATE
    AND a.DEPOSITORLOAN = b.DEPOSITORLOAN
    AND a.DEALCURRCD = b.DEALCURRCD
    AND TRIM(a.DEALNO) = TRIM(b.DEALNO)
  GROUP BY
    a.DEALCURRCD,
    a.DEALNO,
    a.DEPOSITORLOAN,
    a.INTPAIDDATE,
    a.ODS
) AS EBBS_DLINTHIS_C
  ON EBBS_DLINTHIS_C.DEALCURRCD = EBBS_PMMKDEAL.DEALCURRCD
  AND TRIM(EBBS_DLINTHIS_C.DEALNO) = TRIM(EBBS_PMMKDEAL.DEALNO)
  AND EBBS_DLINTHIS_C.DEPOSITORLOAN = 'D'
  AND EBBS_DLINTHIS_C.ODS = EBBS_PMMKDEAL.ODS
  AND EBBS_DLINTHIS_C.ODS = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN (
  SELECT
    a.DEALCURRCD,
    a.DEALNO,
    SUM(a.INTAMTPAID) AS TOTAL_INT_PD,
    a.DEPOSITORLOAN,
    a.INTPAIDDATE,
    a.ODS
  FROM (
    SELECT
      DEALCURRCD,
      DEALNO,
      INTAMTPAID,
      DEPOSITORLOAN,
      INTPAIDDATE,
      ODS
    FROM {{ source('sri_open_schema', 'ebbs_in_dlinthis') }} AS ebbs_dlinthis
    WHERE
      ODS = '{{ var('__ods_val__') }}'
  ) AS a
  JOIN (
    SELECT
      MAX(INTPAIDDATE) AS INTPAIDDATE,
      DEALCURRCD,
      DEALNO,
      DEPOSITORLOAN
    FROM {{ source('sri_open_schema', 'ebbs_in_dlinthis') }} AS ebbs_dlinthis
    WHERE
      ODS = '{{ var('__ods_val__') }}'
    GROUP BY
      DEALCURRCD,
      DEALNO,
      DEPOSITORLOAN
  ) AS b
    ON a.INTPAIDDATE = b.INTPAIDDATE
    AND a.DEPOSITORLOAN = b.DEPOSITORLOAN
    AND a.DEALCURRCD = b.DEALCURRCD
    AND TRIM(a.DEALNO) = TRIM(b.DEALNO)
  GROUP BY
    a.DEALCURRCD,
    a.DEALNO,
    a.DEPOSITORLOAN,
    a.INTPAIDDATE,
    a.ODS
) AS EBBS_DLINTHIS_D
  ON EBBS_DLINTHIS_D.DEALCURRCD = EBBS_PMMKDEAL.DEALCURRCD
  AND TRIM(EBBS_DLINTHIS_D.DEALNO) = TRIM(EBBS_PMMKDEAL.DEALNO)
  AND EBBS_DLINTHIS_D.DEPOSITORLOAN = 'L'
  AND EBBS_DLINTHIS_D.ODS = EBBS_PMMKDEAL.ODS
  AND EBBS_DLINTHIS_D.ODS = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN (
  SELECT
    a.DEALNO,
    a.SEQNO,
    a.INTERESTAMT,
    a.ODS
  FROM (
    SELECT
      DEALNO,
      SEQNO,
      INTERESTAMT,
      ODS
    FROM {{ source('sri_open_schema', 'ebbs_in_dlintsh') }} AS ebbs_dlintsh
    WHERE
      ODS = '{{ var('__ods_val__') }}'
  ) AS a
  JOIN (
    SELECT
      MAX(SEQNO) AS SEQNO,
      DEALNO
    FROM {{ source('sri_open_schema', 'ebbs_in_dlintsh') }} AS ebbs_dlintsh
    WHERE
      ODS = '{{ var('__ods_val__') }}'
    GROUP BY
      DEALNO
  ) AS b
    ON a.SEQNO = b.SEQNO AND a.DEALNO = b.DEALNO
) AS EBBS_DLINTSH
  ON TRIM(EBBS_DLINTSH.DEALNO) = TRIM(EBBS_PMMKDEAL.DEALNO)
  AND EBBS_DLINTSH.ODS = EBBS_PMMKDEAL.ODS
  AND EBBS_DLINTSH.ods = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN (
  SELECT
    *
  FROM {{ source('sri_open_schema', 'm_scb_entity_xlate') }} AS m_scb_entity_xlate
  WHERE
    ods = '{{ var('__ods_val__') }}' AND tp_system = 'EBBS'
) AS scbentityxlate
  ON TRIM(EBBS_PMMKDEAL.DEALBRANCHCODE) = scbentityxlate.branch_code
  AND EBBS_PMMKDEAL.COUNTRY = scbentityxlate.country_code
  AND scbentityxlate.ODS = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN {{ source('sri_open_schema', 'alt_prty') }} AS ALT_PRTY
  ON TRIM(CAST(EBBS_PMMKDEAL.CUSTTCID AS STRING)) = ALT_PRTY.PRTY_ID
  AND ALT_PRTY.process_id_val = 'ALT_PRTY-SCI-LSPSYSXREF'
  AND ALT_PRTY.ALT_PRTY_SRC_SYS = 'EBBS'
  AND ALT_PRTY.ODS_VAL = '{{ var('__ods_val__') }}'
  AND ALT_PRTY.TP_SYS_VAL = 'SCI'
  AND ALT_PRTY.bkg_org_val = scbentityxlate.sci_entity_code
LEFT OUTER JOIN {{ source('sri_open_schema', 'm_cdl_glbu_to_entcd_bkcd_xlate') }} AS G
  ON g.GL_BU_CD = TRIM(EBBS_PMMKDEAL.DEALBRANCHCODE)
  AND G.SRC_SYS = 'PSGL'
  AND G.CTY = 'XX'
  AND G.ods = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN {{ source('sri_open_schema', 'prty') }} AS PRTY_SP_SCI
  ON PRTY_SP_SCI.PRTY_ID = ALT_PRTY.ALT_PRTY_ID
  AND PRTY_SP_SCI.SRC_SYS = 'SCI'
  AND PRTY_SP_SCI.PRTY_CAT_CD = 'SubProfile'
  AND PRTY_SP_SCI.PROCESS_ID_VAL = 'PRTY-SCI-SUBPROF'
  AND PRTY_SP_SCI.ODS_VAL = '{{ var('__ods_val__') }}'
WHERE
  EBBS_PMMKDEAL.ODS = '{{ var('__ods_val__') }}'
 