    
{{ config(
    alias='acct_ball',
    materialized='table'
) }}

 -- 

 SELECT
  CONCAT(EBBS_PMMKDEAL.DEALCURRCD, '-', TRIM(EBBS_PMMKDEAL.DEALNO)) AS ACCT_ID,
  'EBBS' AS SRC_SYS,
  EBBS_PMMKDEAL.country AS CTRY_CD,
  EBBS_PMMKDEAL.ods AS STRT_DT,
  '9999-12-31' AS END_DT,
  EBBS_PMMKDEAL.DEALCURRCD AS ACCT_CCY,
  CASE
    WHEN EBBS_MDELTYP.DEPOSITORLOAN = 'L'
    THEN (
      EBBS_PMMKDEAL.DEALAMT
    )
    ELSE 0
  END AS ASSET_BAL_OS_AMT,
  CASE WHEN EBBS_PRD.CONTINGENTFLAG = 'Y' THEN EBBS_PMMKDEAL.DEALAMT ELSE 0 END AS CONT_OS_BAL_AMT,
  NULL AS FEE_RECD_ADV_AMT,
  NULL AS FEE_RECD_AMT,
  CASE
    WHEN EBBS_DEALPRV.interesttypeflag = 'C'
    THEN EBBS_DEALPRV.PROVISIONAMOUNT
    ELSE 0
  END AS INT_PYBL_AMT_TD,
  CASE
    WHEN EBBS_DEALPRV.interesttypeflag = 'D'
    THEN EBBS_DEALPRV.PROVISIONAMOUNT
    ELSE 0
  END AS INT_RCVBL_AMT_TD,
  NULL AS INT_RECD_ADV_AMT,
  CASE WHEN EBBS_MDELTYP.DEPOSITORLOAN = 'D' THEN EBBS_PMMKDEAL.DEALAMT ELSE 0 END AS LIAB_BAL_OS_AMT,
  NULL AS MTH_AVG_ASSET_BAL_AMT,
  NULL AS MTH_AVG_CONT_BAL_AMT,
  NULL AS MTH_AVG_LIAB_BAL_AMT,
  NULL AS PAST_DUE_OS_BAL_AMT,
  NULL AS PAST_DUE_OS_INT_AMT,
  NULL AS YR_AVG_ASSET_BAL_AMT,
  NULL AS YR_AVG_CONT_OS_BAL_AMT,
  NULL AS YR_AVG_LIAB_BAL_AMT,
  NULL AS FEE_ACR_AMT,
  NULL AS MTD_FEE_REPMT_AMT,
  NULL AS MTD_INT_REPMT_AMT,
  NULL AS OTH_PYBL_AMT_TD,
  NULL AS OTH_RCVBL_AMT_TD,
  NULL AS FRWD_CR_BAL_AMT,
  NULL AS FRWD_DR_BAL_AMT,
  NULL AS EARMARK_CR_BAL_AMT,
  NULL AS EARMARK_DR_BAL_AMT,
  NULL AS ODS
FROM {{ source('sri_open_schema', 'ebbs_in_pmmkdeal') }} AS ebbs_pmmkdeal
LEFT OUTER JOIN {{ source('sri_open_schema', 'ebbs_in_mdeltyp') }} AS EBBS_MDELTYP
  ON EBBS_MDELTYP.MMKDEALTYPE = EBBS_PMMKDEAL.MMKDEALTYPE
  AND EBBS_MDELTYP.ODS = EBBS_PMMKDEAL.ODS
  AND EBBS_MDELTYP.ODS = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN {{ source('sri_open_schema', 'ebbs_in_dealprv') }} AS EBBS_DEALPRV
  ON EBBS_DEALPRV.CURRENCYCODE = EBBS_PMMKDEAL.DEALCURRCD
  AND TRIM(EBBS_DEALPRV.DEALNO) = TRIM(EBBS_PMMKDEAL.DEALNO)
  AND EBBS_DEALPRV.PROVISIONDATE = EBBS_PMMKDEAL.ODS
  AND EBBS_DEALPRV.ODS = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN {{ source('sri_open_schema', 'ebbs_in_mast') }} AS EBBS_MAST
  ON EBBS_MAST.MASTERNO = EBBS_PMMKDEAL.CUSTTCID
  AND EBBS_MAST.ODS = EBBS_PMMKDEAL.ODS
  AND EBBS_MAST.ODS = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN {{ source('sri_open_schema', 'ebbs_in_prd') }} AS EBBS_PRD
  ON EBBS_MDELTYP.PRODUCTCODE = EBBS_PRD.PRODUCTCODE
  AND EBBS_MDELTYP.ODS = EBBS_PRD.ODS
  AND EBBS_PRD.ODS = '{{ var('__ods_val__') }}'
WHERE
  EBBS_PMMKDEAL.ODS = '{{ var('__ods_val__') }}' AND EBBS_PMMKDEAL.STATUSFLAG <> 14
 