    
{{ config(
    alias='prty1',
    materialized='table'
) }}

 -- 

 WITH WITH_PRTY_EBBS_RELINFO AS (
  SELECT
    SEQNO,
    INFOCODE,
    RELATIONSHIPNO,
    INFOVALUE,
    ODS,
    RNUM
  FROM (
    SELECT
      EBBS_RELINFO.SEQNO AS SEQNO,
      EBBS_RELINFO.INFOCODE AS INFOCODE,
      EBBS_RELINFO.RELATIONSHIPNO AS RELATIONSHIPNO,
      EBBS_RELINFO.INFOVALUE AS INFOVALUE,
      EBBS_RELINFO.ODS AS ODS,
      ROW_NUMBER() OVER (
        PARTITION BY EBBS_RELINFO.SEQNO, EBBS_RELINFO.INFOCODE, EBBS_RELINFO.RELATIONSHIPNO
        ORDER BY EBBS_RELINFO.SEQNO DESC
      ) AS RNUM
    FROM {{ source('sri_open_schema', 'ebbs_in_relinfo') }} AS ebbs_relinfo
    WHERE
      EBBS_RELINFO.ODS = '{{ var('__ods_val__') }}'
  ) AS a
  WHERE
    RNUM = 1
), WITH_PRTY_EBBS_RSKIND AS (
  SELECT
    RELATIONSHIPNO,
    STARTDATE,
    ODS,
    RISKCODE,
    RNUM
  FROM (
    SELECT
      EBBS_RSKIND.RELATIONSHIPNO AS RELATIONSHIPNO,
      EBBS_RSKIND.STARTDATE AS STARTDATE,
      EBBS_RSKIND.ODS AS ODS,
      EBBS_RSKIND.RISKCODE AS RISKCODE,
      ROW_NUMBER() OVER (PARTITION BY RELATIONSHIPNO ORDER BY startdate DESC) AS RNUM
    FROM {{ source('sri_open_schema', 'ebbs_in_rskind') }} AS ebbs_rskind
    WHERE
      EBBS_RSKIND.ODS = '{{ var('__ods_val__') }}'
  ) AS a
  WHERE
    RNUM = 1
), WITH_PRTY_EBBS_MASTREL1 AS (
  SELECT
    COUNTRY,
    masterno,
    ODS,
    Relationshipno,
    primaryflag,
    RNUM
  FROM (
    SELECT
      EBBS_MASTREL.COUNTRY AS COUNTRY,
      EBBS_MASTREL.masterno AS masterno,
      EBBS_MASTREL.ODS AS ODS,
      EBBS_MASTREL.RELATIONSHIPNO AS Relationshipno,
      EBBS_MASTREL.primaryflag AS primaryflag,
      ROW_NUMBER() OVER (PARTITION BY Relationshipno ORDER BY Relationshipno) AS RNUM
    FROM {{ source('sri_open_schema', 'ebbs_in_mastrell') }} AS ebbs_mastrel
    WHERE
      EBBS_MASTREL.ods = '{{ var('__ods_val__') }}'
      AND EBBS_MASTREL.PRIMARYFLAG = 'Y'
      AND EBBS_MASTREL.masterno IN (
        SELECT
          masterno
        FROM {{ source('sri_open_schema', 'ebbs_in_mast') }} AS ebbs_mast
        WHERE
          ods = '{{ var('__ods_val__') }}' AND STATUSFLAG <> 14
      )
  ) AS a
  WHERE
    RNUM = 1
), WITH_PRTY_EBBS_MASTREL2 AS (
  SELECT
    COUNTRY,
    masterno,
    ODS,
    Relationshipno,
    primaryflag,
    RNUM
  FROM (
    SELECT
      EBBS_MASTREL.COUNTRY AS COUNTRY,
      EBBS_MASTREL.masterno AS masterno,
      EBBS_MASTREL.ODS AS ODS,
      EBBS_MASTREL.RELATIONSHIPNO AS Relationshipno,
      EBBS_MASTREL.primaryflag AS primaryflag,
      ROW_NUMBER() OVER (PARTITION BY Relationshipno ORDER BY Relationshipno) AS RNUM
    FROM {{ source('sri_open_schema', 'ebbs_in_mastrell') }} AS ebbs_mastrel
    WHERE
      EBBS_MASTREL.ods = '{{ var('__ods_val__') }}'
      AND EBBS_MASTREL.PRIMARYFLAG <> 'Y'
      AND EBBS_MASTREL.masterno IN (
        SELECT
          masterno
        FROM {{ source('sri_open_schema', 'ebbs_in_mast') }} AS ebbs_mast
        WHERE
          ods = '{{ var('__ods_val__') }}' AND STATUSFLAG <> 14
      )
  ) AS a
  WHERE
    RNUM = 1
), WITH_PRTY_EBBS_MAST AS (
  SELECT
    masterno,
    country,
    ods,
    instclasscode,
    statusflag,
    ultimatecntrycode,
    affiliatedcode,
    isiccode,
    crgcode
  FROM (
    SELECT
      EBBS_MAST.masterno AS masterno,
      EBBS_MAST.country AS country,
      EBBS_MAST.ods AS ods,
      EBBS_MAST.instclasscode AS instclasscode,
      EBBS_MAST.statusflag AS statusflag,
      EBBS_MAST.ultimatecntrycode AS ultimatecntrycode,
      EBBS_MAST.affiliatedcode AS affiliatedcode,
      EBBS_MAST.isiccode AS isiccode,
      EBBS_MAST.crgcode AS crgcode
    FROM {{ source('sri_open_schema', 'ebbs_in_mast') }} AS ebbs_mast
    WHERE
      EBBS_MAST.ods = '{{ var('__ods_val__') }}' AND EBBS_MAST.statusflag <> 14
  ) AS a
  WHERE
    ods = '{{ var('__ods_val__') }}'
), WITH_PRTY_EBBS_MSTINFO AS (
  SELECT
    SEQNO,
    INFORMATIONCODE,
    referenceno,
    INFODETCODE,
    ODS,
    RNUM
  FROM (
    SELECT
      EBBS_MSTINFO.SEQNO AS SEQNO,
      EBBS_MSTINFO.INFORMATIONCODE AS INFORMATIONCODE,
      EBBS_MSTINFO.referenceno AS referenceno,
      EBBS_MSTINFO.INFODETCODE AS INFODETCODE,
      EBBS_MSTINFO.ODS AS ODS,
      ROW_NUMBER() OVER (PARTITION BY SEQNO, INFORMATIONCODE, referenceno ORDER BY SEQNO DESC) AS RNUM
    FROM {{ source('sri_open_schema', 'ebbs_in_mstinfo') }} AS ebbs_mstinfo
    WHERE
      EBBS_MSTINFO.ods = '{{ var('__ods_val__') }}' AND EBBS_MSTINFO.INFORMATIONCODE IN ('BNR')
  ) AS a
  WHERE
    RNUM = 1
)
SELECT
  TRIM(CAST(EBBS_REL.RELATIONSHIPNO AS STRING)) AS PRTY_ID,
  'EBBS' AS SRC_SYS,
  COALESCE(EBBS_REL.COUNTRY, '') AS CTRY_CD,
  EBBS_REL.ods AS STRT_DT,
  '9999-12-31' AS END_DT,
  EBBS_REL.WORKTYPE AS PRTY_BIZ_TYPE_CD,
  NULL AS PRTY_CLTR_PLDG_RL_CD,
  CASE
    WHEN RL1.MASTERNO = M1.MASTERNO
    THEN M1.ULTIMATECNTRYCODE
    WHEN RL2.MASTERNO = M2.MASTERNO
    THEN M2.ULTIMATECNTRYCODE
    ELSE ''
  END AS PRTY_INC_CTRY_CD,
  '' AS PRTY_CR_RISK_RESP_CTRY_CD,
  NULL AS PRTY_CR_TEAM_CD,
  NULL AS DATA_SHR_CNST_FLG,
  'Relationship' AS FILE_TYPE,
  EBBS_REL.REVIEWDATE AS PRTY_APPR_RVW_DT,
  NULL AS PRTY_FM_INDUSTRY_CD,
  NULL AS PRTY_GBL_RTNG_FLG,
  NULL AS GUARANTEED_BY_PRNT_FLG,
  NULL AS PRTY_HUB_LOC,
  NULL AS PRTY_IFRS_CP_TYPE_CD,
  EBBS_REL.CONSOLSTMTLANG AS PRTY_LANG_CD,
  NULL AS PRTY_PRNT_SUPT_ELGT_CD,
  CASE
    WHEN RL1.MASTERNO = M1.MASTERNO
    THEN M1.AFFILIATEDCODE
    WHEN RL2.MASTERNO = M2.MASTERNO
    THEN M2.AFFILIATEDCODE
    ELSE ''
  END AS PRTY_AFFL_CD,
  NULL AS PRTY_ANNL_SALES_AMT,
  NULL AS PRTY_ANNL_SALES_AMT_CCY,
  EBBS_REL.ANNUALINCOME AS PRTY_ANNL_INCOME_AMT,
  EBBS_REL.ANNUALINCOMELSTUPDT AS PRTY_ANNL_INCOME_UPDT_DT,
  EBBS_REL.BANKRUPTCYDATE AS PRTY_BKRPT_DT,
  EBBS_REL.BANKRUPTCYRECORDFLAG AS PRTY_BKRPT_FLG,
  NULL AS PRTY_BSL_SGMT_CD,
  NULL AS PRTY_BSL_SUB_SGMT_CD,
  NULL AS PRTY_BENEF_CP_CD,
  EBBS_REL.DATEOFBIRTH AS PRTY_BIRTH_DT,
  NULL AS PRTY_BORROW_EXCP_FLG,
  CASE
    WHEN EBBS_REL.RELATIONSHIPTYPE = 'I'
    THEN 'Retail'
    WHEN EBBS_REL.RELATIONSHIPTYPE = 'C'
    THEN 'Corporate'
    ELSE 'Internal'
  END AS PRTY_CAT_CD,
  NULL AS PRTY_CR_RISK_LOC_CD,
  NULL AS PRTY_CR_STS_CD,
  NULL AS PRTY_CRM_REF_NUM,
  CASE WHEN EBBS_RSKIND.RISKCODE = 'DER' THEN EBBS_RSKIND.STARTDATE ELSE NULL END AS PRTY_DECSD_DT,
  CASE WHEN EBBS_RSKIND.RISKCODE = 'DER' THEN 'Y' ELSE '' END AS PRTY_DECSD_FLG,
  NULL AS PRTY_DCLR_INCOME_AMT,
  NULL AS PRTY_DLFT_CR_GRD_FLG,
  NULL AS PRTY_DLNQ_STRT_DT,
  EBBS_REL.TOTALNOOFDEP AS PRTY_DEPN_CNT,
  EBBS_REL.DESIGNATIONCODE AS PRTY_DESG_CD,
  NULL AS PRTY_DSCL_AGMT_EFF_DT,
  NULL AS PRTY_DSCL_AGMT_FLG,
  COALESCE(EBBS_REL.DOMICILECOUNTRY, '') AS PRTY_DMCL_CTRY_CD,
  EBBS_REL.QUALIFICATIONCODE AS PRTY_ED_LVL_CD,
  NULL AS PRTY_ELIG_FLG,
  NULL AS PRTY_EMPLR_NM,
  NULL AS PRTY_ENV_SR_GRD_CD,
  NULL AS PRTY_FIN_INST_CD,
  NULL AS PRTY_FM_CD,
  NULL AS PRTY_FSA_RPT_CLNT_CD,
  EBBS_REL.SEX AS PRTY_GNDR_CD,
  EBBS_REL.INCORPORATEDDATE AS PRTY_INC_DT,
  CASE WHEN EBBS_REL.RELATIONSHIPTYPE = 'C' THEN EBBS_REL.UNIQUEID1 ELSE '' END AS PRTY_INC_NUM,
  CASE
    WHEN RL1.MASTERNO = M1.MASTERNO
    THEN M1.INSTCLASSCODE
    WHEN RL2.MASTERNO = M2.MASTERNO
    THEN M2.INSTCLASSCODE
    ELSE ''
  END AS PRTY_INST_CLAS_CD,
  NULL AS PRTY_INST_SCTR_CD,
  CASE
    WHEN RL1.MASTERNO = M1.MASTERNO
    THEN M1.ISICCODE
    WHEN RL2.MASTERNO = M2.MASTERNO
    THEN M2.ISICCODE
    ELSE ''
  END AS PRTY_ISIC_CD,
  NULL AS PRTY_ISIC_CD_STRT_DT,
  NULL AS PRTY_ISIC_CD_WGHT,
  NULL AS PRTY_ISIC_TYPE,
  EBBS_REL.CONSTITUTIONCODE AS PRTY_LGL_CONT_TYPE_CD,
  EBBS_REL.FIRSTNAME AS PRTY_LGL_NM,
  EBBS_REL.FULLNAME AS PRTY_LONG_NM,
  EBBS_REL.MARITALST AS PRTY_MRTL_STS,
  NULL AS PRTY_MODE_OF_SAL,
  EBBS_REL.OTHERMTHLYINCOME AS PRTY_MTH_ALLW_AMT,
  EBBS_REL.MTHLYBASIC AS PRTY_MTH_BSC_SAL_AMT,
  EBBS_REL.MTHLYCOMM AS PRTY_MTH_COMS_AMT,
  COALESCE(EBBS_REL.NATIONALITYCODE, '') AS PRTY_NTLTY_CTRY_CD,
  EBBS_REL.NATUREOFBUSINESS AS PRTY_NATR_OF_BIZ,
  NULL AS PRTY_NET_WRTH_AMT,
  NULL AS PRTY_NEW_SGMT_CD,
  EBBS_REL.PROFESSIONCODE AS PRTY_OCCP_CD,
  EBBS_REL.NATUREOFBUSINESS AS PRTY_ORG_TYPE_CD,
  NULL AS PRTY_OTH_BANK_CR_LMT_AMT,
  NULL AS PRTY_OTH_BANK_MTH_ILA_AMT,
  EBBS_REL.OTHERMTHLYINCOME AS PRTY_OTH_MTH_INCOME_AMT,
  EBBS_REL.POSITIONTITLE AS PRTY_POS_TITL,
  NULL AS PRTY_PRIME_BKR_FLG,
  EBBS_REL.PROFESSIONCODE AS PRTY_PRFSN_CD,
  NULL AS PRTY_RL_END_DT,
  NULL AS PRTY_RL_INFO_VAL,
  EBBS_REL.ARMCODE AS PRTY_ARM_CD,
  EBBS_REL.RELOPENDATE AS PRTY_RL_STRT_DT,
  COALESCE(EBBS_REL.RESIDENTCOUNTRY, '') AS PRTY_RSDN_CTRY_CD,
  EBBS_REL.RESIDENTSTATUS AS PRTY_RSDNL_STS_CD,
  NULL AS PRTY_SALES_TURN_OVR_AMT,
  NULL AS PRTY_SALES_TURN_OVR_CCY,
  EBBS_REL.STAFF AS PRTY_SCB_STAF_TYPE,
  EBBS_REL.SEGMENTCODE AS PRTY_SGMT_CD,
  CASE
    WHEN EBBS_REL.FIRSTNAME <> ''
    THEN EBBS_REL.FIRSTNAME
    ELSE EBBS_REL.FULLNAME
  END AS PRTY_SHORT_NM,
  EBBS_REL.STATUSUPDATEDT AS PRTY_STS_EFF_DT,
  EBBS_REL.RELSTATUS AS PRTY_STS_CD,
  EBBS_REL.CUSTSEGMTCODE AS PRTY_SUB_SGMT_CD,
  NULL AS PRTY_TOT_WORK_EXPNC,
  CASE
    WHEN EBBS_REL.RELATIONSHIPTYPE = 'C'
    THEN 'CompanyRelationship'
    ELSE 'RetailRelationship'
  END AS PRTY_TYPE_CD,
  NULL AS PRTY_SCB_CLAS_CD,
  NULL AS PRTY_SCB_ENT_FLG,
  NULL AS PRTY_SRC_PLDG_ID,
  NULL AS TOP_1000_BANK_IND,
  NULL AS PRTY_CFTC_CRCC_FLG,
  EBBS_SEG.CORPORATEFLAG AS PRTY_CORP_FLG,
  EBBS_SEG.BFSFLAG AS PRTY_SME_FLG,
  COALESCE(EBBS_REL.COUNTRY, '') AS BKG_CTRY_CD,
  NULL AS COIN_NUM,
  EBBS_REL.SALUTATIONCODE AS SALN_CD,
  EBBS_REL.STAFFNO AS STAF_ID,
  CASE
    WHEN RL1.MASTERNO = M1.MASTERNO
    THEN EBBS_INSTCLS_1.ISSTAFFCLASS
    WHEN RL2.MASTERNO = M2.MASTERNO
    THEN EBBS_INSTCLS_2.ISSTAFFCLASS
    ELSE ''
  END AS STAF_FLG,
  NULL AS MAND_CLRG_FLG,
  NULL AS PRTY_OPT_OUT_ANNL_FIL_FLG,
  NULL AS DF_PTCOL_2_SIDE_LTR_FLG,
  NULL AS PRTY_EUE_NOTC_FLG,
  NULL AS DF_PTCOL_2_SIDE_COMPL_FLG,
  NULL AS DF_ENT_CD,
  NULL AS SPL_ENT_FLG,
  NULL AS SPL_ENT_SUB_CAT,
  NULL AS QIR_FLG,
  NULL AS US_DMCL_FLG,
  NULL AS DF_ENT_SUB_TYPE,
  NULL AS FIN_ENT_EXCP_FLG,
  CASE
    WHEN RL1.MASTERNO = M1.MASTERNO
    THEN M1.CRGCODE
    WHEN RL2.MASTERNO = M2.MASTERNO
    THEN M2.CRGCODE
    ELSE ''
  END AS INDUSTRY_RISK_CLAS_CD,
  NULL AS DF_COMPL_FLG,
  NULL AS ELIG_CONTR_PARTP_FLG,
  NULL AS INIT_MGRN_METH_CD,
  '' AS DF_CTRY_CD,
  CASE
    WHEN NOT TRIM(RL1.MASTERNO) IS NULL
    THEN TRIM(M1.MASTERNO)
    WHEN NOT TRIM(RL2.MASTERNO) IS NULL
    THEN TRIM(M2.MASTERNO)
    ELSE ''
  END AS EXTR_PRTY_ID,
  EBBS_CONST.description AS PRTY_LGL_CONT_TYPE_DESC,
  CASE WHEN WLNK_1.INFOCODE = 'ETH' THEN WLNK_1.INFOVALUE ELSE '' END AS ETHNC_CD,
  NULL AS OWN_CD,
  CASE WHEN WLNK_2.INFOCODE = 'TUR' THEN WLNK_2.INFOVALUE ELSE '' END AS TURN_AMT,
  CASE WHEN WLNK_3.INFOCODE = 'TU1' THEN WLNK_3.INFOVALUE ELSE '' END AS TURN_YR,
  CASE WHEN WLNK_4.INFOCODE = 'EMP' THEN WLNK_4.INFOVALUE ELSE '' END AS EMP_CNT,
  CASE WHEN WLNK_5.INFOCODE IN ('AO1', 'AO2') THEN WLNK_5.INFOVALUE ELSE '' END AS DEP_PRPS,
  EBBS_REL.UNIQUEID2 AS UNIQ_ID_2,
  EBBS_REL.UNIQUEID3 AS UNIQ_ID_3,
  EBBS_REL.UNIQUEID4 AS UNIQ_ID_4,
  CASE
    WHEN NOT TRIM(RL1.MASTERNO) IS NULL
    THEN EBBS_MSTINFO_BNM_1.INFODETCODE
    WHEN NOT TRIM(RL2.MASTERNO) IS NULL
    THEN EBBS_MSTINFO_BNM_2.INFODETCODE
    ELSE ''
  END AS PRTY_BNM_RSDNL_CD,
  NULL AS ODS
FROM {{ source('sri_open_schema', 'ebbs_in_rel') }} AS ebbs_rel
LEFT OUTER JOIN {{ source('sri_open_schema', 'with_prty_ebbs_rskind') }} AS EBBS_RSKIND
  ON EBBS_RSKIND.RELATIONSHIPNO = EBBS_REL.RELATIONSHIPNO
  AND EBBS_RSKIND.RISKCODE = 'DER'
  AND EBBS_REL.ods = EBBS_RSKIND.ods
  AND EBBS_RSKIND.RNUM = 1
  AND EBBS_RSKIND.ods = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN {{ source('sri_open_schema', 'ebbs_in_seg') }} AS EBBS_SEG
  ON EBBS_REL.SEGMENTCODE = EBBS_SEG.SEGMENTCODE
  AND EBBS_REL.ods = EBBS_SEG.ods
  AND EBBS_SEG.ods = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN {{ source('sri_open_schema', 'with_prty_ebbs_relinfo') }} AS WLNK_1
  ON WLNK_1.RELATIONSHIPNO = EBBS_REL.RELATIONSHIPNO
  AND WLNK_1.ods = EBBS_REL.ods
  AND WLNK_1.ODS = '{{ var('__ods_val__') }}'
  AND WLNK_1.INFOCODE = (
    'ETH'
  )
  AND WLNK_1.RNUM = 1
LEFT OUTER JOIN {{ source('sri_open_schema', 'with_prty_ebbs_relinfo') }} AS WLNK_2
  ON WLNK_2.RELATIONSHIPNO = EBBS_REL.RELATIONSHIPNO
  AND WLNK_2.ods = EBBS_REL.ods
  AND WLNK_2.ODS = '{{ var('__ods_val__') }}'
  AND WLNK_2.INFOCODE = (
    'TUR'
  )
  AND WLNK_2.RNUM = 1
LEFT OUTER JOIN {{ source('sri_open_schema', 'with_prty_ebbs_relinfo') }} AS WLNK_3
  ON WLNK_3.RELATIONSHIPNO = EBBS_REL.RELATIONSHIPNO
  AND WLNK_3.ods = EBBS_REL.ods
  AND WLNK_3.ODS = '{{ var('__ods_val__') }}'
  AND WLNK_3.INFOCODE = (
    'TU1'
  )
  AND WLNK_3.RNUM = 1
LEFT OUTER JOIN {{ source('sri_open_schema', 'with_prty_ebbs_relinfo') }} AS WLNK_4
  ON WLNK_4.RELATIONSHIPNO = EBBS_REL.RELATIONSHIPNO
  AND WLNK_4.ods = EBBS_REL.ods
  AND WLNK_4.ODS = '{{ var('__ods_val__') }}'
  AND WLNK_4.INFOCODE = (
    'EMP'
  )
  AND WLNK_4.RNUM = 1
LEFT OUTER JOIN {{ source('sri_open_schema', 'with_prty_ebbs_relinfo') }} AS WLNK_5
  ON WLNK_5.RELATIONSHIPNO = EBBS_REL.RELATIONSHIPNO
  AND WLNK_5.ods = EBBS_REL.ods
  AND WLNK_5.ODS = '{{ var('__ods_val__') }}'
  AND WLNK_5.INFOCODE IN ('AO1', 'AO2')
  AND WLNK_5.RNUM = 1
LEFT OUTER JOIN {{ source('sri_open_schema', 'with_prty_ebbs_mastrel1') }} AS RL1
  ON TRIM(RL1.RELATIONSHIPNO) = TRIM(EBBS_REL.RELATIONSHIPNO)
  AND RL1.country = EBBS_REL.COUNTRY
  AND RL1.ODS = EBBS_REL.ODS
  AND RL1.RNUM = 1
LEFT OUTER JOIN {{ source('sri_open_schema', 'with_prty_ebbs_mastrel2') }} AS RL2
  ON TRIM(RL2.RELATIONSHIPNO) = TRIM(EBBS_REL.RELATIONSHIPNO)
  AND RL2.country = EBBS_REL.COUNTRY
  AND RL2.ODS = EBBS_REL.ODS
  AND RL2.RNUM = 1
LEFT OUTER JOIN {{ source('sri_open_schema', 'with_prty_ebbs_mast') }} AS M1
  ON RL1.MASTERNO = M1.MASTERNO
  AND M1.ODS = RL1.ODS
  AND M1.COUNTRY = EBBS_REL.COUNTRY
  AND M1.STATUSFLAG <> 14
  AND M1.ODS = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN {{ source('sri_open_schema', 'with_prty_ebbs_mast') }} AS M2
  ON RL2.MASTERNO = M2.MASTERNO
  AND M2.ODS = RL2.ODS
  AND M2.COUNTRY = EBBS_REL.COUNTRY
  AND M2.STATUSFLAG <> 14
  AND M2.ODS = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN {{ source('sri_open_schema', 'ebbs_in_instcls') }} AS EBBS_INSTCLS_1
  ON M1.INSTCLASSCODE = EBBS_INSTCLS_1.INSTCLASSCODE
  AND M1.ods = EBBS_INSTCLS_1.ods
  AND EBBS_INSTCLS_1.ods = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN {{ source('sri_open_schema', 'ebbs_in_instcls') }} AS EBBS_INSTCLS_2
  ON M2.INSTCLASSCODE = EBBS_INSTCLS_2.INSTCLASSCODE
  AND M2.ods = EBBS_INSTCLS_2.ods
  AND EBBS_INSTCLS_2.ods = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN {{ source('sri_open_schema', 'with_prty_ebbs_mstinfo') }} AS EBBS_MSTINFO_BNM_1
  ON TRIM(EBBS_MSTINFO_BNM_1.REFERENCENO) = TRIM(M1.MASTERNO)
  AND EBBS_MSTINFO_BNM_1.ods = M1.ods
  AND EBBS_MSTINFO_BNM_1.ODS = '{{ var('__ods_val__') }}'
  AND EBBS_MSTINFO_BNM_1.RNUM = 1
LEFT OUTER JOIN {{ source('sri_open_schema', 'with_prty_ebbs_mstinfo') }} AS EBBS_MSTINFO_BNM_2
  ON TRIM(EBBS_MSTINFO_BNM_2.REFERENCENO) = TRIM(M2.MASTERNO)
  AND EBBS_MSTINFO_BNM_2.ods = M2.ods
  AND EBBS_MSTINFO_BNM_2.ODS = '{{ var('__ods_val__') }}'
  AND EBBS_MSTINFO_BNM_2.RNUM = 1
LEFT OUTER JOIN {{ source('sri_open_schema', 'ebbs_in_const') }} AS EBBS_CONST
  ON EBBS_REL.CONSTITUTIONCODE = EBBS_CONST.CONSTITUTIONCODE
  AND EBBS_REL.ods = EBBS_CONST.ods
  AND EBBS_CONST.ods = '{{ var('__ods_val__') }}'
WHERE
  EBBS_REL.ODS = '{{ var('__ods_val__') }}'
 