    
{{ config(
    alias='pe_bal',
    materialized='table'
) }}

 -- 

 SELECT
  SL.SUBL_ID AS SUBL_ID,
  SL.SUBL_ID_TYPE AS SUBL_ID_TYPE,
  SL.SUBL_ID AS TRAN_REF_NO,
  CASE WHEN NOT ACCT.ACCT_ID IS NULL THEN 'ACCT' ELSE 'NA' END AS CAT_CD,
  SL.UNIQ_ID AS UNIQ_ID,
  SL.SRC_SYS AS SRC_SYS,
  SL.CTRY_CD AS CTRY_CD,
  NULL AS INSTR_ID,
  NULL AS PTFOL_ID,
  ACCT.PRTY_ID AS PRTY_ID,
  SUBSTRING(ACCT.PRTY_ID, 1, 8) AS PRTY_MAIN_ID,
  NULL AS RISK_PRTY_ID,
  NULL AS BKR_ID,
  NULL AS CLRG_BKR_ID,
  ACCT.CP_ID AS CP_ID,
  NULL AS SRC_RISK_PRTY_ID,
  NULL AS SRC_BKR_ID,
  NULL AS SRC_CLRG_BKR_ID,
  ACCT.ACCT_STS_CD AS ACCT_STS_CD,
  ACCT.LIFCYCL_STS_CD AS LIFCYCL_STS_CD,
  ACCT.LOCAL_PRD_CD AS LOCAL_PRD_CD,
  ACCT.STD_PRD_CD AS STD_PRD_CD,
  G.COMP_CD AS BK_CD,
  ACCT.TP_ENT_NM AS TP_ENT_NM,
  SL.LGL_ENT_CD AS LGL_ENT_CD,
  ACCT.BKG_LOC_CD AS BKG_LOC_CD,
  ACCT.LN_EFF_DT AS ADJ_VAL_DT_1,
  ACCT.FST_LN_DRWDOWN_DT AS TRD_DT,
  NULL AS ACCT_OPEN_DT,
  ACCT.MATURITY_DT AS MATURITY_DT,
  ACCT.SETLM_DT AS SETLM_DT,
  NULL AS ALT_TRD_ID,
  NULL AS ALT_TRD_SRC_SYS,
  NULL AS EXTR_TRD_ID,
  NULL AS CONTR_ID,
  NULL AS ORIG_TRD_ID,
  NULL AS NEAR_FAR_CD,
  NULL AS BUY_SEL_FLG_1,
  NULL AS BUY_SEL_FLG_2,
  NULL AS PAY_RECV_FLG_1,
  NULL AS PAY_RECV_FLG_2,
  NULL AS TRD_LEND_BORROW_TYPE,
  NULL AS PTFOL_NM,
  SL.GL_BIZ_UNIT_CD AS GL_BIZ_UNIT_CD,
  SL.GL_ACCT_CD AS GL_ACCT_CD,
  SL.GL_DEPT_CD AS GL_DEPT_CD,
  SL.GL_AFFL_CD AS GL_AFFL_CD,
  SL.GL_CUST_CLAS_CD AS GL_CUST_CLAS_CD,
  COA.CHRT_FLD_LVL_0 AS GL_CUST_CLAS_CD_DESC,
  SL.GL_OP_UNIT_CD AS GL_OP_UNIT_CD,
  SL.GL_PRD_CD AS GL_PRD_CD,
  SUBSTRING(PGC.chrt_fld_cat_cd, 1, 1) AS ACCT_CAT_NM,
  SL.COA_ACCT_CLAS AS ACCT_CLAS,
  SL.ACCT_SUB_CAT_NM AS ACCT_SUB_CAT_NM,
  SL.BASE_CCY AS BASE_CCY,
  NULL AS CHRG_INT_CD,
  NULL AS CTRY_LVL_ID,
  NULL AS IFRS_SCHED,
  SL.GL_AMT_TYPE AS AMT_TYPE,
  SL.GL_CP_TYPE AS GL_CP_TYPE,
  SL.IFRS_CP_TYPE_CD AS IFRS_CP_TYPE_CD,
  SL.S4_OPR_LOC_CD AS S4_OPR_LOC_CD,
  SL.S4_PRD_CD AS S4_PRD_CD,
  SL.S4_PRFT_CTR AS S4_PRFT_CTR,
  SL.S4_SGMT_CD AS S4_SGMT_CD,
  SL.SUBL_ACCT AS SUBL_ACCT,
  SL.SUBL_ACCT_DESC AS SUBL_ACCT_DESC,
  SL.SUBL_ACCT_GRP AS SUBL_ACCT_GRP,
  SL.SUBL_ACCT_GRP_DESC AS SUBL_ACCT_GRP_DESC,
  SL.LOCAL_CCY AS LOCAL_CCY,
  SL.GRP_CCY AS GRP_CCY,
  SL.TRAN_CCY AS TRAN_CCY,
  SL.bal_amt AS BAL_AMT,
  SL.bal_amt_usd AS BAL_AMT_USD,
  SL.GL_ITD_AMT AS GL_ITD_AMT,
  NULL AS NOT_AMT_CCY_1,
  NULL AS NOT_AMT_CCY_2,
  NULL AS NOT_AMT_1,
  NULL AS NOT_AMT_2,
  NULL AS TRD_LEG_NUM,
  SL.INTCO_FLG AS INTCO_FLG,
  SL.GL_EXCLN_FLG AS GL_EXCLN_FLG,
  NULL AS ECL_EXPSR_FLG,
  SL.GL_ACCT_FLG AS GL_ACCT_FLG,
  NULL AS LEAD_TRD_FLG,
  NULL AS TRD_BK_CD,
  NULL AS SEQ_ID,
  NULL AS SUBL_PRD_TYPE,
  'FPSL' AS DATA_SRC,
  SL.STRT_DT AS STRT_DT,
  SL.END_DT AS END_DT,
  NULL AS STRUC_FLG,
  NULL AS STRUC_PRD_GRP,
  SL.TP_SRC_SYS AS TP_SRC_SYS,
  NULL AS RISK_PRTY_MP_ID,
  ACCT.SRC_CUST_ID AS SRC_CUST_ID,
  PGC.DESC AS PGC_ACCT_DESC,
  PGC.CHRT_FLD_CAT_CD AS PGC_BALANCE_TYPE,
  PGC.PGC_IFRSS_SCH AS PGC_IFRSS_SCH,
  PGC.PGC_IFRSS_SCH_DESC AS PGC_IFRSS_SCH_DESC,
  PGC.PGC_GRP_NONGRP AS PGC_GRP_NONGRP,
  PGC.PGC_MR_SCH_REF AS PGC_MR_SCH_REF,
  ACCTCLASS.ACCOUNTINGCLASSIFICATION AS IFRS_ACCT_CLASS,
  JRNLSRC.DERIVED_ADM_JRNL_SRC AS ADM_JRNL_SRC,
  PRTY_SP_TPCLIENT.PRTY_IFRS_CP_TYPE_CD AS PRTY_IFRS_CP_TYPE_CD,
  SL.GL_STD_PRD_CD AS GL_STD_PRD_CD,
  GL.AMT_MAIN_GRP AS AMT_GRP,
  GL.AMT_SUB_GRP AS AMT_SUB_GRP,
  REPLACE(SL.SUBL_ID, '-', '') AS TRAN_REF_ID,
  ACCT.FILE_TYPE AS LPC_CAT_CD,
  SL.ODS_VAL AS ODS,
  ACCT_BAL.MTH_AVG_ASSET_BAL_AMT AS MTH_AVG_ASSET_BAL_AMT,
  ACCT_BAL.MTH_AVG_CONT_BAL_AMT AS MTH_AVG_CONT_BAL_AMT,
  ACCT_BAL.MTH_AVG_LIAB_BAL_AMT AS MTH_AVG_LIAB_BAL_AMT,
  ACCT_BAL.YR_AVG_ASSET_BAL_AMT AS YR_AVG_ASSET_BAL_AMT,
  ACCT_BAL.YR_AVG_CONT_OS_BAL_AMT AS YR_AVG_CONT_OS_BAL_AMT,
  ACCT_BAL.YR_AVG_LIAB_BAL_AMT AS YR_AVG_LIAB_BAL_AMT,
  ACCT.NXT_MATURITY_DT AS NXT_MATURITY_DT,
  ACCT.CR_INT_ACR_BSIS_CD AS CR_INT_ACR_BSIS_CD,
  ACCT.DR_INT_ACR_BSIS_CD AS DR_INT_ACR_BSIS_CD,
  ACCT.INT_RT_TYPE AS INT_RT_TYPE,
  ACCT.INT_RT AS INT_RT,
  ACCT.NXT_INT_PYMT_DT AS NXT_INT_PYMT_DT,
  ACCT.ACCT_OPEN_BR_CD AS ACCT_OPEN_BR_CD,
  ACCT.ACCT_CLSE_DT AS ACCT_CLSE_DT,
  ACCT.ACCT_POOL_ID AS ACCT_POOL_ID,
  ACCT.ACCT_POOL_FLG AS ACCT_POOL_FLG,
  ACCT.FAC_ORIG_LOC AS FAC_ORIG_LOC,
  ACCT.LAST_CR_INT_RT AS LAST_CR_INT_RT,
  ACCT.LAST_DR_INT_RT AS LAST_DR_INT_RT,
  ACCT.LCL_DEAL_TYPE AS LPC_TYPE,
  ACCT.LOCAL_PRD_DESC AS LOCAL_PRD_DESC,
  PRVSN.TOT_PRVSN_AMT AS TOT_CHRG_OFF_AMT,
  ACCT.DAYS_PAST_DUE AS DAYS_PAST_DUE,
  PRTY_RTNG.PRTY_CR_RISK_RTNG_CD AS PRTY_CR_RISK_RTNG_CD,
  PRTY_RTNG_TP.PRTY_CR_RISK_RTNG_CD AS TP_PRTY_CR_RISK_RTNG_CD,
  ACCT.LAST_EXCES_DT AS LAST_EXCES_DT,
  ACCT.CUST_MRGN_RT AS CUST_MRGN_RT,
  PRVSN.CHOFF_FLG AS CHOFF_FLG,
  PRVSN.TXN_DT AS CHOFF_DT,
  ACCT.LIFCYCL_STS_DT AS LIFCYCL_STS_DT,
  CASE WHEN ACCT.OVR_DFT_TYPE = 'PCL' THEN 'F' ELSE 'V' END AS FIX_FLT_FLG_1,
  PRTY_MST.PRTY_SGMT_CD AS TP_BIZ_SGMT_CD
FROM (
  SELECT
    SL1.SUBL_ID,
    SL1.SUBL_ID_TYPE,
    SL1.UNIQ_ID,
    SL1.SRC_SYS,
    SL1.CTRY_CD,
    SL1.LGL_ENT_CD,
    SL1.COA_ACCT_CLAS,
    SL1.ACCT_SUB_CAT_NM,
    SL1.BASE_CCY,
    SL1.GL_AMT_TYPE,
    SL1.GL_CP_TYPE,
    SL1.GL_BIZ_UNIT_CD,
    SL1.GL_ACCT_CD,
    SL1.GL_DEPT_CD,
    SL1.GL_AFFL_CD,
    SL1.GL_CUST_CLAS_CD,
    SL1.GL_OP_UNIT_CD,
    SL1.GL_PRD_CD,
    SL1.S4_OPR_LOC_CD,
    SL1.S4_PRD_CD,
    SL1.S4_PRFT_CTR,
    SL1.S4_SGMT_CD,
    SL1.IFRS_CP_TYPE_CD,
    SL1.SUBL_ACCT,
    SL1.SUBL_ACCT_DESC,
    SL1.SUBL_ACCT_GRP,
    SL1.SUBL_ACCT_GRP_DESC,
    SL1.LOCAL_CCY,
    SL1.GRP_CCY,
    SL1.TRAN_CCY,
    SL1.GL_ITD_AMT,
    SL1.INTCO_FLG,
    SL1.GL_EXCLN_FLG,
    SL1.GL_ACCT_FLG,
    SL1.STRT_DT,
    SL1.END_DT,
    SL1.TP_SRC_SYS,
    SL1.GL_STD_PRD_CD,
    SL1.ODS_VAL,
    SL1.country_val,
    SUM(SL1.BAL_AMT_USD) AS bal_amt_usd,
    SUM(SL1.BAL_AMT) AS bal_amt
  FROM {{ source('sri_open_schema', 'sub_ldgr') }} AS SL1
  WHERE
    SL1.ODS_VAL = '{{ var('__ods_val__') }}'
    AND SL1.PROCESS_ID_VAL = 'SUB_LDGR-EBBS-FPSLBS'
    AND SL1.SRC_SYS = 'EBBS'
    AND SL1.COUNTRY_VAL = 'IN'
    AND SL1.TP_SYS_VAL = 'FPSL'
    AND SL1.SRC_SYS = 'EBBS'
    AND COALESCE(SL1.GL_EXCLN_FLG, '') <> 'Y'
  GROUP BY
    SL1.SUBL_ID,
    SL1.SUBL_ID_TYPE,
    SL1.UNIQ_ID,
    SL1.SRC_SYS,
    SL1.CTRY_CD,
    SL1.LGL_ENT_CD,
    SL1.COA_ACCT_CLAS,
    SL1.ACCT_SUB_CAT_NM,
    SL1.BASE_CCY,
    SL1.GL_AMT_TYPE,
    SL1.GL_CP_TYPE,
    SL1.GL_BIZ_UNIT_CD,
    SL1.GL_ACCT_CD,
    SL1.GL_DEPT_CD,
    SL1.GL_AFFL_CD,
    SL1.GL_CUST_CLAS_CD,
    SL1.GL_OP_UNIT_CD,
    SL1.GL_PRD_CD,
    SL1.S4_OPR_LOC_CD,
    SL1.S4_PRD_CD,
    SL1.S4_PRFT_CTR,
    SL1.S4_SGMT_CD,
    SL1.IFRS_CP_TYPE_CD,
    SL1.SUBL_ACCT,
    SL1.SUBL_ACCT_DESC,
    SL1.SUBL_ACCT_GRP,
    SL1.SUBL_ACCT_GRP_DESC,
    SL1.LOCAL_CCY,
    SL1.GRP_CCY,
    SL1.TRAN_CCY,
    SL1.GL_ITD_AMT,
    SL1.INTCO_FLG,
    SL1.GL_EXCLN_FLG,
    SL1.GL_ACCT_FLG,
    SL1.STRT_DT,
    SL1.END_DT,
    SL1.TP_SRC_SYS,
    SL1.GL_STD_PRD_CD,
    SL1.ODS_VAL,
    SL1.country_val
) AS SL
LEFT OUTER JOIN {{ source('sri_open_schema', 'acct') }} AS ACCT
  ON ACCT.ACCT_ID = SL.SUBL_ID
  AND ACCT.country_val = SL.country_val
  AND ACCT.ODS_VAL = SL.ODS_VAL
  AND ACCT.SRC_SYS = 'EBBS'
  AND ACCT.TP_SYS_VAL = 'EBBS'
  AND ACCT.PROCESS_ID_VAL IN ('ACCT-EBBS-ACCOUNT_IN', 'ACCT-EBBS-PMMKDEAL_IN')
  AND ACCT.ODS_VAL = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN {{ source('sri_open_schema', 'prty') }} AS PRTY_SP_TPCLIENT
  ON PRTY_SP_TPCLIENT.PRTY_ID = ACCT.PRTY_ID
  AND PRTY_SP_TPCLIENT.SRC_SYS = 'SCI'
  AND PRTY_SP_TPCLIENT.PRTY_CAT_CD = 'SubProfile'
  AND PRTY_SP_TPCLIENT.PROCESS_ID_VAL = 'PRTY-SCI-SUBPROF'
  AND PRTY_SP_TPCLIENT.ODS_VAL = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN {{ source('sri_open_schema', 'chrt_of_acct') }} AS COA
  ON SL.GL_CUST_CLAS_CD = COA.CHRT_FLD_ID
  AND COA.ODS_VAL = SL.ODS_VAL
  AND COA.PROCESS_ID_VAL = 'CHRT_OF_ACCT-RDM-PGCMST_CUSTCLS'
  AND COA.ODS_VAL = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN (
  SELECT
    PGC.*,
    CHRT_FLD_CAT_CD LIKE '%P/L%',
    CASE WHEN CHRT_FLD_CAT_CD LIKE '%P/L%' THEN 'PNL' ELSE 'BS' END AS ACCT_CAT
  FROM {{ source('sri_open_schema', 'chrt_of_acct') }} AS PGC
  WHERE
    PGC.ODS_VAL = '{{ var('__ods_val__') }}' AND PROCESS_ID_VAL = 'CHRT_OF_ACCT-RDM-PGCMST_ACCT'
) AS PGC
  ON SL.GL_ACCT_CD = PGC.CHRT_FLD_ID AND PGC.ODS_VAL = SL.ODS_VAL
LEFT OUTER JOIN {{ source('sri_open_schema', 'm_ifrs9_acct_class_xlate') }} AS ACCTCLASS
  ON SL.GL_ACCT_CD = ACCTCLASS.PSGLACCOUNTFROM
  AND SL.GL_BIZ_UNIT_CD = ACCTCLASS.PSGLBU
  AND SL.GL_PRD_CD = ACCTCLASS.PSGLPRODUCTFROM
  AND SL.GL_DEPT_CD = ACCTCLASS.PSGLDEPTFROM
  AND ACCTCLASS.ODS = SL.ODS_VAL
  AND ACCTCLASS.ODS = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN (
  SELECT DISTINCT
    derived_adm_tp_source,
    derived_adm_jrnl_src,
    ods
  FROM {{ source('sri_open_schema', 'm_psgl_src_lsdr_src_sys_xlate') }} AS m_psgl_src_lsdr_src_sys_xlate
  WHERE
    ODS = '{{ var('__ods_val__') }}'
) AS JRNLSRC
  ON SL.SRC_SYS = JRNLSRC.DERIVED_ADM_TP_SOURCE
  AND JRNLSRC.ODS = SL.ODS_VAL
  AND JRNLSRC.ODS = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN {{ source('sri_open_schema', 'm_gl_acct_amt_grp') }} AS GL
  ON SL.GL_ACCT_CD = GL.ACCT AND GL.ODS = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN {{ source('sri_open_schema', 'm_cdl_glbu_to_entcd_bkcd_xlate') }} AS G
  ON g.GL_BU_CD = SL.GL_BIZ_UNIT_CD
  AND G.SRC_SYS = 'PSGL'
  AND G.CTY = 'XX'
  AND G.ods = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN {{ source('sri_open_schema', 'acct_bal') }} AS ACCT_BAL
  ON ACCT_BAL.ACCT_ID = SL.SUBL_ID
  AND ACCT_BAL.country_val = SL.country_val
  AND ACCT_BAL.SRC_SYS = 'EBBS'
  AND ACCT_BAL.TP_SYS_VAL = 'EBBS'
  AND ACCT_BAL.PROCESS_ID_VAL IN ('ACCT_BAL-EBBS-ACCOUNT_IN', 'ACCT_BAL-EBBS-PMMKDEAL_IN')
  AND ACCT_BAL.ODS_VAL = '{{ var('__ods_val__') }}'
  AND SL.acct_sub_cat_nm = 'PCP'
LEFT OUTER JOIN {{ source('sri_open_schema', 'prvsn') }} AS prvsn
  ON PRVSN.PRVSN_ID = SL.SUBL_ID
  AND PRVSN.country_val = SL.country_val
  AND PRVSN.SRC_SYS = 'EBBS'
  AND PRVSN.TP_SYS_VAL = 'EBBS'
  AND PRVSN.PROCESS_ID_VAL = 'PRVSN-EBBS-CORP_CHOFF_IN'
  AND PRVSN.ODS_VAL = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN {{ source('sri_open_schema', 'prty') }} AS PRTY_MST
  ON ACCT.CP_ID = PRTY_MST.PRTY_ID
  AND PRTY_MST.TP_SYS_VAL = 'EBBS'
  AND PRTY_MST.PROCESS_ID_VAL = 'PRTY-EBBS-MAST_IN'
  AND ACCT.PROCESS_ID_VAL IN ('ACCT-EBBS-ACCOUNT_IN', 'ACCT-EBBS-PMMKDEAL_IN')
  AND PRTY_MST.ODS_VAL = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN {{ source('sri_open_schema', 'prty_rtng') }} AS PRTY_RTNG
  ON SUBSTRING(ACCT.PRTY_ID, 1, 8) = PRTY_RTNG.PRTY_ID
  AND PRTY_RTNG.process_id_val = 'PRTY_RTNG-SCI-LMPCRG'
  AND PRTY_RTNG.prty_cr_risk_rtng_type = 'INTERNAL'
  AND PRTY_RTNG.ods_val = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN {{ source('sri_open_schema', 'prty_rtng') }} AS PRTY_RTNG_TP
  ON ACCT.CP_ID = PRTY_RTNG_TP.PRTY_ID
  AND PRTY_RTNG_TP.process_id_val = 'PRTY_RTNG-EBBS-MASTCRG'
  AND ACCT.PROCESS_ID_VAL IN ('ACCT-EBBS-ACCOUNT_IN', 'ACCT-EBBS-PMMKDEAL_IN')
  AND PRTY_RTNG_TP.prty_cr_risk_rtng_type = 'INTERNAL'
  AND PRTY_RTNG_TP.ods_val = '{{ var('__ods_val__') }}'
  AND ACCT.ODS_VAL = '{{ var('__ods_val__') }}'
WHERE
  SL.ODS_VAL = '{{ var('__ods_val__') }}'
  AND SL.SRC_SYS = 'EBBS'
  AND SUBSTRING(SL.GL_ACCT_CD, 1, 1) <> '9'
  AND PGC.ACCT_CAT <> 'PNL'
 