    
{{ config(
    alias='prty',
    materialized='table'
) }}

 -- 

 SELECT
  TRIM(CAST(EBBS_MAST.MASTERNO AS STRING)) AS PRTY_ID,
  'EBBS' AS SRC_SYS,
  COALESCE(EBBS_MAST.COUNTRY, '') AS CTRY_CD,
  EBBS_MAST.ods AS STRT_DT,
  '9999-12-31' AS END_DT,
  EBBS_MAST.ACCTTYPE AS PRTY_BIZ_TYPE_CD,
  NULL AS PRTY_CLTR_PLDG_RL_CD,
  COALESCE(EBBS_MAST.ULTIMATECNTRYCODE, '') AS PRTY_INC_CTRY_CD,
  '' AS PRTY_CR_RISK_RESP_CTRY_CD,
  NULL AS PRTY_CR_TEAM_CD,
  NULL AS DATA_SHR_CNST_FLG,
  'Master' AS FILE_TYPE,
  EBBS_MAST.REVIEWDATE AS PRTY_APPR_RVW_DT,
  NULL AS PRTY_FM_INDUSTRY_CD,
  NULL AS PRTY_GBL_RTNG_FLG,
  NULL AS GUARANTEED_BY_PRNT_FLG,
  NULL AS PRTY_HUB_LOC,
  NULL AS PRTY_IFRS_CP_TYPE_CD,
  NULL AS PRTY_LANG_CD,
  NULL AS PRTY_PRNT_SUPT_ELGT_CD,
  EBBS_MAST.AFFILIATEDCODE AS PRTY_AFFL_CD,
  NULL AS PRTY_ANNL_SALES_AMT,
  NULL AS PRTY_ANNL_SALES_AMT_CCY,
  NULL AS PRTY_ANNL_INCOME_AMT,
  NULL AS PRTY_ANNL_INCOME_UPDT_DT,
  NULL AS PRTY_BKRPT_DT,
  NULL AS PRTY_BKRPT_FLG,
  NULL AS PRTY_BSL_SGMT_CD,
  NULL AS PRTY_BSL_SUB_SGMT_CD,
  NULL AS PRTY_BENEF_CP_CD,
  NULL AS PRTY_BIRTH_DT,
  NULL AS PRTY_BORROW_EXCP_FLG,
  'MasterNumber' AS PRTY_CAT_CD,
  NULL AS PRTY_CR_RISK_LOC_CD,
  NULL AS PRTY_CR_STS_CD,
  NULL AS PRTY_CRM_REF_NUM,
  NULL AS PRTY_DECSD_DT,
  NULL AS PRTY_DECSD_FLG,
  NULL AS PRTY_DCLR_INCOME_AMT,
  NULL AS PRTY_DLFT_CR_GRD_FLG,
  NULL AS PRTY_DLNQ_STRT_DT,
  NULL AS PRTY_DEPN_CNT,
  NULL AS PRTY_DESG_CD,
  NULL AS PRTY_DSCL_AGMT_EFF_DT,
  NULL AS PRTY_DSCL_AGMT_FLG,
  EBBS_MAST.residencyclscode AS PRTY_DMCL_CTRY_CD,
  NULL AS PRTY_ED_LVL_CD,
  NULL AS PRTY_ELIG_FLG,
  NULL AS PRTY_EMPLR_NM,
  NULL AS PRTY_ENV_SR_GRD_CD,
  NULL AS PRTY_FIN_INST_CD,
  NULL AS PRTY_FM_CD,
  NULL AS PRTY_FSA_RPT_CLNT_CD,
  NULL AS PRTY_GNDR_CD,
  NULL AS PRTY_INC_DT,
  NULL AS PRTY_INC_NUM,
  EBBS_MAST.INSTITUTIONALCODE AS PRTY_INST_CLAS_CD,
  NULL AS PRTY_INST_SCTR_CD,
  EBBS_MAST.ISICCODE AS PRTY_ISIC_CD,
  NULL AS PRTY_ISIC_CD_STRT_DT,
  NULL AS PRTY_ISIC_CD_WGHT,
  NULL AS PRTY_ISIC_TYPE,
  NULL AS PRTY_LGL_CONT_TYPE_CD,
  NULL AS PRTY_LGL_NM,
  NULL AS PRTY_LONG_NM,
  NULL AS PRTY_MRTL_STS,
  NULL AS PRTY_MODE_OF_SAL,
  NULL AS PRTY_MTH_ALLW_AMT,
  NULL AS PRTY_MTH_BSC_SAL_AMT,
  NULL AS PRTY_MTH_COMS_AMT,
  '' AS PRTY_NTLTY_CTRY_CD,
  NULL AS PRTY_NATR_OF_BIZ,
  NULL AS PRTY_NET_WRTH_AMT,
  NULL AS PRTY_NEW_SGMT_CD,
  NULL AS PRTY_OCCP_CD,
  EBBS_MAST.CUSTTYPECODE AS PRTY_ORG_TYPE_CD,
  NULL AS PRTY_OTH_BANK_CR_LMT_AMT,
  NULL AS PRTY_OTH_BANK_MTH_ILA_AMT,
  NULL AS PRTY_OTH_MTH_INCOME_AMT,
  NULL AS PRTY_POS_TITL,
  NULL AS PRTY_PRIME_BKR_FLG,
  NULL AS PRTY_PRFSN_CD,
  EBBS_MAST.CLOSINGDATE AS PRTY_RL_END_DT,
  NULL AS PRTY_RL_INFO_VAL,
  EBBS_MAST.ARMCODE AS PRTY_ARM_CD,
  EBBS_MAST.MASTEROPENDATE AS PRTY_RL_STRT_DT,
  COALESCE(EBBS_MAST.RESIDENCYCLSCODE, '') AS PRTY_RSDN_CTRY_CD,
  EBBS_MAST.RESIDENTSTATUS AS PRTY_RSDNL_STS_CD,
  NULL AS PRTY_SALES_TURN_OVR_AMT,
  NULL AS PRTY_SALES_TURN_OVR_CCY,
  NULL AS PRTY_SCB_STAF_TYPE,
  EBBS_MAST.SEGMENTCODE AS PRTY_SGMT_CD,
  EBBS_MAST.SHORTNAME AS PRTY_SHORT_NM,
  NULL AS PRTY_STS_EFF_DT,
  NULL AS PRTY_STS_CD,
  EBBS_MAST.CUSTSEGMTCODE AS PRTY_SUB_SGMT_CD,
  NULL AS PRTY_TOT_WORK_EXPNC,
  'Master' AS PRTY_TYPE_CD,
  NULL AS PRTY_SCB_CLAS_CD,
  NULL AS PRTY_SCB_ENT_FLG,
  NULL AS PRTY_SRC_PLDG_ID,
  NULL AS TOP_1000_BANK_IND,
  NULL AS PRTY_CFTC_CRCC_FLG,
  EBBS_SEG.CORPORATEFLAG AS PRTY_CORP_FLG,
  EBBS_SEG.BFSFLAG AS PRTY_SME_FLG,
  COALESCE(EBBS_MAST.COUNTRY, '') AS BKG_CTRY_CD,
  NULL AS COIN_NUM,
  NULL AS SALN_CD,
  NULL AS STAF_ID,
  EBBS_INSTCLS.ISSTAFFCLASS AS STAF_FLG,
  NULL AS MAND_CLRG_FLG,
  NULL AS PRTY_OPT_OUT_ANNL_FIL_FLG,
  NULL AS DF_PTCOL_2_SIDE_LTR_FLG,
  NULL AS PRTY_EUE_NOTC_FLG,
  NULL AS DF_PTCOL_2_SIDE_COMPL_FLG,
  NULL AS DF_ENT_CD,
  NULL AS SPL_ENT_FLG,
  NULL AS SPL_ENT_SUB_CAT,
  NULL AS QIR_FLG,
  NULL AS US_DMCL_FLG,
  NULL AS DF_ENT_SUB_TYPE,
  NULL AS FIN_ENT_EXCP_FLG,
  NULL AS INDUSTRY_RISK_CLAS_CD,
  NULL AS DF_COMPL_FLG,
  NULL AS ELIG_CONTR_PARTP_FLG,
  NULL AS INIT_MGRN_METH_CD,
  '' AS DF_CTRY_CD,
  NULL AS EXTR_PRTY_ID,
  NULL AS PRTY_LGL_CONT_TYPE_DESC,
  NULL AS ETHNC_CD,
  NULL AS OWN_CD,
  EBBS_MAST.CHECKERDATE AS PRTY_LAST_MOD_DT,
  EBBS_MAST.CHECKERTIME AS PRTY_LAST_MOD_TM,
  EBBS_SEG.NAME AS PRTY_SGMT_DESC,
  EBBS_ARM.NAME AS PRTY_ARM_DESC,
  EBBS_MSTINFO_BNM.INFODETCODE AS PRTY_BNM_RSDNL_CD,
  NULL AS ODS
FROM {{ source('sri_open_schema', 'ebbs_in_mast') }} AS ebbs_mast
LEFT OUTER JOIN {{ source('sri_open_schema', 'ebbs_in_instcls') }} AS EBBS_INSTCLS
  ON EBBS_MAST.INSTCLASSCODE = EBBS_INSTCLS.INSTCLASSCODE
  AND EBBS_MAST.ods = EBBS_INSTCLS.ods
  AND EBBS_INSTCLS.ODS = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN {{ source('sri_open_schema', 'ebbs_in_seg') }} AS EBBS_SEG
  ON EBBS_MAST.SEGMENTCODE = EBBS_SEG.SEGMENTCODE
  AND EBBS_MAST.ods = EBBS_SEG.ods
  AND EBBS_SEG.ods = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN {{ source('sri_open_schema', 'ebbs_in_arm') }} AS EBBS_ARM
  ON EBBS_MAST.ARMCODE = EBBS_ARM.ARMCODE
  AND EBBS_MAST.ods = EBBS_ARM.ods
  AND EBBS_ARM.ods = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN (
  SELECT
    a.SEQNO,
    a.INFORMATIONCODE,
    a.referenceno,
    a.INFODETCODE,
    a.ods
  FROM (
    SELECT
      SEQNO,
      INFORMATIONCODE,
      referenceno,
      INFODETCODE,
      ods
    FROM {{ source('sri_open_schema', 'ebbs_in_mstinfo') }} AS ebbs_mstinfo
    WHERE
      ods = '{{ var('__ods_val__') }}'
  ) AS a
  JOIN (
    SELECT
      MAX(SEQNO) AS SEQNO,
      INFORMATIONCODE,
      referenceno
    FROM {{ source('sri_open_schema', 'ebbs_in_mstinfo') }} AS ebbs_mstinfo
    WHERE
      INFORMATIONCODE IN ('BNR') AND ods = '{{ var('__ods_val__') }}'
    GROUP BY
      INFORMATIONCODE,
      referenceno
  ) AS b
    ON a.SEQNO = b.SEQNO
    AND a.INFORMATIONCODE = b.INFORMATIONCODE
    AND a.referenceno = b.referenceno
) AS EBBS_MSTINFO_BNM
  ON TRIM(EBBS_MSTINFO_BNM.REFERENCENO) = TRIM(EBBS_MAST.MASTERNO)
  AND EBBS_MSTINFO_BNM.ods = EBBS_MAST.ods
  AND EBBS_MSTINFO_BNM.ODS = '{{ var('__ods_val__') }}'
WHERE
  EBBS_MAST.ODS = '{{ var('__ods_val__') }}'
 