    
{{ config(
    alias='acct1',
    materialized='table'
) }}

 -- 

 SELECT
  CONCAT(EBBS_ACCOUNT.CURRENCYCODE, '-', TRIM(EBBS_ACCOUNT.ACCOUNTNO)) AS ACCT_ID,
  EBBS_ACCOUNT.CURRENCYCODE AS ACCT_CCY,
  CONCAT(EBBS_ACCOUNT.CURRENCYCODE, TRIM(EBBS_ACCOUNT.ACCOUNTNO)) AS ACCT_REF_ID,
  EBBS_ACCOUNT.COUNTRY AS CTRY_CD,
  '9999-12-31' AS END_DT,
  EBBS_ACCOUNT.ods AS STRT_DT,
  'EBBS' AS SRC_SYS,
  'Account' AS ACCT_CAT_CD,
  EBBS_ACCOUNT.ACCLOSEDT AS ACCT_CLSE_DT,
  EBBS_ACCOUNT.ACCLOSUREREASON AS ACCT_CLSR_RSN,
  EBBS_ACCOUNT.CRINTINDFLAG AS ACCT_CR_INT_ACR_FLG,
  EBBS_ACCOUNT.DRINTINDFLAG AS ACCT_DR_INT_ACRL_FLG,
  EBBS_ACCOUNT.TRANSTODORMANTDATE AS ACCT_DRMT_DT,
  EBBS_ACCOUNT.FROZENSURRENDER AS ACCT_FRZN_CD,
  EBBS_ACCOUNT.CACSIND AS ACCT_IN_COL_FLG,
  'F' AS ACCT_INT_TYPE_CD,
  EBBS_ACCOUNT.CRINTCURRENCYCODE AS ACCT_INT_ACC_CCY,
  EBBS_ACCOUNT.LASTCRTRNEXCLSYSAMT AS ACCT_LAST_CR_TRAN_AMT,
  EBBS_ACCOUNT.LASTDRTRNEXCLSYSAMT AS ACCT_LAST_DR_TRAN_AMT,
  EBBS_EXCRTL.EXCESSSHRTAMT AS ACCT_LAST_EXCES_TRAN_AMT,
  EBBS_ACCOUNT.ACOPENDATE AS ACCT_OPEN_DT,
  EBBS_ACCOUNT.ACCOUNTBRANCH AS ACCT_OPEN_BR_CD,
  CASE
    WHEN EBBS_INTPL.REFNO <> 'NULL'
    THEN 'P'
    WHEN EBBS_INTPLDT.REFNO <> 'NULL'
    THEN 'C'
    ELSE ''
  END AS ACCT_POOL_FLG,
  COALESCE(EBBS_INTPLDT.REFNO, EBBS_INTPL.REFNO, '') AS ACCT_POOL_ID,
  EBBS_ACCOUNT.LASTCRTRNDATE AS ACCT_PREV_CR_TRAN_DT,
  EBBS_ACCOUNT.LASTDRTRNDATE AS ACCT_PREV_DR_TRAN_DT,
  EBBS_ACCOUNT.ACREOPENDT AS ACCT_REACTIVATED_DT,
  EBBS_ACCOUNT.SHORTNAME AS ACCT_SHORT_NM,
  EBBS_ACCOUNT.ACCTITLE2 AS ACCT_STMT_ADD_TITL,
  EBBS_ACCOUNT.ACCTCURRENTSTATUS AS ACCT_STS_CD,
  EBBS_ACCOUNT.TRANSTOUNCLAIMDATE AS ACCT_UNCLAIM_DT,
  EBBS_ACCOUNT.CRLASTACCADJAMOUNT AS ACR_INT_ADJ_AMT,
  NULL AS AMORT_FLG,
  NULL AS AMORT_TYPE,
  NULL AS ANCHOR_ID,
  NULL AS ANCHOR_NM,
  EBBS_ACCOUNT.CHECKERDATE AS AUTH_DT,
  NULL AS BASE_TENR,
  NULL AS BNF_CUST_NM,
  G.COMP_CD AS BK_CD,
  EBBS_ACCOUNT.COUNTRY AS BKG_CTRY_CD,
  scbentityxlate.sci_entity_code AS BKG_LOC_CD,
  NULL AS CAP_RELIEF,
  TRIM(CAST(EBBS_ACCOUNT.MASTERNO AS STRING)) AS CP_ID,
  EBBS_INTCURR.CRINTCHARGEBASIS AS CR_INT_ACR_BSIS_CD,
  EBBS_ACCOUNT.CRLASTACCADJAMOUNT AS CR_INT_ADJ_ACR_AMT,
  EBBS_ACCOUNT.CRINTACCRUEDAMT AS CR_INT_LAST_ACR_AMT,
  EBBS_ACINTHIS_C.INTPAIDDATE AS CR_INT_LAST_PYMT_DT,
  CASE
    WHEN EBBS_ACINTHIS_C.CREDITDEBIT = 'C'
    THEN EBBS_ACINTHIS_C.TOTAL_INT_PD
    ELSE ''
  END AS CR_INT_LAST_PYMT_AMT,
  EBBS_INTCURR.CRINTPAYFREQ AS CR_INT_PYMT_FREQ,
  EBBS_ACCOUNT.CRINTPRODUCTCODE AS CR_INT_PRD_CD,
  NULL AS CR_PROT_OS_FIN_AMT,
  NULL AS CROSS_CCY_DEAL_FLG,
  NULL AS CURR_INT_COL_OPT,
  NULL AS CURR_INT_PYMT_FRQ,
  NULL AS CURV_FLG,
  EBBS_ACCOUNT.INTINSUSPENSE AS CUST_ACCT_INT_IN_SUSP_FLG,
  NULL AS CUST_DEP_TYPE_CD,
  NULL AS CUST_DEP_VAL_DT,
  NULL AS CUST_INT_BASE_RT,
  NULL AS CUST_MRGN_RT,
  NULL AS CUST_MRGN_RT_FLG,
  NULL AS NXT_MATURITY_DT,
  CONCAT('EBBS', '-', EBBS_ACCOUNT.COUNTRY) AS DATA_SRC,
  NULL AS DAY_CNT_CONV_CD,
  DATEDIFF(TO_DATE(EBBS_EXCRTL.ODS), TO_DATE(EBBS_EXCRTL.LASTEXCESSUPDATEDDATE)) AS DAYS_PAST_DUE,
  EBBS_ACCOUNT.DSRCLOSINGID AS DEAL_CLSE_DSR_ID,
  NULL AS DEAL_LIEN_AMT,
  NULL AS DEAL_MATCH_FLG,
  NULL AS DEAL_REPR_STRT_DT,
  NULL AS DEAL_ROLL_OVER_CNT,
  NULL AS DEAL_SRC_DSR_ID,
  NULL AS DEAL_TERM_AMT,
  NULL AS DEAL_TERM_TYPE,
  NULL AS DEAL_TRSRY_RT,
  EBBS_INTCURR.DRINTCHARGEBASIS AS DR_INT_ACR_BSIS_CD,
  EBBS_INTCURR.DRBANDPROGREG AS DR_INT_BAND_METH,
  EBBS_ACCOUNT.DRINTACCRUEDAMT AS DR_INT_LAST_ACR_AMT,
  EBBS_ACCOUNT.CRNEXTINTPAYDATE AS CR_INT_NXT_PYMT_DT,
  EBBS_ACINTHIS_D.INTPAIDDATE AS DR_INT_LAST_PYMT_DT,
  NULL AS DR_INT_PYMT_FREQ,
  NULL AS DR_INT_ADJ_ACR_AMT,
  EBBS_ACCOUNT.DRINTPRODUCTCODE AS DR_INT_PRD_CD,
  NULL AS DISAPPROVED_PERIOD,
  CASE
    WHEN EBBS_ACCINFO_FOL.informationcode = 'FOL'
    THEN EBBS_ACCINFO_FOL.INFODETCODE
    ELSE ''
  END AS FAC_ORIG_LOC,
  'Account' AS FILE_TYPE,
  EBBS_ACCOUNT.ACOPENDATE AS FST_LN_DRWDOWN_DT,
  NULL AS FIX_PERIOD,
  NULL AS FRT_ON_LAND_CD,
  NULL AS FTP_BASE_RT,
  NULL AS FTP_BE_LIQ_PRIM_RT,
  NULL AS FTP_CONTR_LIQ_PRIM_RT,
  NULL AS FTP_COST_OF_LIQ_RT,
  NULL AS FTP_CTRY_COST_OF_LIQ_RT,
  NULL AS FTP_INCT_PRIM_RT,
  NULL AS FTP_LIQ_PRIM_RT_DT,
  NULL AS FTP_LIQ_PRIM_TENR,
  NULL AS FTP_RT_DT,
  NULL AS FUND_PL_MATURITY_DT,
  EBBS_ACCOUNT.TRANPRICINGRATE AS FTP_RT,
  NULL AS INT_ACR_UP_TO_DT,
  NULL AS INT_ACR_AMT,
  NULL AS INT_BAND_BRKP,
  NULL AS INT_BASE_RT_MULT,
  NULL AS INT_BASE_RT_TYPE,
  NULL AS INT_CALC_DAY_CONV,
  NULL AS INT_ONLY_FLG,
  NULL AS INT_PYMT_DAY_CONV,
  NULL AS INT_PYMT_DUE_DT,
  (
    COALESCE(EBBS_INTDTL.CRINTRATE, 0) - COALESCE(EBBS_INTDTL.DRINTRATE, 0) - COALESCE(EBBS_INTDTL.EXCESSINTRATE, 0)
  ) AS INT_RT,
  EBBS_INTCURR.EFFECTIVEDATE AS INT_RT_EFF_DT,
  'Fixed' AS INT_RT_TYPE,
  NULL AS INT_REPYMT_FREQ,
  NULL AS INT_PYMT_STRT_DT,
  NULL AS ISLM_ACCT_FLG,
  NULL AS ISLM_SUB_PRD,
  EBBS_ACCOUNT.LASTCRINTRATE AS LAST_CR_INT_RT,
  EBBS_ACCOUNT.LASTCRTRNEXCLSYSDT AS LAST_CUST_INIT_CR_TRAN_DT,
  EBBS_ACCOUNT.LASTDRTRNEXCLSYSDT AS LAST_CUST_INIT_DR_TRAN_DT,
  EBBS_ACCOUNT.LASTDRINTRATE AS LAST_DR_INT_RT,
  EBBS_EXCRTL.EXCESSSHRTAMT AS LAST_EXCES_AMT,
  EBBS_EXCRTL.LASTEXCESSUPDATEDDATE AS LAST_EXCES_DT,
  NULL AS LAST_INT_PYMT_DT,
  NULL AS LAST_INT_REPR_DT,
  scbentityxlate.sci_entity_code AS LGL_ENT_CD,
  scbentityxlate.sci_bkg_loctn_id AS LGL_ENT_ID,
  NULL AS LIBR_DIBR_FLG,
  EBBS_ACCOUNT.ACCTCURRENTSTATUS AS LIFCYCL_STS_CD,
  EBBS_ACCOUNT.ACCLASSCODE AS LN_CLAS,
  EBBS_ACCOUNT.ACOPENDATE AS LN_EFF_DT,
  NULL AS LN_TENR_IN_DAYS,
  EBBS_ACCOUNT.PRODUCTCODE AS LOCAL_PRD_CD,
  EBBS_ACCOUNT.LASTPRDCHANGEDT AS LOCAL_PRD_CD_CHG_DT,
  EBBS_ACCOUNT.MATURITYDATE AS MATURITY_DT,
  NULL AS MATURITY_INT_AMT,
  NULL AS MAX_TENR,
  NULL AS NXT_INT_PYMT_DT,
  NULL AS NXT_INT_REPR_DT,
  NULL AS NXT_PYMT_DT,
  CASE WHEN EBBS_ACCINFO_NOSTRO.informationcode = 'TLM' THEN 'Y' ELSE '' END AS NOST_SUSP_FLG,
  NULL AS OBL_FLG,
  NULL AS ORIG_MATURTY_DT,
  NULL AS ORIG_TERM_TYPE,
  NULL AS ORIG_PRIN_AMT,
  EBBS_MLTMAST.LMTPRVPRDCD AS OVR_DFT_TYPE,
  EBBS_PRVINFO.IMPAIRMENT AS PAST_DUE_FLG,
  NULL AS PAST_DUE_INT_COL_OPT,
  NULL AS PAST_DUE_INT_PYMT_FREQ,
  NULL AS PNLTY_AMT,
  NULL AS PNLTY_CHRG_FLG,
  NULL AS PRE_PYMT_RT,
  EBBS_ACCOUNT.OLDPRODUCTCODE AS PREV_LOCAL_PRD_CD,
  NULL AS PRIN_PYMT_FREQ,
  NULL AS PRG_CD,
  EBBS_PRVINFO.PRVPRDCD AS PRVSN_PRD_CD,
  NULL AS PRPS_CD,
  NULL AS REPR_DT,
  NULL AS RECRSE_FLG,
  NULL AS REG_INT_COL_OPT,
  NULL AS RISK_PRTY_ID,
  NULL AS ROLL_OVER_FLG,
  NULL AS ROLL_OVER_INT_CAP_FLG,
  NULL AS RLOVR_ORIG_INT_RT_FLG,
  NULL AS SCTY_TYPE_CD,
  NULL AS SEL_DOWN_FLG,
  NULL AS SETLM_DT,
  TRIM(CAST(EBBS_MASTREL.RELATIONSHIPNO AS STRING)) AS SRC_CUST_ID,
  m_product_xlate.basel_prod_code AS STD_PRD_CD,
  NULL AS STRUC_NM,
  NULL AS STRUC_TRD_FLG,
  NULL AS STRUC_TRD_SUB_TYPE,
  NULL AS STRUC_TRD_TYPE,
  NULL AS SUST_TRD_FIN_FLG,
  EBBS_PRVINFO.TOTALCHARGEOFFAMT AS TOT_CHRG_OFF_AMT,
  NULL AS TP_ENT_NM,
  NULL AS ULT_RISK_CTRY,
  EBBS_ACCOUNT.TRANSTOUNCLAIMDATE AS UNCLAIM_DT,
  NULL AS UWRT_TYPE,
  CASE WHEN EBBS_ACCINFO_VOSTRO.informationcode = 'TM3' THEN 'Y' ELSE '' END AS VOST_FLG,
  EBBS_ACCOUNT.WAIVEEXCINT AS WAIVE_EXCES_INT_FLG,
  NULL AS INT_RT_BSIS_CD,
  NULL AS NON_CR_PROT_OS_FIN_AMT,
  NULL AS INT_PYMT_FREQ,
  NULL AS TRD_FIN_TYPE,
  NULL AS TRUE_SALES_FLG,
  EBBS_BRN.NAME AS ACCT_BR_NM,
  NULL AS ACTG_METH_CD,
  NULL AS FST_INT_PYMT_DT,
  NULL AS FST_PRIN_PYMT_DT,
  EBBS_PRVINFO.IISDATE AS INT_PAST_DUE_DT,
  EBBS_ACCOUNT.CURRENCYCODE AS LOCAL_CCY,
  NULL AS LOCAL_CCY_FX_RT,
  NULL AS PRIN_PAST_DUE_DT,
  NULL AS PTFOL_ID,
  NULL AS PTFOL_NM,
  NULL AS RESV_RT,
  NULL AS RMNG_TENR,
  NULL AS LPC_GRP_CD,
  NULL AS LPC_TYPE,
  NULL AS OS_INVC_DT,
  NULL AS TP_BIZ_GRP_CD,
  EBBS_ACCOUNT.SEGMENTCODE AS TP_BIZ_SGMT_CD,
  NULL AS TP_BIZ_SUB_SGMT_CD,
  NULL AS TP_BIZ_UNIT_CD,
  NULL AS ACCT_STS_DESC,
  NULL AS FAC_ORIG_LOC_DESC,
  NULL AS INT_PYMT_FREQ_DESC,
  NULL AS INT_RT_TYPE_DESC,
  NULL AS LN_CLAS_DESC,
  EBBS_PRD.DESCRIPTION AS LOCAL_PRD_DESC,
  NULL AS PRIN_PYMT_FREQ_DESC,
  NULL AS PRPS_DESC,
  NULL AS LPC_GRP_DESC,
  NULL AS LPC_TYPE_DESC,
  NULL AS REPRC_FREQ,
  NULL AS REPRC_FREQ_DESC,
  NULL AS STRUC_TYPE,
  NULL AS STRUC_TYPE_DESC,
  NULL AS RLOVR_WAIT_PERIOD,
  NULL AS TRNCH_ID,
  NULL AS CARD_BLK_CD,
  NULL AS CASH_ADVN_INT_RT,
  NULL AS CR_CARD_TYPE_CD,
  NULL AS AVAIL_CR_AMT,
  NULL AS CR_CARD_USR_CD,
  NULL AS ACCT_STM_CYC_DAY,
  EBBS_ACCOUNT.CHECKERDATE AS ACCT_LAST_MOD_DT,
  EBBS_ACCOUNT.CHECKERTIME AS ACCT_LAST_MOD_TM,
  EBBS_SEG.CORPORATEFLAG AS ACCT_CORP_FLG,
  EBBS_SEG.BFSFLAG AS ACCT_SME_FLG,
  EBBS_ACCOUNT.crintadjamt AS CR_INT_ADJ_AMT,
  EBBS_ACCOUNT.drintadjamt AS DR_INT_ADJ_AMT,
  EBBS_ACCOUNT.crmanualadjamt AS CR_INT_MAN_ADJ_AMT,
  EBBS_ACCOUNT.drmanualadjamt AS DR_INT_MAN_ADJ_AMT,
  EBBS_ACCOUNT.ATMFLAG AS ATM_FLG,
  NULL AS prd_cd_desc,
  EBBS_PRD.splprdflag AS SPL_PRD_FLG,
  EBBS_REASON.DESCRIPTION AS ACCT_CLSR_RSN_DESC,
  CASE
    WHEN EBBS_ACINTHIS_D.CREDITDEBIT = 'D'
    THEN EBBS_ACINTHIS_D.TOTAL_INT_PD
    ELSE ''
  END AS DR_INT_LAST_PYMT_AMT,
  EBBS_ACCOUNT.DRNEXTINTPAYDATE AS DR_INT_NXT_PYMT_DT,
  NULL AS DR_INT_NXT_PYMT_AMT,
  NULL AS CR_INT_NXT_PYMT_AMT,
  COALESCE(EBBS_INTDTL.EXCESSINTRATE, 0) AS EXCES_DR_INT_RT,
  PRTY_SP_SCI.PRTY_ID AS PRTY_ID,
  CASE
    WHEN EBBS_ACCOUNT.ACCTCURRENTSTATUS = 'O'
    THEN EBBS_ACCOUNT.ACOPENDATE
    WHEN EBBS_ACCOUNT.ACCTCURRENTSTATUS = 'D'
    THEN EBBS_ACCOUNT.TRANSTODORMANTDATE
    WHEN EBBS_ACCOUNT.ACCTCURRENTSTATUS = 'U'
    THEN EBBS_ACCOUNT.TRANSTOUNCLAIMDATE
    WHEN EBBS_ACCOUNT.ACCTCURRENTSTATUS = 'C'
    THEN EBBS_ACCOUNT.ACCLOSEDT
    WHEN EBBS_ACCOUNT.ACCTCURRENTSTATUS = 'A'
    THEN EBBS_ACCOUNT.ACREOPENDT
    ELSE NULL
  END AS LIFCYCL_STS_DT,
  EBBS_ACCOUNT.ODS AS ODS
FROM {{ source('sri_open_schema', 'ebbs_in_account') }} AS ebbs_account
LEFT OUTER JOIN {{ source('sri_open_schema', 'ebbs_in_excrtl') }} AS EBBS_EXCRTL
  ON EBBS_EXCRTL.CURRENCYCODE = EBBS_ACCOUNT.CURRENCYCODE
  AND EBBS_EXCRTL.ACCOUNTNO = EBBS_ACCOUNT.ACCOUNTNO
  AND EBBS_EXCRTL.ODS = EBBS_ACCOUNT.ODS
  AND EBBS_EXCRTL.EXCESSSHRTAMT > 0
  AND EBBS_EXCRTL.ods = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN {{ source('sri_open_schema', 'ebbs_in_intpl') }} AS EBBS_INTPL
  ON EBBS_INTPL.LEADERCURRENCYCODE = EBBS_ACCOUNT.CURRENCYCODE
  AND EBBS_INTPL.LEADERACCOUNTNO = EBBS_ACCOUNT.ACCOUNTNO
  AND EBBS_INTPL.ODS = EBBS_ACCOUNT.ODS
  AND EBBS_INTPL.ods = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN {{ source('sri_open_schema', 'ebbs_in_intpldt') }} AS EBBS_INTPLDT
  ON EBBS_INTPLDT.CURRENCYCODE = EBBS_ACCOUNT.CURRENCYCODE
  AND EBBS_INTPLDT.ACCOUNTNO = EBBS_ACCOUNT.ACCOUNTNO
  AND EBBS_INTPLDT.ODS = EBBS_ACCOUNT.ODS
  AND EBBS_INTPLDT.ods = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN (
  SELECT
    a.CRINTCHARGEBASIS,
    a.CRINTPAYFREQ,
    a.DRINTCHARGEBASIS,
    a.DRBANDPROGREG,
    a.interestcode,
    a.CURRENCYCODE,
    a.EFFECTIVEDATE,
    a.ODS
  FROM (
    SELECT
      CRINTCHARGEBASIS,
      CRINTPAYFREQ,
      DRINTCHARGEBASIS,
      DRBANDPROGREG,
      interestcode,
      CURRENCYCODE,
      EFFECTIVEDATE,
      ODS
    FROM {{ source('sri_open_schema', 'ebbs_in_intcurr') }} AS ebbs_intcurr
    WHERE
      ODS = '{{ var('__ods_val__') }}'
  ) AS a
  JOIN (
    SELECT
      MAX(EFFECTIVEDATE) AS EFFECTIVEDATE,
      interestcode,
      CURRENCYCODE
    FROM {{ source('sri_open_schema', 'ebbs_in_intcurr') }} AS ebbs_intcurr
    WHERE
      ODS = '{{ var('__ods_val__') }}'
    GROUP BY
      interestcode,
      CURRENCYCODE
  ) AS b
    ON a.EFFECTIVEDATE = b.EFFECTIVEDATE
    AND a.interestcode = b.interestcode
    AND a.CURRENCYCODE = b.CURRENCYCODE
) AS EBBS_INTCURR
  ON EBBS_INTCURR.CURRENCYCODE = EBBS_ACCOUNT.CURRENCYCODE
  AND EBBS_INTCURR.INTERESTCODE = EBBS_ACCOUNT.INTERESTCODE
  AND EBBS_INTCURR.ODS = EBBS_ACCOUNT.ODS
  AND EBBS_INTCURR.ODS = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN {{ source('sri_open_schema', 'ebbs_in_prvinfo') }} AS EBBS_PRVINFO
  ON EBBS_PRVINFO.CURRENCYCODE = EBBS_ACCOUNT.CURRENCYCODE
  AND EBBS_PRVINFO.REFERENCENO = EBBS_ACCOUNT.ACCOUNTNO
  AND EBBS_PRVINFO.ODS = EBBS_ACCOUNT.ODS
  AND EBBS_PRVINFO.ods = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN {{ source('sri_open_schema', 'ebbs_in_intdtl') }} AS EBBS_INTDTL
  ON EBBS_INTDTL.CURRENCYCODE = EBBS_ACCOUNT.CURRENCYCODE
  AND EBBS_INTDTL.ACCOUNTNO = EBBS_ACCOUNT.ACCOUNTNO
  AND EBBS_INTDTL.accrualdate = EBBS_ACCOUNT.ODS
  AND EBBS_INTDTL.ods = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN (
  SELECT
    a.CURRENCYCODE,
    a.ACCOUNTNO,
    a.SEQNO,
    a.INFODETCODE,
    a.informationcode,
    a.ODS
  FROM (
    SELECT
      CURRENCYCODE,
      ACCOUNTNO,
      SEQNO,
      INFODETCODE,
      informationcode,
      ODS
    FROM {{ source('sri_open_schema', 'ebbs_in_accinfo') }} AS ebbs_accinfo
    WHERE
      ODS = '{{ var('__ods_val__') }}'
  ) AS a
  JOIN (
    SELECT
      MAX(SEQNO) AS SEQNO,
      INFORMATIONCODE,
      CURRENCYCODE,
      ACCOUNTNO
    FROM {{ source('sri_open_schema', 'ebbs_in_accinfo') }} AS ebbs_accinfo
    WHERE
      INFORMATIONCODE IN ('TLM') AND ODS = '{{ var('__ods_val__') }}'
    GROUP BY
      INFORMATIONCODE,
      CURRENCYCODE,
      ACCOUNTNO
  ) AS b
    ON a.SEQNO = b.SEQNO
    AND a.INFORMATIONCODE = b.INFORMATIONCODE
    AND a.CURRENCYCODE = b.CURRENCYCODE
    AND a.ACCOUNTNO = b.ACCOUNTNO
) AS EBBS_ACCINFO_NOSTRO
  ON EBBS_ACCINFO_NOSTRO.CURRENCYCODE = EBBS_ACCOUNT.CURRENCYCODE
  AND EBBS_ACCINFO_NOSTRO.ACCOUNTNO = EBBS_ACCOUNT.ACCOUNTNO
  AND EBBS_ACCINFO_NOSTRO.ODS = EBBS_ACCOUNT.ODS
  AND EBBS_ACCINFO_NOSTRO.ods = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN {{ source('sri_open_schema', 'ebbs_in_mltmast') }} AS EBBS_MLTMAST
  ON EBBS_MLTMAST.CURRENCYCODE = EBBS_ACCOUNT.CURRENCYCODE
  AND EBBS_MLTMAST.ACCOUNTNO = EBBS_ACCOUNT.ACCOUNTNO
  AND EBBS_MLTMAST.ODS = EBBS_ACCOUNT.ODS
  AND EBBS_MLTMAST.ods = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN (
  SELECT
    ODS,
    COUNTRY_CODE,
    SRC_PROD_CODE,
    BASEL_PROD_CODE,
    lcl_prod_desc,
    src_sys_short_name,
    ROW_NUMBER() OVER (PARTITION BY COUNTRY_CODE, SRC_PROD_CODE ORDER BY SRC_PROD_CODE) AS ROW_NUM
  FROM {{ source('sri_open_schema', 'm_product_xlate') }} AS m_product_xlate
  WHERE
    ods = '{{ var('__ods_val__') }}'
) AS m_product_xlate
  ON EBBS_ACCOUNT.PRODUCTCODE = m_product_xlate.src_prod_code
  AND m_product_xlate.src_sys_short_name = 'EBBS'
  AND m_product_xlate.country_code = EBBS_ACCOUNT.COUNTRY
  AND m_product_xlate.ODS = EBBS_ACCOUNT.ODS
  AND m_product_xlate.ROW_NUM = 1
LEFT OUTER JOIN {{ source('sri_open_schema', 'ebbs_in_brn') }} AS EBBS_BRN
  ON EBBS_BRN.BRANCHCODE = EBBS_ACCOUNT.ACCOUNTBRANCH
  AND EBBS_BRN.ODS = EBBS_ACCOUNT.ODS
  AND EBBS_BRN.ods = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN (
  SELECT
    COUNTRY,
    ODS,
    masterno,
    Relationshipno,
    primaryflag,
    ROW_NUMBER() OVER (PARTITION BY masterno ORDER BY Relationshipno ASC, s_startdt DESC) AS ROW_NUM
  FROM {{ source('sri_open_schema', 'ebbs_in_mastrell') }} AS ebbs_mastrel
  WHERE
    ods = '{{ var('__ods_val__') }}' AND PRIMARYFLAG = 'Y'
) AS EBBS_MASTREL
  ON TRIM(EBBS_MASTREL.MASTERNO) = TRIM(EBBS_ACCOUNT.MASTERNO)
  AND EBBS_MASTREL.ODS = EBBS_ACCOUNT.ODS
  AND EBBS_MASTREL.ods = '{{ var('__ods_val__') }}'
  AND EBBS_MASTREL.ROW_NUM = 1
LEFT OUTER JOIN {{ source('sri_open_schema', 'ebbs_in_seg') }} AS EBBS_SEG
  ON EBBS_ACCOUNT.SEGMENTCODE = EBBS_SEG.SEGMENTCODE
  AND EBBS_ACCOUNT.ods = EBBS_SEG.ods
  AND EBBS_SEG.ods = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN {{ source('sri_open_schema', 'ebbs_in_prd') }} AS EBBS_PRD
  ON EBBS_ACCOUNT.PRODUCTCODE = EBBS_PRD.PRODUCTCODE
  AND EBBS_ACCOUNT.ods = EBBS_PRD.ods
  AND EBBS_PRD.ods = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN (
  SELECT
    a.CURRENCYCODE,
    a.ACCOUNTNO,
    a.SEQNO,
    a.INFODETCODE,
    a.informationcode,
    a.ODS
  FROM (
    SELECT
      CURRENCYCODE,
      ACCOUNTNO,
      SEQNO,
      INFODETCODE,
      informationcode,
      ODS
    FROM {{ source('sri_open_schema', 'ebbs_in_accinfo') }} AS ebbs_accinfo
    WHERE
      ODS = '{{ var('__ods_val__') }}'
  ) AS a
  JOIN (
    SELECT
      MAX(SEQNO) AS SEQNO,
      INFORMATIONCODE,
      CURRENCYCODE,
      ACCOUNTNO
    FROM {{ source('sri_open_schema', 'ebbs_in_accinfo') }} AS ebbs_accinfo
    WHERE
      INFORMATIONCODE IN ('TM3') AND ODS = '{{ var('__ods_val__') }}'
    GROUP BY
      INFORMATIONCODE,
      CURRENCYCODE,
      ACCOUNTNO
  ) AS b
    ON a.SEQNO = b.SEQNO
    AND a.INFORMATIONCODE = b.INFORMATIONCODE
    AND a.CURRENCYCODE = b.CURRENCYCODE
    AND a.ACCOUNTNO = b.ACCOUNTNO
) AS EBBS_ACCINFO_VOSTRO
  ON EBBS_ACCINFO_VOSTRO.CURRENCYCODE = EBBS_ACCOUNT.CURRENCYCODE
  AND EBBS_ACCINFO_VOSTRO.ACCOUNTNO = EBBS_ACCOUNT.ACCOUNTNO
  AND EBBS_ACCINFO_VOSTRO.ODS = EBBS_ACCOUNT.ODS
  AND EBBS_ACCINFO_VOSTRO.ods = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN (
  SELECT
    a.CURRENCYCODE,
    a.ACCOUNTNO,
    a.SEQNO,
    a.INFODETCODE,
    a.informationcode,
    a.ODS
  FROM (
    SELECT
      CURRENCYCODE,
      ACCOUNTNO,
      SEQNO,
      INFODETCODE,
      informationcode,
      ODS
    FROM {{ source('sri_open_schema', 'ebbs_in_accinfo') }} AS ebbs_accinfo
    WHERE
      ODS = '{{ var('__ods_val__') }}'
  ) AS a
  JOIN (
    SELECT
      MAX(SEQNO) AS SEQNO,
      INFORMATIONCODE,
      CURRENCYCODE,
      ACCOUNTNO
    FROM {{ source('sri_open_schema', 'ebbs_in_accinfo') }} AS ebbs_accinfo
    WHERE
      INFORMATIONCODE IN ('FOL') AND ODS = '{{ var('__ods_val__') }}'
    GROUP BY
      INFORMATIONCODE,
      CURRENCYCODE,
      ACCOUNTNO
  ) AS b
    ON a.SEQNO = b.SEQNO
    AND a.INFORMATIONCODE = b.INFORMATIONCODE
    AND a.CURRENCYCODE = b.CURRENCYCODE
    AND a.ACCOUNTNO = b.ACCOUNTNO
) AS EBBS_ACCINFO_FOL
  ON EBBS_ACCINFO_FOL.CURRENCYCODE = EBBS_ACCOUNT.CURRENCYCODE
  AND EBBS_ACCINFO_FOL.ACCOUNTNO = EBBS_ACCOUNT.ACCOUNTNO
  AND EBBS_ACCINFO_FOL.ODS = EBBS_ACCOUNT.ODS
  AND EBBS_ACCINFO_FOL.ods = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN {{ source('sri_open_schema', 'ebbs_in_reason') }} AS EBBS_REASON
  ON TRIM(EBBS_ACCOUNT.ACCLOSUREREASON) = TRIM(EBBS_REASON.reasoncode)
  AND EBBS_ACCOUNT.ods = EBBS_reason.ods
  AND EBBS_reason.ods = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN (
  SELECT
    a.CURRENCYCODE,
    a.ACCOUNTNO,
    SUM(a.INTAMTPAID) AS TOTAL_INT_PD,
    a.CREDITDEBIT,
    a.INTPAIDDATE,
    a.ODS
  FROM (
    SELECT
      CURRENCYCODE,
      ACCOUNTNO,
      INTAMTPAID,
      CREDITDEBIT,
      INTPAIDDATE,
      ODS
    FROM {{ source('sri_open_schema', 'ebbs_in_acinthis') }} AS ebbs_acinthis
    WHERE
      ODS = '{{ var('__ods_val__') }}'
  ) AS a
  JOIN (
    SELECT
      MAX(INTPAIDDATE) AS INTPAIDDATE,
      CURRENCYCODE,
      ACCOUNTNO,
      CREDITDEBIT
    FROM {{ source('sri_open_schema', 'ebbs_in_acinthis') }} AS ebbs_acinthis
    WHERE
      ODS = '{{ var('__ods_val__') }}'
    GROUP BY
      CURRENCYCODE,
      ACCOUNTNO,
      CREDITDEBIT
  ) AS b
    ON a.INTPAIDDATE = b.INTPAIDDATE
    AND a.CREDITDEBIT = b.CREDITDEBIT
    AND a.CURRENCYCODE = b.CURRENCYCODE
    AND TRIM(a.accountno) = TRIM(b.accountno)
  GROUP BY
    a.CURRENCYCODE,
    a.ACCOUNTNO,
    a.CREDITDEBIT,
    a.INTPAIDDATE,
    a.ODS
) AS EBBS_ACINTHIS_C
  ON EBBS_ACINTHIS_C.CURRENCYCODE = EBBS_ACCOUNT.CURRENCYCODE
  AND TRIM(EBBS_ACINTHIS_C.ACCOUNTNO) = TRIM(EBBS_ACCOUNT.ACCOUNTNO)
  AND EBBS_ACINTHIS_C.CREDITDEBIT = 'C'
  AND EBBS_ACINTHIS_C.ODS = EBBS_ACCOUNT.ODS
  AND EBBS_ACINTHIS_C.ODS = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN (
  SELECT
    a.CURRENCYCODE,
    a.ACCOUNTNO,
    SUM(a.INTAMTPAID) AS TOTAL_INT_PD,
    a.CREDITDEBIT,
    a.INTPAIDDATE,
    a.ODS
  FROM (
    SELECT
      CURRENCYCODE,
      ACCOUNTNO,
      INTAMTPAID,
      CREDITDEBIT,
      INTPAIDDATE,
      ODS
    FROM {{ source('sri_open_schema', 'ebbs_in_acinthis') }} AS ebbs_acinthis
    WHERE
      ODS = '{{ var('__ods_val__') }}'
  ) AS a
  JOIN (
    SELECT
      MAX(INTPAIDDATE) AS INTPAIDDATE,
      CURRENCYCODE,
      ACCOUNTNO,
      CREDITDEBIT
    FROM {{ source('sri_open_schema', 'ebbs_in_acinthis') }} AS ebbs_acinthis
    WHERE
      ODS = '{{ var('__ods_val__') }}'
    GROUP BY
      CURRENCYCODE,
      ACCOUNTNO,
      CREDITDEBIT
  ) AS b
    ON a.INTPAIDDATE = b.INTPAIDDATE
    AND a.CREDITDEBIT = b.CREDITDEBIT
    AND a.CURRENCYCODE = b.CURRENCYCODE
    AND TRIM(a.accountno) = TRIM(b.accountno)
  GROUP BY
    a.CURRENCYCODE,
    a.ACCOUNTNO,
    a.CREDITDEBIT,
    a.INTPAIDDATE,
    a.ODS
) AS EBBS_ACINTHIS_D
  ON EBBS_ACINTHIS_D.CURRENCYCODE = EBBS_ACCOUNT.CURRENCYCODE
  AND TRIM(EBBS_ACINTHIS_D.ACCOUNTNO) = TRIM(EBBS_ACCOUNT.ACCOUNTNO)
  AND EBBS_ACINTHIS_D.CREDITDEBIT = 'D'
  AND EBBS_ACINTHIS_D.ODS = EBBS_ACCOUNT.ODS
  AND EBBS_ACINTHIS_D.ODS = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN (
  SELECT
    *
  FROM {{ source('sri_open_schema', 'm_scb_entity_xlate') }} AS m_scb_entity_xlate
  WHERE
    ods = '{{ var('__ods_val__') }}' AND tp_system = 'EBBS'
) AS scbentityxlate
  ON TRIM(EBBS_ACCOUNT.ACCOUNTBRANCH) = scbentityxlate.branch_code
  AND EBBS_ACCOUNT.COUNTRY = scbentityxlate.country_code
  AND EBBS_ACCOUNT.ODS = scbentityxlate.ODS
LEFT OUTER JOIN {{ source('sri_open_schema', 'm_cdl_glbu_to_entcd_bkcd_xlate') }} AS G
  ON g.GL_BU_CD = TRIM(EBBS_ACCOUNT.ACCOUNTBRANCH)
  AND G.SRC_SYS = 'PSGL'
  AND G.CTY = 'XX'
  AND G.ODS = EBBS_ACCOUNT.ODS
  AND G.ods = '{{ var('__ods_val__') }}'
LEFT OUTER JOIN {{ source('sri_open_schema', 'alt_prty') }} AS ALT_PRTY
  ON TRIM(CAST(EBBS_ACCOUNT.MASTERNO AS STRING)) = ALT_PRTY.PRTY_ID
  AND ALT_PRTY.process_id_val = 'ALT_PRTY-SCI-LSPSYSXREF'
  AND ALT_PRTY.ALT_PRTY_SRC_SYS = 'EBBS'
  AND ALT_PRTY.ODS_VAL = '{{ var('__ods_val__') }}'
  AND ALT_PRTY.TP_SYS_VAL = 'SCI'
  AND ALT_PRTY.bkg_org_val = scbentityxlate.sci_entity_code
LEFT OUTER JOIN {{ source('sri_open_schema', 'prty') }} AS PRTY_SP_SCI
  ON PRTY_SP_SCI.PRTY_ID = ALT_PRTY.ALT_PRTY_ID
  AND PRTY_SP_SCI.SRC_SYS = 'SCI'
  AND PRTY_SP_SCI.PRTY_CAT_CD = 'SubProfile'
  AND PRTY_SP_SCI.PROCESS_ID_VAL = 'PRTY-SCI-SUBPROF'
  AND PRTY_SP_SCI.ODS_VAL = '{{ var('__ods_val__') }}'
WHERE
  EBBS_ACCOUNT.ODS = '{{ var('__ods_val__') }}'
  AND (
    EBBS_ACCOUNT.STATUSFLAG <> 14
    OR EBBS_ACCOUNT.ACCLOSEDT > LAST_DAY(EBBS_ACCOUNT.ODS - INTERVAL '14' MONTH)
  )
 