//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GDPTenant) DeepCopyInto(out *GDPTenant) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GDPTenant.
func (in *GDPTenant) DeepCopy() *GDPTenant {
	if in == nil {
		return nil
	}
	out := new(GDPTenant)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GDPTenant) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GDPTenantList) DeepCopyInto(out *GDPTenantList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GDPTenant, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GDPTenantList.
func (in *GDPTenantList) DeepCopy() *GDPTenantList {
	if in == nil {
		return nil
	}
	out := new(GDPTenantList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GDPTenantList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GDPTenantSpec) DeepCopyInto(out *GDPTenantSpec) {
	*out = *in
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TenantNoninteractiveOwner != nil {
		in, out := &in.TenantNoninteractiveOwner, &out.TenantNoninteractiveOwner
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TenantNoninteractiveViewer != nil {
		in, out := &in.TenantNoninteractiveViewer, &out.TenantNoninteractiveViewer
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TenantInteractiveOwner != nil {
		in, out := &in.TenantInteractiveOwner, &out.TenantInteractiveOwner
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TenantInteractiveViewer != nil {
		in, out := &in.TenantInteractiveViewer, &out.TenantInteractiveViewer
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.JobQueue = in.JobQueue
	out.ResourceQuotas = in.ResourceQuotas
	if in.ObjectStoreBuckets != nil {
		in, out := &in.ObjectStoreBuckets, &out.ObjectStoreBuckets
		*out = make([]ObjectStoreBuckets, len(*in))
		copy(*out, *in)
	}
	if in.RangerPolicies != nil {
		in, out := &in.RangerPolicies, &out.RangerPolicies
		*out = make([]RangerPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GDPTenantSpec.
func (in *GDPTenantSpec) DeepCopy() *GDPTenantSpec {
	if in == nil {
		return nil
	}
	out := new(GDPTenantSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GDPTenantStatus) DeepCopyInto(out *GDPTenantStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Trino != nil {
		in, out := &in.Trino, &out.Trino
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Ranger != nil {
		in, out := &in.Ranger, &out.Ranger
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GDPTenantStatus.
func (in *GDPTenantStatus) DeepCopy() *GDPTenantStatus {
	if in == nil {
		return nil
	}
	out := new(GDPTenantStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobQueue) DeepCopyInto(out *JobQueue) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobQueue.
func (in *JobQueue) DeepCopy() *JobQueue {
	if in == nil {
		return nil
	}
	out := new(JobQueue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectStoreBuckets) DeepCopyInto(out *ObjectStoreBuckets) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectStoreBuckets.
func (in *ObjectStoreBuckets) DeepCopy() *ObjectStoreBuckets {
	if in == nil {
		return nil
	}
	out := new(ObjectStoreBuckets)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RangerPolicy) DeepCopyInto(out *RangerPolicy) {
	*out = *in
	if in.SchemaAdmin != nil {
		in, out := &in.SchemaAdmin, &out.SchemaAdmin
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SchemaViewer != nil {
		in, out := &in.SchemaViewer, &out.SchemaViewer
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RangerPolicy.
func (in *RangerPolicy) DeepCopy() *RangerPolicy {
	if in == nil {
		return nil
	}
	out := new(RangerPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceQuotas) DeepCopyInto(out *ResourceQuotas) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceQuotas.
func (in *ResourceQuotas) DeepCopy() *ResourceQuotas {
	if in == nil {
		return nil
	}
	out := new(ResourceQuotas)
	in.DeepCopyInto(out)
	return out
}
