;EBB~SG~EBBS_SG_MLITDEL~C_APRVD_LMT~1400303SGEBBSELECT 
CONCAT('@DATA_SRC_EBB@', '-', '@SOURCE_COUNTRY_CODE@', '-', TRIM(MLITDEL.DEALNO), '-', MLITDEL.SEQNO) AS LMT_SROGT_ID
, CONCAT('@DATA_SRC_EBB@', '-', '@SOURCE_COUNTRY_CODE@', '-', TRIM(MDELTYP.PRODUCTCODE))  AS PROD_SROGT_ID 
, CONCAT('@DATA_SRC_EBB@', '-', '@SOURCE_COUNTRY_CODE@', '-', TRIM(MASTREL.RELATIONSHIPNO)) AS PRTY_SROGT_ID
, CONCAT(TRIM(MLITDEL.DEALNO), '-', MLITDEL.SEQNO) AS DOM_LMT_REF
, MDELTYP.PRODUCTCODE AS DOM_PROD_CD
, MASTREL.RELATIONSHIPNO AS DOM_PRTY_REF
, MLITDEL.CURRENCYCODE AS ACCT_CURY_CD
, MLITDEL.LIMITAMT AS LMT_AMT
, '@DATA_SRC_EBB@' as DATA_SRC
, '@SOURCE_COUNTRY_CODE@' as SOURCE_COUNTRY_CODE
, 'EBB~SG~EBBS_SG_MLITDEL~C_APRVD_LMT~1' as PROCESS_ID
, from_unixtime(unix_timestamp()) as PPN_DTM
, '@DT_VRSN@' as DT_VRSN
, '@ACCS_CTRY_CD@' as ACCS_CTRY_CD
, CASE WHEN C_CRTD_CORE_PRTY.ACCS_SEGMT_CD IS NULL or trim (C_CRTD_CORE_PRTY.ACCS_SEGMT_CD)='' THEN NULL ELSE  C_CRTD_CORE_PRTY.ACCS_SEGMT_CD END as ACCS_SEGMT_CD
, '@MNTHEND_FL@' as MNTHEND_FL
FROM (SELECT LIMITORLIEN, DEALNO, SEQNO, CURRENCYCODE, LIMITAMT  FROM @SOURCE_EBB@.EBBS_SG_MLITDEL WHERE ODS = '@ODS_EBB@' AND LIMITORLIEN = 'L') MLITDEL
LEFT JOIN
(SELECT DEALNO , CUSTTCID, MMKDEALTYPE  FROM @SOURCE_EBB@.EBBS_SG_MMKDEAL WHERE ODS = '@ODS_EBB@' ) MMKDEAL 
ON trim(MLITDEL.DEALNO) = trim(MMKDEAL.DEALNO)
LEFT JOIN (SELECT MASTERNO,RELATIONSHIPNO, PRIMARYFLAG FROM @SOURCE_EBB@.EBBS_SG_MASTREL WHERE ODS = '@ODS_EBB@' ) MASTREL 
ON TRIM(MMKDEAL.CUSTTCID) = TRIM(MASTREL.MASTERNO) AND MASTREL.PRIMARYFLAG = 'Y'
LEFT JOIN
(SELECT PRTY_SROGT_ID, ACCS_SEGMT_CD FROM @TARGET_WORK@.C_CRTD_CORE_PRTY WHERE process_date = '@PSE_DATE@' AND data_src = '@DATA_SRC_EBB@' AND source_country_code = '@SOURCE_COUNTRY_CODE@') C_CRTD_CORE_PRTY
ON CONCAT('@DATA_SRC_EBB@', '-', '@SOURCE_COUNTRY_CODE@', '-', TRIM(MASTREL.RELATIONSHIPNO)) = TRIM(C_CRTD_CORE_PRTY.PRTY_SROGT_ID)
LEFT JOIN (select PRODUCTCODE,MMKDEALTYPE from @SOURCE_EBB@.EBBS_SG_MDELTYP WHERE ODS = '@ODS_EBB@') MDELTYP ON TRIM(MMKDEAL.MMKDEALTYPE) = TRIM(MDELTYP.MMKDEALTYPE)c_aprvd_lmtmaster1007

