;EBB~SG~EBBS_SG_MMKDEAL~C_ACCT_INT_MTRC~1400302SGEBBSELECT 
CONCAT('@DATA_SRC_EBB@-@SOURCE_COUNTRY_CODE@-', TRIM(MMKDEAL.DEALNO)) AS ACCT_SROGT_ID, 
CONCAT('@DATA_SRC_EBB@-@SOURCE_COUNTRY_CODE@-', TRIM(MDELTYP.PRODUCTCODE)) AS PROD_SROGT_ID, 
CONCAT('@DATA_SRC_EBB@-@SOURCE_COUNTRY_CODE@-', TRIM(MASTREL.RELATIONSHIPNO)) AS PRTY_SROGT_ID, 
MMKDEAL.DEALNO AS DOM_ACCT_REF, 
MDELTYP.PRODUCTCODE AS DOM_PROD_CD, 
MASTREL.RELATIONSHIPNO AS DOM_PRTY_REF, 
MMKDEAL.DEALCURRCD AS ACCT_CURY_CD, 
MMKDEAL.DEALRATE AS FIXD_INT_RATE,
MMKDEAL.ACCRUEDINTERESTAMT as CR_INT_ACR_AMT,
MMKDEAL.MATURITYINT as MTY_INT_AMT,
from_unixtime(unix_timestamp()) AS PPN_DTM,
'@DT_VRSN@' AS DT_VRSN,
'@ACCS_CTRY_CD@' AS ACCS_CTRY_CD,
WPM.ACCS_SEGMT_CD AS ACCS_SEGMT_CD, 
'EBB~SG~EBBS_SG_MMKDEAL~C_ACCT_INT_MTRC~1' AS PROCESS_ID
,'@MNTHEND_FL@' AS MNTHEND_FL
FROM 
(SELECT * FROM @SOURCE_EBB@.EBBS_SG_MMKDEAL where ods = "@ODS@") MMKDEAL 
LEFT JOIN 
(SELECT * FROM @SOURCE_EBB@.EBBS_SG_MASTREL where ods = "@ODS@") MASTREL 
ON TRIM(MMKDEAL.CUSTTCID) = TRIM(MASTREL.MASTERNO) AND MASTREL.PRIMARYFLAG = 'Y'
LEFT JOIN 
(SELECT * FROM @TARGET_WORK@.C_CRTD_CORE_PRTY WHERE PROCESS_DATE = '@PSE_DATE@' AND DATA_SRC = '@DATA_SRC_EBB@' AND SOURCE_COUNTRY_CODE = '@SOURCE_COUNTRY_CODE@') WPM 
on CONCAT('@DATA_SRC_EBB@-@SOURCE_COUNTRY_CODE@-', TRIM(MASTREL.RELATIONSHIPNO)) = WPM.PRTY_SROGT_ID
LEFT JOIN 
(SELECT * FROM @SOURCE_EBB@.EBBS_SG_MDELTYP where ods = "@ODS@") MDELTYP 
ON TRIM(MMKDEAL.MMKDEALTYPE) = TRIM(MDELTYP.MMKDEALTYPE)
c_acct_int_mtrcmaster10010
