;EBB~SG~EBBS_SG_ACCOUNT~C_ACCT_INT_MTRC~1400302SGEBBSELECT 
CONCAT('@DATA_SRC_EBB@-@SOURCE_COUNTRY_CODE@-', TRIM(ACCOUNT.CURRENCYCODE), '-', TRIM(ACCOUNT.ACCOUNTNO)) AS ACCT_SROGT_ID
,CONCAT('@DATA_SRC_EBB@-@SOURCE_COUNTRY_CODE@-', TRIM(ACCOUNT.PRODUCTCODE)) AS PROD_SROGT_ID
,CONCAT('@DATA_SRC_EBB@-@SOURCE_COUNTRY_CODE@-', TRIM(MASTREL.RELATIONSHIPNO)) AS PRTY_SROGT_ID
,CONCAT(TRIM(ACCOUNT.CURRENCYCODE), '-', TRIM(ACCOUNT.ACCOUNTNO)) AS DOM_ACCT_REF
,ACCOUNT.PRODUCTCODE AS DOM_PROD_CD
,MASTREL.RELATIONSHIPNO AS DOM_PRTY_REF
,ACCOUNT.CURRENCYCODE AS ACCT_CURY_CD
,ACCOUNT.LASTCRINTRATE AS LAST_CR_INT_RATE
,ACCOUNT.LASTDRINTRATE AS LAST_DR_INT_RATE
,ACCOUNT.LASTEXSINTRATE AS LAST_EX_INT_RATE
,from_unixtime(unix_timestamp()) AS PPN_DTM
,'@DT_VRSN@' AS DT_VRSN
,'@ACCS_CTRY_CD@' AS ACCS_CTRY_CD
,WPM.ACCS_SEGMT_CD AS ACCS_SEGMT_CD
,'EBB~SG~EBBS_SG_ACCOUNT~C_ACCT_INT_MTRC~1' AS PROCESS_ID 
,'@MNTHEND_FL@' AS MNTHEND_FL
,ACCTPRV.INTERESTAMOUNT AS CR_INT_ACR_AMT
FROM 

(Select * from @SOURCE_EBB@.EBBS_SG_ACCOUNT where ods = "@ODS@") ACCOUNT 
LEFT JOIN 
(Select * from @SOURCE_EBB@.EBBS_SG_MASTREL where ods = "@ODS@") MASTREL
ON TRIM(ACCOUNT.MASTERNO) = TRIM(MASTREL.MASTERNO) AND MASTREL.PRIMARYFLAG = 'Y'
LEFT JOIN 
(Select * from @TARGET_WORK@.C_CRTD_CORE_PRTY WHERE PROCESS_DATE = '@PSE_DATE@' AND DATA_SRC = '@DATA_SRC_EBB@' AND SOURCE_COUNTRY_CODE = '@SOURCE_COUNTRY_CODE@') WPM
on CONCAT('@DATA_SRC_EBB@-@SOURCE_COUNTRY_CODE@-', TRIM(MASTREL.RELATIONSHIPNO)) = WPM.PRTY_SROGT_ID
LEFT JOIN
(SELECT CURRENCYCODE,ACCOUNTNO,ISCRDRFLAG,PROVISIONDATE,PROVISIONGROUP,INTERESTAMOUNT,ROW_NUMBER() OVER(PARTITION BY trim(CURRENCYCODE), trim(ACCOUNTNO),trim(ISCRDRFLAG) ORDER BY trim(ods) DESC) AS ROW1
FROM @SOURCE_EBB@.EBBS_SG_ACCTPRV WHERE ods between date_format('@ODS@','%Y-%m-01') and '@ODS@')ACCTPRV
ON trim(ACCTPRV.CURRENCYCODE) = trim(ACCOUNT.CURRENCYCODE) AND trim(ACCTPRV.ACCOUNTNO) = trim(ACCOUNT.ACCOUNTNO) 
AND trim(ACCTPRV.ISCRDRFLAG)='C' AND ROW1=1c_acct_int_mtrcmaster1009
