;EBB~SG~EBBS_SG_LMTLNDT~C_ACTVD_LMT~1400303SGEBBSELECT 
CONCAT('@DATA_SRC_EBB@', '-', '@SOURCE_COUNTRY_CODE@', '-', TRIM(LMTLNDT.MASTERNO), '-', TRIM(LMTLNDT.LIMITNO))  AS ACTVD_LMT_SROGT_ID
, CONCAT('@DATA_SRC_EBB@', '-', '@SOURCE_COUNTRY_CODE@', '-', TRIM(MASTREL.RELATIONSHIPNO)) AS PRTY_SROGT_ID
, CONCAT(TRIM(LMTLNDT.MASTERNO), '-', TRIM(LMTLNDT.LIMITNO)) AS DOM_LMT_REF
, MASTREL.RELATIONSHIPNO AS DOM_PRTY_REF
, LMTLNDT.LIMITPRDCODE AS LMT_TP_CD
, LMTLNDT.ACTIVELIMITLIENAMT AS LMT_AMT
, LMTLNDT.LMTSTARTDATE AS LMT_SETUP_DT
, LMTLNDT.EXPIRYDATE AS LMT_MATURITY_DT
, LMTLNDT.CURRENCYCODE AS LMT_CURY_CD
, '@DATA_SRC_EBB@' as DATA_SRC
, '@SOURCE_COUNTRY_CODE@' as SOURCE_COUNTRY_CODE
, 'EBB~SG~EBBS_SG_LMTLNDT~C_ACTVD_LMT~1' as PROCESS_ID
, from_unixtime(unix_timestamp()) as PPN_DTM
, '@DT_VRSN@' as DT_VRSN
, '@ACCS_CTRY_CD@' as ACCS_CTRY_CD
, CASE WHEN C_CRTD_CORE_PRTY.ACCS_SEGMT_CD IS NULL or trim (C_CRTD_CORE_PRTY.ACCS_SEGMT_CD)='' THEN NULL ELSE  C_CRTD_CORE_PRTY.ACCS_SEGMT_CD END as ACCS_SEGMT_CD
, '@MNTHEND_FL@' as MNTHEND_FL
FROM  (SELECT LIMITORLIEN, LIMITPRDCODE, ACTIVELIMITLIENAMT, LMTSTARTDATE, CURRENCYCODE, EXPIRYDATE, LIMITNO, MASTERNO  FROM @SOURCE_EBB@.EBBS_SG_LMTLNDT WHERE ODS = '@ODS_EBB@' AND LIMITORLIEN = 'L') LMTLNDT  
LEFT JOIN  (SELECT MASTERNO,RELATIONSHIPNO,PRIMARYFLAG FROM @SOURCE_EBB@.EBBS_SG_MASTREL WHERE ODS = '@ODS_EBB@') MASTREL  ON TRIM(LMTLNDT.MASTERNO) = TRIM(MASTREL.MASTERNO) AND MASTREL.PRIMARYFLAG = 'Y'
LEFT JOIN (SELECT * FROM @TARGET_WORK@.C_CRTD_CORE_PRTY WHERE PROCESS_DATE = '@PSE_DATE@' AND DATA_SRC = '@DATA_SRC_EBB@' AND SOURCE_COUNTRY_CODE = '@SOURCE_COUNTRY_CODE@') C_CRTD_CORE_PRTY 
 ON CONCAT('@DATA_SRC_EBB@', '-', '@SOURCE_COUNTRY_CODE@', '-', TRIM(MASTREL.RELATIONSHIPNO)) = TRIM(C_CRTD_CORE_PRTY.PRTY_SROGT_ID)c_actvd_lmtmaster1009
