;EBB~SG~EBBS_SG_ACCOUNT~C_ACCT_BAL_MTRC~1400302SGEBBSelect
CONCAT('@DATA_SRC_EBB@-@SOURCE_COUNTRY_CODE@-', TRIM(ACCOUNT.CURRENCYCODE), '-', TRIM(ACCOUNT.ACCOUNTNO)) as ACCT_SROGT_ID
,CONCAT('@DATA_SRC_EBB@-@SOURCE_COUNTRY_CODE@-', TRIM(ACCOUNT.PRODUCTCODE)) as PROD_SROGT_ID
,CONCAT('@DATA_SRC_EBB@-@SOURCE_COUNTRY_CODE@-', TRIM(MASTREL.RELATIONSHIPNO)) as PRTY_SROGT_ID
,CONCAT(TRIM(ACCOUNT.CURRENCYCODE), '-', TRIM(ACCOUNT.ACCOUNTNO)) as DOM_ACCT_REF
,ACCOUNT.PRODUCTCODE as DOM_PROD_CD
,MASTREL.RELATIONSHIPNO as DOM_PRTY_REF
,CASE WHEN (BEBAL.CURRENCYCODE is not NULL AND BEBAL.ACCOUNTNO is not NULL) THEN BEBAL.CURRENCYCODE ELSE C_ACCT_BAL_MTRC_PREV.BAL_CURY_CD END as BAL_CURY_CD
,CASE WHEN (BEBAL.CURRENCYCODE is not NULL AND BEBAL.ACCOUNTNO is not NULL) THEN BEBAL.LEDGERBALANCE ELSE C_ACCT_BAL_MTRC_PREV.OS_BAL_AMT END as OS_BAL_AMT
,CASE WHEN (BEBAL.CURRENCYCODE is not NULL AND BEBAL.ACCOUNTNO is not NULL) THEN BEBAL.ALEDGERBALANCE ELSE C_ACCT_BAL_MTRC_PREV.AVAIL_BAL_AMT END as AVAIL_BAL_AMT
,CASE WHEN (CBAL.CURRENCYCODE is not NULL AND CBAL.ACCOUNTNO is not NULL) THEN CBAL.MAVGLEDGERBAL ELSE C_ACCT_BAL_MTRC_PREV.MTHLY_AVG_LDGR_BAL_AMT END as MTHLY_AVG_LDGR_BAL_AMT
,CASE WHEN (BEBAL.CURRENCYCODE is not NULL AND BEBAL.ACCOUNTNO is not NULL) THEN BEBAL.DATE1 ELSE C_ACCT_BAL_MTRC_PREV.OS_BAL_AMT_EFF_DT END as OS_BAL_AMT_EFF_DT
,from_unixtime(unix_timestamp()) AS PPN_DTM
,'@DT_VRSN@' AS DT_VRSN
,'@ACCS_CTRY_CD@' as ACCS_CTRY_CD
,C_CRTD_CORE_PRTY.ACCS_SEGMT_CD as ACCS_SEGMT_CD
,'EBB~SG~EBBS_SG_ACCOUNT~C_ACCT_BAL_MTRC~1' as PROCESS_ID
,'@MNTHEND_FL@' AS MNTHEND_FL
,ACOD.CURRENTOUTSTANDINGAMT as CURR_STMT_CYC_OS_BAL_AMT
FROM (SELECT * FROM @SOURCE_EBB@.EBBS_SG_ACCOUNT where ods = '@ODS_EBB@') ACCOUNT
LEFT JOIN
(SELECT CURRENCYCODE, ACCOUNTNO, DATE1, LEDGERBALANCE, ALEDGERBALANCE,
ROW_NUMBER() OVER(PARTITION BY CURRENCYCODE, ACCOUNTNO ORDER BY DATE1 DESC, cast(SPLIT(rowid,'_')[6] as int))  AS ROW2
FROM @SOURCE_EBB@.EBBS_SG_BEBAL WHERE ODS = '@ODS_EBB@')BEBAL
ON BEBAL.CURRENCYCODE = ACCOUNT.CURRENCYCODE AND BEBAL.ACCOUNTNO = ACCOUNT.ACCOUNTNO AND BEBAL.ROW2 = 1
LEFT JOIN
(SELECT *,
ROW_NUMBER() OVER(PARTITION BY CURRENCYCODE, ACCOUNTNO ORDER BY LASTUPDATEDDATE DESC, cast(SPLIT(rowid,'_')[6] as int))  AS ROW2
FROM @SOURCE_EBB@.EBBS_SG_CBALSTAT WHERE ODS = '@ODS_EBB@') CBAL
ON CBAL.CURRENCYCODE = ACCOUNT.CURRENCYCODE and CBAL.ACCOUNTNO = ACCOUNT.ACCOUNTNO AND CBAL.ROW2 = 1
LEFT JOIN
(SELECT * FROM @SOURCE_EBB@.EBBS_SG_MASTREL WHERE ODS = '@ODS_EBB@'  AND PRIMARYFLAG = 'Y') MASTREL
ON TRIM(ACCOUNT.MASTERNO) = TRIM(MASTREL.MASTERNO)
LEFT JOIN
(SELECT * FROM @TARGET_WORK@.C_CRTD_CORE_PRTY
WHERE PROCESS_DATE = '@PSE_DATE@' AND DATA_SRC = '@DATA_SRC_EBB@' AND SOURCE_COUNTRY_CODE = '@SOURCE_COUNTRY_CODE@')C_CRTD_CORE_PRTY
on CONCAT('@DATA_SRC_EBB@-@SOURCE_COUNTRY_CODE@-',TRIM(MASTREL.RELATIONSHIPNO))=C_CRTD_CORE_PRTY.PRTY_SROGT_ID
LEFT JOIN (SELECT * FROM (SELECT *, row_number() over (partition by acct_srogt_id ORDER BY acct_srogt_id DESC) as rw from @TARGET_WORK@.C_ACCT_BAL_MTRC
WHERE PROCESS_DATE='@PREV_T1@' AND DATA_SRC = '@DATA_SRC_EBB@' AND SOURCE_COUNTRY_CODE = '@SOURCE_COUNTRY_CODE@' and process_id='EBB~SG~EBBS_SG_ACCOUNT~C_ACCT_BAL_MTRC~1')a where a.rw=1
)C_ACCT_BAL_MTRC_PREV
ON CONCAT('@DATA_SRC_EBB@-@SOURCE_COUNTRY_CODE@-',TRIM(ACCOUNT.CURRENCYCODE),'-',TRIM(ACCOUNT.ACCOUNTNO))=C_ACCT_BAL_MTRC_PREV.ACCT_SROGT_ID
left join 
(SELECT CURRENTOUTSTANDINGAMT,CURRENCYCODE,ACCOUNTNO FROM @SOURCE_EBB@.EBBS_SG_ACODINFO WHERE ODS = '@ODS_EBB@' )ACOD
on trim(ACCOUNT.CURRENCYCODE) = trim(ACOD.CURRENCYCODE) AND trim(ACCOUNT.ACCOUNTNO) = trim(ACOD.ACCOUNTNO)c_acct_bal_mtrcmaster1006