;EBB~SG~EBBS_SG_ACCTLMT~C_ACTVD_LMT~1400303SGEBBSELECT 
CONCAT('@DATA_SRC_EBB@', '-', '@SOURCE_COUNTRY_CODE@', '-', TRIM(ACCTLMT.CURRENCYCODE), '-', TRIM(ACCTLMT.ACCOUNTNO)) AS ACTVD_LMT_SROGT_ID
, CONCAT('@DATA_SRC_EBB@', '-', '@SOURCE_COUNTRY_CODE@', '-', TRIM(MASTREL.RELATIONSHIPNO)) AS PRTY_SROGT_ID
, CONCAT(TRIM(ACCTLMT.CURRENCYCODE), '-', TRIM(ACCTLMT.ACCOUNTNO)) AS DOM_LMT_REF
, MASTREL.RELATIONSHIPNO AS DOM_PRTY_REF
, ACCTLMT.LIMITLIENAMT AS LMT_AMT
, ACCTLMT.LMTSTARTDT AS LMT_SETUP_DT
, ACCTLMT.EXPIRYDT AS LMT_MATURITY_DT
, ACCTLMT.CURRENCYCODE AS LMT_CURY_CD
, '@DATA_SRC_EBB@' as DATA_SRC
, '@SOURCE_COUNTRY_CODE@' as SOURCE_COUNTRY_CODE
, 'EBB~SG~EBBS_SG_ACCTLMT~C_ACTVD_LMT~1' as PROCESS_ID
, from_unixtime(unix_timestamp()) as PPN_DTM
, '@DT_VRSN@' as DT_VRSN
, '@ACCS_CTRY_CD@' as ACCS_CTRY_CD
, CASE WHEN C_CRTD_CORE_PRTY.ACCS_SEGMT_CD IS NULL or trim (C_CRTD_CORE_PRTY.ACCS_SEGMT_CD)='' THEN NULL ELSE  C_CRTD_CORE_PRTY.ACCS_SEGMT_CD END as ACCS_SEGMT_CD
, '@MNTHEND_FL@' as MNTHEND_FL
FROM (SELECT LIMITORLIEN, ACCOUNTNO, LIMITLIENAMT, LMTSTARTDT, CURRENCYCODE, EXPIRYDT  FROM @SOURCE_EBB@.EBBS_SG_ACCTLMT WHERE ODS = '@ODS_EBB@' AND LIMITORLIEN = 'L') ACCTLMT
LEFT JOIN
(SELECT   ACCOUNTNO, CURRENCYCODE , PRODUCTCODE,MASTERNO  FROM @SOURCE_EBB@.EBBS_SG_ACCOUNT WHERE ODS = '@ODS_EBB@' ) ACCOUNT 
ON ACCTLMT.CURRENCYCODE = ACCOUNT.CURRENCYCODE and ACCTLMT.ACCOUNTNO = ACCOUNT.ACCOUNTNO
LEFT JOIN (SELECT MASTERNO,RELATIONSHIPNO, PRIMARYFLAG FROM @SOURCE_EBB@.EBBS_SG_MASTREL WHERE ODS = '@ODS_EBB@' ) MASTREL 
ON TRIM(ACCOUNT.MASTERNO) = TRIM(MASTREL.MASTERNO) AND MASTREL.PRIMARYFLAG = 'Y'
LEFT JOIN
(SELECT PRTY_SROGT_ID, ACCS_SEGMT_CD FROM @TARGET_WORK@.C_CRTD_CORE_PRTY WHERE process_date = '@PSE_DATE@' AND data_src = '@DATA_SRC_EBB@' AND source_country_code = '@SOURCE_COUNTRY_CODE@') C_CRTD_CORE_PRTY
ON CONCAT('@DATA_SRC_EBB@', '-', '@SOURCE_COUNTRY_CODE@', '-', TRIM(MASTREL.RELATIONSHIPNO)) = C_CRTD_CORE_PRTY.PRTY_SROGT_IDc_actvd_lmtmaster1008


