;EBB~SG~EBBS_SG_MLTMAST~C_APRVD_LMT~1400303SGEBBSELECT
CONCAT('@DATA_SRC_EBB@', '-', '@SOURCE_COUNTRY_CODE@', '-', TRIM(MLTMAST.CURRENCYCODE), '-', TRIM(MLTMAST.ACCOUNTNO)) AS LMT_SROGT_ID
, CONCAT('@DATA_SRC_EBB@', '-', '@SOURCE_COUNTRY_CODE@', '-', TRIM(ACCOUNT.PRODUCTCODE)) AS PROD_SROGT_ID
, CONCAT('@DATA_SRC_EBB@', '-', '@SOURCE_COUNTRY_CODE@', '-', TRIM(MASTREL.RELATIONSHIPNO)) AS PRTY_SROGT_ID
, CONCAT(TRIM(MLTMAST.CURRENCYCODE), '-', TRIM(MLTMAST.ACCOUNTNO)) AS DOM_LMT_REF
, ACCOUNT.PRODUCTCODE AS DOM_PROD_CD
, MASTREL.RELATIONSHIPNO AS DOM_PRTY_REF
, MLTMAST.CURRENCYCODE AS ACCT_CURY_CD
, MLTMAST.TOTALLIMITAMT AS LMT_AMT
, MLTMAST.LMTPRVPRDCD AS LMT_TP_CD
, '@DATA_SRC_EBB@' as DATA_SRC
, '@SOURCE_COUNTRY_CODE@' as SOURCE_COUNTRY_CODE
, 'EBB~SG~EBBS_SG_MLTMAST~C_APRVD_LMT~1' as PROCESS_ID
, from_unixtime(unix_timestamp()) as PPN_DTM
, '@DT_VRSN@' as DT_VRSN
, '@ACCS_CTRY_CD@' as ACCS_CTRY_CD
, CASE WHEN C_CRTD_CORE_PRTY.ACCS_SEGMT_CD IS NULL or trim (C_CRTD_CORE_PRTY.ACCS_SEGMT_CD)='' THEN NULL ELSE  C_CRTD_CORE_PRTY.ACCS_SEGMT_CD END as ACCS_SEGMT_CD
, '@MNTHEND_FL@' as MNTHEND_FL
FROM (SELECT TOTALLIMITAMT,CURRENCYCODE, LMTPRVPRDCD, ACCOUNTNO,LIMITORLIEN FROM @SOURCE_EBB@.EBBS_SG_MLTMAST WHERE ODS = '@ODS_EBB@' AND LIMITORLIEN = 'L') MLTMAST
LEFT JOIN
(SELECT PRODUCTCODE, CURRENCYCODE, MASTERNO,ACCOUNTNO FROM @SOURCE_EBB@.EBBS_SG_ACCOUNT WHERE ODS = '@ODS_EBB@' ) ACCOUNT 
ON trim(MLTMAST.CURRENCYCODE) = trim(ACCOUNT.CURRENCYCODE) and trim(MLTMAST.ACCOUNTNO) = trim(ACCOUNT.ACCOUNTNO)
LEFT JOIN (SELECT MASTERNO,RELATIONSHIPNO, PRIMARYFLAG FROM @SOURCE_EBB@.EBBS_SG_MASTREL WHERE ODS = '@ODS_EBB@' ) MASTREL 
ON TRIM(ACCOUNT.MASTERNO) = TRIM(MASTREL.MASTERNO) AND MASTREL.PRIMARYFLAG = 'Y'
LEFT JOIN
(SELECT PRTY_SROGT_ID, ACCS_SEGMT_CD FROM @TARGET_WORK@.C_CRTD_CORE_PRTY WHERE PROCESS_DATE = '@PSE_DATE@' AND DATA_SRC = '@DATA_SRC_EBB@' AND SOURCE_COUNTRY_CODE = '@SOURCE_COUNTRY_CODE@') C_CRTD_CORE_PRTY
ON CONCAT('@DATA_SRC_EBB@', '-', '@SOURCE_COUNTRY_CODE@', '-', TRIM(MASTREL.RELATIONSHIPNO)) = TRIM(C_CRTD_CORE_PRTY.PRTY_SROGT_ID)c_aprvd_lmtmaster1006
