;EBB~SG~EBBS_SG_ACCOUNT~C_ACCT_MTRC~1400302SGEBBSELECT
CONCAT('@DATA_SRC_EBB@', '-', '@SOURCE_COUNTRY_CODE@', '-', trim(account.CURRENCYCODE), '-', trim(account.ACCOUNTNO)) as ACCT_SROGT_ID
,CONCAT('@DATA_SRC_EBB@', '-', '@SOURCE_COUNTRY_CODE@', '-', trim(account.PRODUCTCODE)) as PROD_SROGT_ID
,CONCAT('@DATA_SRC_EBB@', '-', '@SOURCE_COUNTRY_CODE@', '-', trim(mastrel.RELATIONSHIPNO)) as PRTY_SROGT_ID
,CONCAT(trim(account.CURRENCYCODE), '-', trim(account.ACCOUNTNO)) as DOM_ACCT_REF
,account.PRODUCTCODE as DOM_PROD_CD
,mastrel.RELATIONSHIPNO as DOM_PRTY_REF
,account.CURRENCYCODE as ACCT_CURY_CD
,ptrnstat.CREDITAMOUNT as LAST_MNTHLY_INCM_AMT
,'EBB~SG~EBBS_SG_ACCOUNT~C_ACCT_MTRC~1' as PROCESS_ID
,from_unixtime(unix_timestamp()) as PPN_DTM
,'@DT_VRSN@' as DT_VRSN
,'@ACCS_CTRY_CD@' as ACCS_CTRY_CD
,wpm.ACCS_SEGMT_CD as ACCS_SEGMT_CD
,'@MNTHEND_FL@' as MNTHEND_FL
FROM
(SELECT * FROM @SOURCE_EBB@.EBBS_SG_ACCOUNT WHERE ods = '@ODS_EBB@') account
LEFT JOIN
(SELECT currencycode, accountno, creditamount FROM @SOURCE_EBB@.EBBS_SG_PTRNSTAT WHERE ods = '@ODS_EBB@' AND STATGROUPCODE='PAY') ptrnstat
ON ptrnstat.CURRENCYCODE = account.CURRENCYCODE AND ptrnstat.ACCOUNTNO = account.ACCOUNTNO
LEFT JOIN
(SELECT relationshipno, masterno FROM @SOURCE_EBB@.EBBS_SG_MASTREL WHERE ods = '@ODS_EBB@' AND primaryflag = 'Y') mastrel
ON trim(account.MASTERNO) = trim(mastrel.MASTERNO)
LEFT JOIN
(SELECT accs_segmt_cd, prty_srogt_id FROM @TARGET_WORK@.C_CRTD_CORE_PRTY
WHERE process_date = '@PSE_DATE@' AND data_src = '@DATA_SRC_EBB@' AND source_country_code ='@SOURCE_COUNTRY_CODE@') wpm
ON concat('@DATA_SRC_EBB@', '-', '@SOURCE_COUNTRY_CODE@', '-', trim(mastrel.RELATIONSHIPNO)) = wpm.PRTY_SROGT_IDc_acct_mtrcmaster1008

;EBB~SG~EBBS_SG_MMKDEAL~C_ACCT_MTRC~1400302SGEBBSELECT
CONCAT('@DATA_SRC_EBB@', '-', '@SOURCE_COUNTRY_CODE@', '-', TRIM(MMKDEAL.DEALNO)) AS ACCT_SROGT_ID
,CONCAT('@DATA_SRC_EBB@', '-', '@SOURCE_COUNTRY_CODE@', '-', TRIM(MDELTYP.PRODUCTCODE)) AS PROD_SROGT_ID
,CONCAT('@DATA_SRC_EBB@', '-', '@SOURCE_COUNTRY_CODE@', '-', TRIM(MASTREL.RELATIONSHIPNO)) AS PRTY_SROGT_ID
,MMKDEAL.DEALNO AS DOM_ACCT_REF
,MDELTYP.PRODUCTCODE AS DOM_PROD_CD
,MASTREL.RELATIONSHIPNO AS DOM_PRTY_REF
,MMKDEAL.DEALCURRCD AS ACCT_CURY_CD
,'EBB' AS DATA_SRC
,'SG' AS SOURCE_COUNTRY_CODE
,'SG' AS ACCS_CTRY_CD
,WPM.ACCS_SEGMT_CD AS ACCS_SEGMT_CD
,'EBB~SG~EBBS_SG_MMKDEAL~C_ACCT_MTRC~1' AS PROCESS_ID
,MMKDEAL.ORIGINALDEALAMT AS ORIG_DEP_AMT
--LDC changes 3.3 start ----
,MMKDEAL.LIENAMOUNT AS LIEN_AMT
--LDC changes 3.3 end ----
FROM(SELECT LIENAMOUNT,DEALNO,DEALCURRCD,CUSTTCID,MMKDEALTYPE,ORIGINALDEALAMT FROM @SOURCE_EBB@.EBBS_SG_MMKDEAL WHERE ods = '@ODS_EBB@') MMKDEAL
LEFT JOIN (SELECT RELATIONSHIPNO,MASTERNO,PRIMARYFLAG FROM @SOURCE_EBB@.EBBS_SG_MASTREL WHERE ods = '@ODS_EBB@') MASTREL ON TRIM(MMKDEAL.CUSTTCID) = TRIM(MASTREL.MASTERNO) AND MASTREL.PRIMARYFLAG = 'Y'
LEFT JOIN (SELECT ACCS_SEGMT_CD,PRTY_SROGT_ID,DATA_SRC,SOURCE_COUNTRY_CODE,process_date FROM @TARGET_WORK@.C_CRTD_CORE_PRTY WHERE process_date = '@PSE_DATE@' AND data_src = '@DATA_SRC_EBB@' AND source_country_code ='@SOURCE_COUNTRY_CODE@') WPM on CONCAT('EBB-SG-', TRIM(MASTREL.RELATIONSHIPNO)) = WPM.PRTY_SROGT_ID AND WPM.DATA_SRC = '@DATA_SRC_EBB@' AND WPM.SOURCE_COUNTRY_CODE ='@SOURCE_COUNTRY_CODE@'
LEFT JOIN(SELECT PRODUCTCODE,MMKDEALTYPE FROM @SOURCE_EBB@.EBBS_SG_MDELTYP WHERE ods = '@ODS_EBB@') MDELTYP ON TRIM(MMKDEAL.MMKDEALTYPE) = TRIM(MDELTYP.MMKDEALTYPE)c_acct_mtrcmaster10018