;EBB~SG~EBBS_SG_MMKDEAL~C_ACCT~1400302SGEBBSELECT
concat('@DATA_SRC_EBB@', '-', '@SOURCE_COUNTRY_CODE@', '-', trim(mmkdeal.DEALNO)) as ACCT_SROGT_ID
,mmkdeal.DEALNO as DOM_ACCT_REF
,'CORE' as ACCT_CLAS
,'Deal' as ACCT_SUB_CLAS
,mdeltyp.DEPOSITORLOAN as ACCT_TP_CD
,depln.ACCT_TP_DESC as ACCT_TP_DESC
,mmkdeal.STATUSFLAG as ACCT_STS_TP_CD
,stsfl.ACCT_STS_TP_DESC as ACCT_STS_TP_DESC
,mmkdeal.DEALDT as ACCT_OPEN_DT
,mmkdeal.DEALCURRCD as ACCT_CURY_CD
,concat('@DATA_SRC_EBB@', '-', '@SOURCE_COUNTRY_CODE@', '-', trim(mastrel.RELATIONSHIPNO)) as PRTY_SROGT_ID
,mastrel.RELATIONSHIPNO as DOM_PRTY_REF
,mast.ARMCODE as ARM_CD
,concat('@DATA_SRC_EBB@', '-', '@SOURCE_COUNTRY_CODE@', '-', trim(mdeltyp.PRODUCTCODE)) as PROD_SROGT_ID
,mdeltyp.PRODUCTCODE as DOM_PROD_CD
,concat('@DATA_SRC_EBB@', '-', '@SOURCE_COUNTRY_CODE@', '-', trim(mmkdeal.DEALBRANCHCODE)) as ACCT_BRNCH_SROGT_ID
,mmkdeal.DEALBRANCHCODE as ACCT_BRNCH_CD
,mmkdeal.INTERESTCODE as INT_CD
,mmkdeal.TERMVAL as TENOR
,mmkdeal.TERMTYPE as TENOR_TP_CD
,tentp.TENOR_TP_DESC as TENOR_TP_DESC
,mmkdeal.MATURITYDT as MATURTY_DT
,t.FREQUENCY as STMT_CYC_FREQ
,t.LASTSTMTDATE as CURR_STMT_DT
,mast.ACCTTYPE as INTN_OR_CUST_ACCT_IND
,t.STMTTYPECODE as STMT_CD
,stmttyp.DESCRIPTION as STMT_DESC
,mmkdeal.CUSTTCID as DOM_MAST_REF
,mast.INSTCLASSCODE as INST_CLAS_CD
,instcls.DESCRIPTION as INST_CLAS_DESC
,instcls.ISSTAFFCLASS as SCB_STAF_FL
,mast.ISICCODE as ISIC_CD
,isic.DESCRIPTION as ISIC_DESC
,mast.CUSTSEGMTCODE as SEGMT_CD
,custseg.DESCRIPTION as SEGMT_DESC
,mast.SEGMENTCODE as SUB_SEGMT_CD
,seg.NAME as SUB_SEGMT_CD_DESC
,mmkdeal.MMKDEALTYPE as DEAL_TP_CD
,mdeltyp.DESCRIPTION as DEAL_TP_DESC
,mmkdeal.ROLLOVERFLAG as ROLLOVR_IND
,'EBB~SG~EBBS_SG_MMKDEAL~C_ACCT~1' as PROCESS_ID
,from_unixtime(unix_timestamp()) as PPN_DTM
,'@DT_VRSN@' as DT_VRSN
,'@ACCS_CTRY_CD@' as ACCS_CTRY_CD
,w_prty_mast.ACCS_SEGMT_CD as ACCS_SEGMT_CD
,'@MNTHEND_FL@' as MNTHEND_FL

---
,mmkdeal.DSRREFERRALID AS REFL_ID
,mmkdeal.DSRSOURCINGID AS SRCG_ID
,mmkdeal.DSRCLOSINGID AS CLSG_ID
,CASE WHEN MMKDEAL.STATUSFLAG = '14' THEN MMKDEAL.CHECKERDATE ELSE 'NULL' END AS ACCT_CLSE_DT
,mmkdeal.CHANNELID as ACQ_CHNL_CD

----
,CASE WHEN mmkdeal.MMKDEALTYPE IN ('CDAF','FBFD','FCFD','FCFS','FIDE','FLDP','SBFD','SFLD','STDE','STFD','RESR','MS06','CDA','FTDE','NBEX','RESF','STFF','MS12','MTDE','TSM1','3','EFD7','AMG8','TMFC','SCSF','TSM3','NBFD','TSM2','NRER',
'SCSR','STFR','SPA3','FTD2','NBCB','NREF','13','AMG7','FD22','AMGI','FCNR','GIAS','RSIM','MIPN','SAM6','SGIA','SPA4','ZNRR','GIA3','UNC1','FCN1','MIPI','ZRSF','FDIC','AMG2','TDFC','209','STIP','RFCR','RUTD','SMIP',
'GIA4','CNPD','STFT','RFCD','ZSSR','DDA','ZSSF','212','55','SPA6','SPAM','17','RSV','AMG4','YNRO','SAMG','ZRSR','AMG1','SPA5','ZNRF','SAM7','RD6N','SAM1','EFD1','AMG5','FCNU','FCR3','ZFC1','SAM2','ZRMI','FD24','EF10',
'621','SAM4','FD26','GIA1','FD23','FD27','EFD2','AMG6','GIA2','FD25') THEN 'TIMEDEPOSIT' ELSE  '' END  as DEAL_CAT_DESC
,mmkdeal.FUNDSACCTNO as FUND_ACCT_NUM
,mmkdeal.LASTREPRICINGDT as LAST_REPRCG_DT
,mmkdeal.NEXTREPRICINGDT as NXT_REPRCG_DT
,mdeltyp.ISISLAMIC as ISLAMIC_FL
,mmkdeal.CHECKERID as CHECKER_ID
--- Oct change
,mmkdeal.CAPITALISEFLAG as ROLLOVR_INT_CPTLZD_FL
---LDC 4.1V STARTS---
,mmkdeal.REPRICINGFREQ AS RPRCNG_FREQ
,mmkdeal.REPRICESTRTDT AS RPRCNG_STRT_DT
,mdeltyp.STEPUPDEPOSIT AS STEP_UP_DEP_IND
,INTRST.DESCRIPTION AS INT_DESC
---LDC 4.1V ENDS---

---drop14 changes---
,mast.OPERATINGINS as ACCT_OPRT_INSTR_CD
,AOICD.ACCT_OPRT_INSTR_DESC as ACCT_OPRT_INSTR_DESC


FROM (SELECT * FROM @SOURCE_EBB@.EBBS_SG_MMKDEAL WHERE ods = '@ODS_EBB@') mmkdeal
LEFT JOIN
(SELECT relationshipno, masterno, primaryflag FROM @SOURCE_EBB@.EBBS_SG_MASTREL WHERE ods = '@ODS_EBB@' AND primaryflag = 'Y') mastrel
ON trim(mmkdeal.CUSTTCID) = trim(mastrel.MASTERNO)
LEFT JOIN
(SELECT prty_srogt_id, accs_segmt_cd FROM @TARGET_WORK@.C_CRTD_CORE_PRTY
WHERE process_date = '@PSE_DATE@' AND data_src = '@DATA_SRC_EBB@' AND source_country_code = '@SOURCE_COUNTRY_CODE@') w_prty_mast
ON concat('@DATA_SRC_EBB@', '-', '@SOURCE_COUNTRY_CODE@', '-', trim(mastrel.RELATIONSHIPNO)) = w_prty_mast.PRTY_SROGT_ID
LEFT JOIN
(SELECT depositorloan, productcode, description, mmkdealtype,ISISLAMIC,STEPUPDEPOSIT FROM @SOURCE_EBB@.EBBS_SG_MDELTYP WHERE ods = '@ODS_EBB@') mdeltyp
ON trim(mmkdeal.MMKDEALTYPE) = trim(mdeltyp.MMKDEALTYPE)
LEFT JOIN
(SELECT dom_desc as acct_tp_desc, dom_cd FROM @SOURCE_REF@.C_REF_DAT_MAP
WHERE trim(source_country_code) = '@SOURCE_COUNTRY_CODE@' and trim(data_src) = '@DATA_SRC_EBB@' and trim(map_tp_cd) = 'DEPLN') depln
ON mdeltyp.DEPOSITORLOAN = depln.DOM_CD
LEFT JOIN
(SELECT dom_desc as acct_sts_tp_desc, dom_cd FROM @SOURCE_REF@.C_REF_DAT_MAP
WHERE trim(source_country_code) = '@SOURCE_COUNTRY_CODE@' and trim(data_src) = '@DATA_SRC_EBB@' and trim(map_tp_cd) = 'STSFL') stsfl
ON mmkdeal.STATUSFLAG = stsfl.DOM_CD
LEFT JOIN
(SELECT dom_desc as tenor_tp_desc, dom_cd FROM @SOURCE_REF@.C_REF_DAT_MAP
WHERE trim(source_country_code) = '@SOURCE_COUNTRY_CODE@' and trim(data_src) = '@DATA_SRC_EBB@' and trim(map_tp_cd) = 'TENTP') tentp
ON mmkdeal.TERMTYPE = tentp.DOM_CD
LEFT JOIN
(SELECT base.DEALNO, base.SEQNO, base.LASTSTMTDATE, base.FREQUENCY, base.STMTTYPECODE
FROM (SELECT row_number() OVER (partition by dealno order by seqno desc) as MAX_ROW
,dealno
,seqno
,laststmtdate
,frequency
,stmttypecode
FROM (SELECT * FROM @SOURCE_EBB@.EBBS_SG_DLSTMT WHERE ods = '@ODS_EBB@') dlstmt) base where base.MAX_ROW = 1) t
ON trim(mmkdeal.DEALNO) = trim(t.DEALNO)
LEFT JOIN
(SELECT armcode, accttype, instclasscode, isiccode, custsegmtcode, segmentcode, masterno, OPERATINGINS FROM @SOURCE_EBB@.EBBS_SG_MAST WHERE ods = '@ODS_EBB@') mast
ON trim(mmkdeal.CUSTTCID) = trim(mast.MASTERNO)
LEFT JOIN
(SELECT description, isstaffclass, instclasscode FROM @SOURCE_EBB@.EBBS_SG_INSTCLS WHERE ods = '@ODS_EBB@') instcls
ON mast.INSTCLASSCODE = instcls.INSTCLASSCODE
LEFT JOIN
(SELECT description, custsegmtcode FROM @SOURCE_EBB@.EBBS_SG_CUSTSEG WHERE ods = '@ODS_EBB@') custseg
ON mast.CUSTSEGMTCODE = custseg.CUSTSEGMTCODE
LEFT JOIN
(SELECT name, segmentcode FROM @SOURCE_EBB@.EBBS_SG_SEG WHERE ods = '@ODS_EBB@') seg
ON mast.SEGMENTCODE = seg.SEGMENTCODE
LEFT JOIN
(SELECT description, isiccode FROM @SOURCE_EBB@.EBBS_SG_ISIC WHERE ods = '@ODS_EBB@') isic
ON mast.ISICCODE = isic.ISICCODE
LEFT JOIN
(SELECT description, stmttypecode FROM @SOURCE_EBB@.EBBS_SG_STMTTYP WHERE ods = '@ODS_EBB@') stmttyp
ON t.STMTTYPECODE = stmttyp.STMTTYPECODE
LEFT JOIN 
(select DESCRIPTION,INTERESTCODE FROM @SOURCE_EBB@.EBBS_SG_INT WHERE ods = '@ODS_EBB@') INTRST
on INTRST.INTERESTCODE = MMKDEAL.INTERESTCODE
LEFT JOIN (SELECT DOM_CD,DOM_DESC AS ACCT_OPRT_INSTR_DESC FROM @SOURCE_REF@.C_REF_DAT_MAP WHERE SOURCE_COUNTRY_CODE = '@SOURCE_COUNTRY_CODE@' AND DATA_SRC = '@DATA_SRC_EBB@' AND MAP_TP_CD = 'AOICD') AOICD 
ON MAST.OPERATINGINS = AOICD.DOM_CDc_acctmaster1002
