;EBB~SG~EBBS_SG_BRN~C_BRNCH~1400303SGEBBSELECT
CONCAT('@DATA_SRC_EBB@','-','@SOURCE_COUNTRY_CODE@','-',TRIM(BRN.BRANCHCODE)) AS BRNCH_SROGT_ID
,BRN.BRANCHCODE AS BRNCH_CD
,BRN.NAME AS BRNCH_NM
,BRN.ADDRESS1 AS ADDR_LN_1
,BRN.ADDRESS2 AS ADDR_LN_2
,BRN.ADDRESS3 AS ADDR_LN_3
,BRN.ADDRESS4 AS ADDR_LN_4
,BRN.ADDRESS5 AS ADDR_LN_5
,BRN.ADDRESS6 AS ADDR_LN_6
,BRN.AREACODE AS PSTL_CD
,BRN.ENTITYCODE AS ENTY_CD
,BRN.SWIFTADDRESS AS SWFT_CD
,'EBB~SG~EBBS_SG_BRN~C_BRNCH~1' AS PROCESS_ID
,from_unixtime(unix_timestamp()) AS PPN_DTM
,'@DT_VRSN@' AS DT_VRSN
,'@ACCS_CTRY_CD@' AS ACCS_CTRY_CD
,'@MNTHEND_FL@' AS MNTHEND_FL
FROM @SOURCE_EBB@.EBBS_SG_BRN BRN WHERE ODS='@ODS_EBB@'c_brnchmaster1005