version: 2
sources:
  - name: sri_open_schema
    description: ''
    tables:
      - name: rdm_all_pgc_mstr_acct
        description: ''
      - name: rdm_all_pgc_mstr_cust_clas
        description: ''        
    tags: ['sit']
