    
{{ config(
    alias='prty_rtng5',
    materialized='table'
) }}

 -- 

 SELECT DISTINCT
  TRIM(CAST(SCI_ALL_LMPCRG.LCG_LE_ID AS STRING)) AS PRTY_ID,
  'SCI' AS SRC_SYS,
  'XX' AS CTRY_CD,
  SCI_ALL_LMPCRG.ODS AS STRT_DT,
  '9999-12-31' AS END_DT,
  NULL AS PRTY_CR_RISK_RTNG_AGNCY_TYPE,
  NULL AS PRTY_CR_RISK_RTNG_CCY,
  SCI_ALL_LMPCRG.LCG_CRDT_GRD_CD_VAL AS PRTY_CR_RISK_RTNG_CD,
  SCI_ALL_LMPCRG.LCG_CRDT_GRD_TP_VAL AS PRTY_CR_RISK_RTNG_TYPE,
  'MainProfileCreditGrade' AS RTNG_CAT_CD,
  SCI_ALL_LMPCRG.LCG_CRDT_GRD_DESC AS PRTY_CR_RISK_RTNG_CD_DESC,
  SCI_ALL_LMPCRG.LCG_CRDT_GRD_START_DT AS PRTY_CR_RISK_RTNG_STRT_DT,
  SCI_ALL_LMPCRG.LCG_APPR_EMP_ID AS APRV_EMP_ID,
  SCI_ALL_LMPCRG.ODS AS ODS
FROM (
  SELECT
    ODS,
    LCG_LE_ID,
    LCG_CRDT_GRD_CD_VAL,
    LCG_CRDT_GRD_DESC,
    LCG_CRDT_GRD_START_DT,
    LCG_CRDT_GRD_TP_VAL,
    LCG_APPR_EMP_ID,
    ROW_NUMBER() OVER (
      PARTITION BY LCG_LE_ID, LCG_CRDT_GRD_CD_VAL, LCG_CRDT_GRD_TP_VAL
      ORDER BY LCG_CRDT_GRD_START_DT DESC, LAST_UPD_DT DESC, UPD_COUNT DESC
    ) AS MAXID
  FROM {{ source('sri_open_schema', 'sci_all_lmpcrg') }} AS sci_all_lmpcrg
  WHERE
    ODS = '{{ var('__ods_val__') }}'
) AS SCI_ALL_LMPCRG
WHERE
  SCI_ALL_LMPCRG.ODS = '{{ var('__ods_val__') }}' AND MAXID = 1
 